Repository Siteimprove/alfa, pull requests merged in 2020-06, with the labels that each got.

#237 Improve table building
  packages/alfa-table/package.json
  packages/alfa-table/src/cell.ts
  packages/alfa-table/src/row-group.ts
  packages/alfa-table/src/row.ts
  packages/alfa-table/src/table.ts
  packages/alfa-table/test/table.spec.ts
  packages/alfa-table/test/testcases.tsx
  packages/alfa-table/tsconfig.json
Labels: major

#243 Disallow `Fragment` nodes from having parents
  packages/alfa-dom/src/node/fragment.ts
Labels: patch

#244 Add `Document#frame` property to better model embedded documents
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/src/node/document.ts
  packages/alfa-dom/src/node/element.ts
Labels: major

#245 Allow passing traversal options to `Node#path()`
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/src/node/attribute.ts
  packages/alfa-dom/src/node/comment.ts
  packages/alfa-dom/src/node/document.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/shadow.ts
  packages/alfa-dom/src/node/text.ts
Labels: minor

#248 Move formatters out of the CLI and into their own packages
  packages/alfa-cli/bin/alfa/commands/audit.ts
  packages/alfa-cli/bin/alfa/commands/scrape.ts
  packages/alfa-cli/package.json
  packages/alfa-cli/src/formatter.ts
  packages/alfa-cli/src/index.ts
  packages/alfa-cli/tsconfig.json
  packages/alfa-formatter-earl/package.json
  packages/alfa-formatter-earl/src/earl.ts
  packages/alfa-formatter-earl/src/index.ts
  packages/alfa-formatter-earl/tsconfig.json
  packages/alfa-formatter-json/package.json
  packages/alfa-formatter-json/src/index.ts
  packages/alfa-formatter-json/src/json.ts
  packages/alfa-formatter-json/tsconfig.json
  packages/alfa-formatter/package.json
  packages/alfa-formatter/src/formatter.ts
  packages/alfa-formatter/src/index.ts
  packages/alfa-formatter/tsconfig.json
  packages/tsconfig.json
Labels: major

#249 Allow passing headers and cookies to `Scraper#scrape()` and the CLI
  packages/alfa-cli/bin/alfa/commands/scrape.ts
  packages/alfa-http/src/cookie.ts
  packages/alfa-http/src/cookies.ts
  packages/alfa-http/src/header.ts
  packages/alfa-http/src/headers.ts
  packages/alfa-http/src/index.ts
  packages/alfa-http/src/request.ts
  packages/alfa-http/src/response.ts
  packages/alfa-http/tsconfig.json
  packages/alfa-scraper/src/scraper.ts
Labels: major

#250 Implement a SARIF formatter
  packages/alfa-formatter-sarif/package.json
  packages/alfa-formatter-sarif/src/index.ts
  packages/alfa-formatter-sarif/src/sarif.ts
  packages/alfa-formatter-sarif/tsconfig.json
  packages/tsconfig.json
Labels: minor

#253 Use `Awaiter.loaded` as the default in `Scraper#scrape()`
  packages/alfa-scraper/src/scraper.ts
Labels: patch

#254 Use `Timeout` and not `number` for timeouts in `Awaiter`
  packages/alfa-scraper/src/awaiter.ts
  packages/alfa-scraper/src/scraper.ts
Labels: major

#256 Fix background computation in SIA-R69
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/test/common/oracle.ts
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
Labels: patch

#257 Add missing dependency and project references
  docs/examples/component-testing/react/package.json
  docs/examples/component-testing/vue/package.json
  packages/alfa-act/package.json
  packages/alfa-act/tsconfig.json
  packages/alfa-angular/package.json
  packages/alfa-angular/tsconfig.json
  packages/alfa-aria/package.json
  packages/alfa-assert/package.json
  packages/alfa-assert/tsconfig.json
  packages/alfa-chai/package.json
  packages/alfa-chai/tsconfig.json
  packages/alfa-cli/package.json
  packages/alfa-cli/tsconfig.json
  packages/alfa-css/package.json
  packages/alfa-css/tsconfig.json
  packages/alfa-cypress/package.json
  packages/alfa-cypress/tsconfig.json
  packages/alfa-dom/package.json
  packages/alfa-dom/tsconfig.json
  packages/alfa-either/package.json
  packages/alfa-either/tsconfig.json
  packages/alfa-enzyme/package.json
  packages/alfa-enzyme/tsconfig.json
  packages/alfa-http/package.json
  packages/alfa-http/tsconfig.json
  packages/alfa-jasmine/package.json
  packages/alfa-jasmine/tsconfig.json
  packages/alfa-jest/package.json
  packages/alfa-jest/tsconfig.json
  packages/alfa-react/package.json
  packages/alfa-react/tsconfig.json
  packages/alfa-rules/package.json
  packages/alfa-rules/tsconfig.json
  packages/alfa-scraper/package.json
  packages/alfa-scraper/tsconfig.json
  packages/alfa-table/package.json
  packages/alfa-table/tsconfig.json
  packages/alfa-trilean/package.json
  packages/alfa-trilean/tsconfig.json
  packages/alfa-unexpected/package.json
  packages/alfa-unexpected/tsconfig.json
  packages/alfa-vue/package.json
  packages/alfa-vue/tsconfig.json
  packages/alfa-webdriver/package.json
  yarn.lock
Labels: internal

#259 Add scripting and user preferences as `Device` parameters
  packages/alfa-cli/bin/alfa/commands/scrape.ts
  packages/alfa-device/package.json
  packages/alfa-device/src/device.ts
  packages/alfa-device/src/index.ts
  packages/alfa-device/src/preference.ts
  packages/alfa-device/src/scripting.ts
  packages/alfa-device/tsconfig.json
  packages/alfa-hash/src/hash.ts
  packages/alfa-scraper/src/scraper.ts
Labels: major

#263 Lazy load syntax definitions
  packages/alfa-highlight/package.json
  packages/alfa-highlight/src/syntax.ts
  packages/alfa-highlight/types/emphasize.d.ts
Labels: major

#266 Prevent infinite instantiation of `Interview` type
  packages/alfa-act/src/interview.ts
  packages/alfa-act/src/rule.ts
  packages/alfa-rules/src/common/applicability/audio.ts
  packages/alfa-rules/src/common/applicability/video.ts
  packages/alfa-rules/src/sia-r23/rule.ts
  packages/alfa-rules/src/sia-r39/rule.ts
  packages/alfa-rules/src/sia-r82/rule.ts
Labels: patch

#264 Account for presentational role conflict resolution in ARIA feature mappings
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/node.ts
  packages/alfa-aria/src/role.ts
Labels: minor

#269 Treat kind attribute as enumerated
  packages/alfa-rules/src/common/applicability/video.ts
Labels: patch

#268 Rewrite the @siteimprove/alfa-math package
  packages/alfa-affine/src/transformation.ts
  packages/alfa-affine/test/transformation.spec.ts
  packages/alfa-affine/tsconfig.json
  packages/alfa-css/src/value/color/hsl.ts
  packages/alfa-css/src/value/numeric.ts
  packages/alfa-math/package.json
  packages/alfa-math/src/clamp.ts
  packages/alfa-math/src/equals.ts
  packages/alfa-math/src/index.ts
  packages/alfa-math/src/matrix.ts
  packages/alfa-math/src/mod.ts
  packages/alfa-math/src/real.ts
  packages/alfa-math/src/round.ts
  packages/alfa-math/src/vector.ts
  packages/alfa-math/test/matrix.spec.ts
  packages/alfa-math/test/vector.spec.ts
  packages/alfa-math/tsconfig.json
  packages/alfa-rules/src/sia-r44/rule.ts
  packages/alfa-rules/src/sia-r47/rule.ts
  packages/alfa-style/src/property/opacity.ts
  packages/alfa-style/src/resolver.ts
  packages/alfa-table/src/helpers.ts
  yarn.lock
Labels: major

#273 Move presentational role conflict resolution down to Role.from
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/node.ts
  packages/alfa-aria/src/role.ts
Labels: patch

#274 Avoid discarding rules when adding to `RuleTree`
  packages/alfa-cascade/src/rule-tree.ts
  packages/alfa-cascade/src/selector-map.ts
Labels: patch

#265 Rewrite the CLI internals
  packages/alfa-cli/bin/alfa.ts
  packages/alfa-cli/bin/alfa/command/audit.ts
  packages/alfa-cli/bin/alfa/command/audit/arguments.ts
  packages/alfa-cli/bin/alfa/command/audit/flags.ts
  packages/alfa-cli/bin/alfa/command/audit/run.ts
  packages/alfa-cli/bin/alfa/command/scrape.ts
  packages/alfa-cli/bin/alfa/command/scrape/arguments.ts
  packages/alfa-cli/bin/alfa/command/scrape/flags.ts
  packages/alfa-cli/bin/alfa/command/scrape/run.ts
  packages/alfa-cli/bin/alfa/commands/audit.ts
  packages/alfa-cli/bin/alfa/commands/scrape.ts
  packages/alfa-cli/bin/alfa/oracle.ts
  packages/alfa-cli/package.json
  packages/alfa-cli/src/index.ts
  packages/alfa-cli/tsconfig.json
  packages/alfa-command/package.json
  packages/alfa-command/src/argument.ts
  packages/alfa-command/src/command.ts
  packages/alfa-command/src/flag.ts
  packages/alfa-command/src/index.ts
  packages/alfa-command/src/text.ts
  packages/alfa-command/test/flag.spec.ts
  packages/alfa-command/test/text.spec.ts
  packages/alfa-command/tsconfig.json
  packages/tsconfig.json
  yarn.lock
Labels: major

#275 Use `Element.hasName()` in accessible name computation
  packages/alfa-aria/src/get-name.ts
Labels: internal

#277 Add initial support for `background` shorthand property
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/background.ts
  packages/alfa-style/src/style.ts
Labels: minor

#276 Speedup table building
  packages/alfa-table/src/cell.ts
  packages/alfa-table/src/row-group.ts
  packages/alfa-table/src/row.ts
  packages/alfa-table/src/table.ts
Labels: internal

#279 Add `Future#get()` and accept thunked promises in `Future.from()`
  packages/alfa-future/src/future.ts
  packages/alfa-future/test/future.spec.ts
Labels: minor

#278 Use dynamic import rather than `require()` for loading formatters
  packages/alfa-cli/bin/alfa/command/audit/run.ts
  packages/alfa-formatter/package.json
  packages/alfa-formatter/src/formatter.ts
Labels: major

#281 Introduce HyperScript-like DSL for constructing DOM
  packages/alfa-aria/test/get-name.spec.tsx
  packages/alfa-dom/h.ts
  packages/alfa-dom/package.json
  packages/alfa-dom/src/h.ts
  packages/alfa-dom/src/index.ts
  packages/alfa-dom/src/jsx.ts
  packages/alfa-dom/tsconfig.json
  packages/alfa-rules/test/sia-r45/rule.spec.tsx
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
  packages/alfa-rules/test/sia-r71/rule.spec.tsx
  packages/alfa-rules/test/sia-r72/rule.spec.tsx
  packages/alfa-rules/test/sia-r73/rule.spec.tsx
  packages/alfa-rules/test/sia-r74/rule.spec.tsx
  packages/alfa-rules/test/sia-r75/rule.spec.tsx
  packages/alfa-rules/test/sia-r80/rule.spec.tsx
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
  packages/alfa-rules/test/sia-r84/rule.spec.tsx
  packages/alfa-rules/test/sia-r85/rule.spec.tsx
  packages/alfa-table/test/testcases.tsx
Labels: major

#282 Correctly resolve important and overridden CSS properties
  packages/alfa-style/src/style.ts
  packages/alfa-style/test/style.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: patch

#272 Update SIA R67
  packages/alfa-aria/src/role.ts
  packages/alfa-dom/src/node/attribute.ts
  packages/alfa-rules/src/sia-r67/rule.ts
  packages/alfa-rules/test/sia-r67/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch
