Repository Siteimprove/alfa, pull requests merged in 2020-05, with the labels that each got.

#224 Update expectations of SIA-R45
  packages/alfa-rules/src/sia-r45/rule.ts
  packages/alfa-rules/test/sia-r45/rule.spec.tsx
Labels: patch

#222 Only look for `Element` nodes when determining ownership in SIA-R68
  packages/alfa-rules/src/sia-r68/rule.ts
  packages/alfa-rules/test/sia-r68/rule.spec.tsx
Labels: patch

#225 Reorganise @siteimprove/alfa-highlight
  packages/alfa-highlight/src/index.ts
  packages/alfa-highlight/src/marker.ts
  packages/alfa-highlight/src/syntax.ts
  packages/alfa-highlight/tsconfig.json
Labels: major

#226 Rework @siteimprove/alfa-scraper and @siteimprove/alfa-cli
  README.md
  docs/examples/page-testing/puppeteer/package.json
  packages/alfa-cli/bin/alfa/commands/audit.ts
  packages/alfa-cli/bin/alfa/commands/scrape.ts
  packages/alfa-cli/package.json
  packages/alfa-cli/src/index.ts
  packages/alfa-cli/src/oracle.ts
  packages/alfa-cli/tsconfig.json
  packages/alfa-device/src/viewport.ts
  packages/alfa-puppeteer/package.json
  packages/alfa-scraper/package.json
  packages/alfa-scraper/src/awaiter.ts
  packages/alfa-scraper/src/credentials.ts
  packages/alfa-scraper/src/index.ts
  packages/alfa-scraper/src/scraper.ts
  packages/alfa-scraper/src/screenshot.ts
  packages/alfa-scraper/tsconfig.json
  packages/alfa-time/package.json
  packages/alfa-time/src/index.ts
  packages/alfa-time/src/time.ts
  packages/alfa-time/src/timeout.ts
  packages/alfa-time/test/time.spec.ts
  packages/alfa-time/tsconfig.json
  packages/tsconfig.json
  yarn.lock
Labels: major

#187 Implement CSS fore- and background color properties
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/background.ts
  packages/alfa-style/src/property/color.ts
  packages/alfa-style/src/resolver.ts
  packages/alfa-style/tsconfig.json
Labels: minor

#181 Duplicate is streaming
  packages/alfa-rules/src/common/applicability/audio.ts
  packages/alfa-rules/src/common/applicability/video.ts
  packages/alfa-rules/test/sia-r24/rule.spec.tsx
  packages/alfa-rules/test/sia-r38/rule.spec.tsx
Labels: patch

#228 Provide initial implementation of SIA-R69
  packages/alfa-rules/src/common/question.ts
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#233 Correct parsing of `!important` CSS declarations
  packages/alfa-css/src/syntax/declaration.ts
  packages/alfa-css/test/syntax/declaration.spec.ts
  packages/alfa-css/tsconfig.json
Labels: patch

#235 Provide the option to disable JavaScript in `Scraper`
  packages/alfa-cli/bin/alfa/commands/scrape.ts
  packages/alfa-scraper/src/scraper.ts
Labels: minor

#231 Provide initial implementation of SIA-R82
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r82/rule.ts
  packages/alfa-rules/test/sia-r82/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#234 Implement SIA-R71, SIA-R72, SIA-R73, SIA-R74, SIA-R75, and SIA-R80
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r71/rule.ts
  packages/alfa-rules/src/sia-r72/rule.ts
  packages/alfa-rules/src/sia-r73/rule.ts
  packages/alfa-rules/src/sia-r74/rule.ts
  packages/alfa-rules/src/sia-r75/rule.ts
  packages/alfa-rules/src/sia-r80/rule.ts
  packages/alfa-rules/test/sia-r71/rule.spec.tsx
  packages/alfa-rules/test/sia-r72/rule.spec.tsx
  packages/alfa-rules/test/sia-r73/rule.spec.tsx
  packages/alfa-rules/test/sia-r74/rule.spec.tsx
  packages/alfa-rules/test/sia-r75/rule.spec.tsx
  packages/alfa-rules/test/sia-r80/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/line.ts
  packages/alfa-style/src/property/text.ts
  packages/alfa-style/tsconfig.json
Labels: minor

#238 Implement pseudo selector parsing
  packages/alfa-selector/src/selector.ts
Labels: patch

#242 Initial implementation of SIA-R83
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/text.ts
  packages/alfa-style/src/property/whitespace.ts
  packages/alfa-style/tsconfig.json
Labels: minor

#232 Provide initial implementation of SIA-R81
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/test/sia-r81/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#239 Provide initial implementation of SIA-R84
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r84/rule.ts
  packages/alfa-rules/test/sia-r84/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#241 Implement SIA-R85
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r85/rule.ts
  packages/alfa-rules/test/sia-r85/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/font.ts
Labels: minor
