Repository Siteimprove/alfa, pull requests merged in 2020-10, with the labels that each got.

#430 Implement step 2H of the accessible name computation
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/test/name.spec.tsx
Labels: patch

#437 Exclude from the accessibility tree text nodes of parent elements with `visibility: hidden`
  packages/alfa-aria/src/node.ts
  packages/alfa-aria/test/node.spec.tsx
Labels: patch

#426 Implement traversal API for `Graph`
  packages/alfa-graph/package.json
  packages/alfa-graph/src/graph.ts
  packages/alfa-graph/test/graph.spec.ts
  packages/alfa-graph/tsconfig.json
Labels: major

#442 Improve handling of cyclic `aria-owns` references
  packages/alfa-aria/package.json
  packages/alfa-aria/src/node.ts
  packages/alfa-aria/test/node.spec.tsx
  packages/alfa-aria/tsconfig.json
Labels: patch

#443 Implement ARIA presentational role inheritance
  packages/alfa-aria/src/node.ts
  packages/alfa-aria/test/node.spec.tsx
Labels: patch

#445 Fix several `Element#tabIndex()` cases
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/element/predicate.ts
  packages/alfa-dom/src/node/element/predicate/is-browsing-context-container.ts
  packages/alfa-dom/src/node/element/predicate/is-disabled.ts
  packages/alfa-dom/src/node/element/predicate/is-draggable.ts
  packages/alfa-dom/src/node/element/predicate/is-editing-host.ts
  packages/alfa-dom/src/node/element/predicate/is-suggested-focusable.ts
  packages/alfa-dom/test/node/element.spec.tsx
  packages/alfa-dom/tsconfig.json
  packages/alfa-rules/test/sia-r2/rule.spec.tsx
Labels: patch

#448 Implement style resolution for stateful pseudo classes
  packages/alfa-cascade/package.json
  packages/alfa-cascade/src/cascade.ts
  packages/alfa-cascade/src/rule-tree.ts
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-cascade/tsconfig.json
  packages/alfa-selector/package.json
  packages/alfa-selector/src/context.ts
  packages/alfa-selector/src/index.ts
  packages/alfa-selector/src/selector.ts
  packages/alfa-selector/test/selector.spec.tsx
  packages/alfa-selector/tsconfig.json
  packages/alfa-style/package.json
  packages/alfa-style/src/style.ts
  packages/alfa-style/test/style.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: major

#406 Don't require answers for `<iframe>` elements that definitely embed the same resource
  packages/alfa-dom/src/node/document.ts
  packages/alfa-rules/package.json
  packages/alfa-rules/src/common/predicate/reference-same-resource.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/test/sia-r15/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#481 Add support for `box-shadow` CSS property
  packages/alfa-css/src/index.ts
  packages/alfa-css/src/value/shadow.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/box.ts
  packages/alfa-style/test/property/box.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#427 Implement `Group` class for rules that target sets
  packages/alfa-rules/src/common/group.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/test/sia-r15/rule.spec.tsx
  packages/alfa-rules/test/sia-r81/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#482 Reverse `wrapsText()` conditions in SIA-R83
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
Labels: patch

#496 Implement `outline` CSS property
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/outline.ts
  packages/alfa-style/tsconfig.json
Labels: minor

#468 Implement SIA-R87
  packages/alfa-cascade/src/user-agent.ts
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/test/node.spec.tsx
  packages/alfa-dom/tsconfig.json
  packages/alfa-rules/package.json
  packages/alfa-rules/src/common/predicate/is-keyboard-actionable.ts
  packages/alfa-rules/src/common/predicate/is-rendered.ts
  packages/alfa-rules/src/common/predicate/is-transparent.ts
  packages/alfa-rules/src/common/predicate/is-visible.ts
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r87/rule.ts
  packages/alfa-rules/test/sia-r87/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
  packages/alfa-style/package.json
  packages/alfa-style/src/value.ts
  packages/alfa-style/tsconfig.json
Labels: minor
