Repository Siteimprove/alfa, pull requests merged in 2020-07, with the labels that each got.

#286 Pass rules during construction of `Audit` class rather than after
  README.md
  packages/alfa-act/src/audit.ts
  packages/alfa-act/src/rule.ts
  packages/alfa-assert/src/assert.ts
  packages/alfa-cli/bin/alfa/command/audit/run.ts
  packages/alfa-rules/src/index.ts
Labels: major

#289 Fix handling of gradients in SIA-R69
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
Labels: patch

#288 Refactor `Scraper#scrape()` internals to fix scraping of URLs with hash fragment
  packages/alfa-scraper/package.json
  packages/alfa-scraper/src/scraper.ts
  packages/alfa-scraper/test/fixture/internal-link.html
  packages/alfa-scraper/test/fixture/location-change-delayed.html
  packages/alfa-scraper/test/fixture/location-change-immediate.html
  packages/alfa-scraper/test/fixture/meta-refresh-delayed.html
  packages/alfa-scraper/test/fixture/meta-refresh-immediate.html
  packages/alfa-scraper/test/scraper.spec.ts
  packages/alfa-scraper/tsconfig.json
Labels: patch

#295 Implement support for CSS Custom Properties
  packages/alfa-css/src/syntax.ts
  packages/alfa-dom/src/h.ts
  packages/alfa-either/src/either.ts
  packages/alfa-parser/src/parser.ts
  packages/alfa-style/package.json
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/overflow.ts
  packages/alfa-style/src/style.ts
  packages/alfa-style/test/style.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#296 Correctly parse function component values
  packages/alfa-css/src/syntax/component.ts
  packages/alfa-style/test/style.spec.tsx
Labels: patch

#297 Fix URI
  packages/alfa-rules/src/sia-r53/rule.ts
Labels: patch
