Repository Siteimprove/alfa, pull requests merged in 2020-12, with the labels that each got.

#577 SIA R53: ignore headings that are not in the accessibility tree
  packages/alfa-rules/src/sia-r53/rule.ts
  packages/alfa-rules/test/sia-r53/rule.spec.tsx
Labels: patch

#586 SIA R90: Element with Presentational Children has no focusable descendants
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r90/rule.ts
  packages/alfa-rules/test/sia-r90/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#587 Support CSS properties `letter-spacing` and `word-spacing`
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/letter-spacing.ts
  packages/alfa-style/src/property/text.ts
  packages/alfa-style/src/property/word-spacing.ts
  packages/alfa-style/tsconfig.json
Labels: minor

#588 Check for pairwise (`overflow-x`, `width`) and (`overflow-y`, `height`) handling in `isPossiblyScrollable()`
  packages/alfa-rules/src/sia-r84/rule.ts
  packages/alfa-rules/test/sia-r84/rule.spec.tsx
Labels: patch

#589 SIA R61: Ignore headings that are not in the accessibility tree
  packages/alfa-rules/src/sia-r61/rule.ts
  packages/alfa-rules/test/sia-r61/rule.spec.tsx
Labels: patch

#590 Do not use Device.standard() when it's the default value
  packages/alfa-rules/test/sia-r53/rule.spec.tsx
  packages/alfa-rules/test/sia-r90/rule.spec.tsx
Labels: internal

#600 Improve performance of `:nth-*` selectors
  packages/alfa-selector/src/selector.ts
Labels: patch

#607 SIA R46: Accept header assigned only to other header cells
  packages/alfa-rules/src/sia-r46/rule.ts
  packages/alfa-rules/test/sia-r46/rule.spec.tsx
Labels: patch

#609 Implement SIA R94: menuitem has accessible name
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r94/rule.ts
  packages/alfa-rules/test/sia-r94/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#592 Implement SIA R91, R92, and R93 (text spacing)
  packages/alfa-rules/src/common/outcome/text-spacing.ts
  packages/alfa-rules/src/common/predicate/has-cascaded-value-declared-in-inline-style.ts
  packages/alfa-rules/src/common/predicate/has-inline-style-property.ts
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r91/rule.ts
  packages/alfa-rules/src/sia-r92/rule.ts
  packages/alfa-rules/src/sia-r93/rule.ts
  packages/alfa-rules/test/sia-r91/rule.spec.tsx
  packages/alfa-rules/test/sia-r92/rule.spec.tsx
  packages/alfa-rules/test/sia-r93/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#624 isVisible: take into account elements that are visible when empty
  packages/alfa-rules/src/common/predicate/is-visible.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
Labels: patch

#618 Improve `isPossiblyClipped()`
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
Labels: patch
