Repository Siteimprove/alfa, pull requests merged in 2020-09, with the labels that each got.

#350 Cache accessible names of `Text` nodes
  packages/alfa-aria/src/name.ts
Labels: internal

#355 Fix for `Lazy#map()` and `Lazy#flatMap()` possibly evaluating a `Lazy` multiple times
  CHANGELOG.md
  packages/alfa-aria/test/node.spec.tsx
  packages/alfa-lazy/src/lazy.ts
  packages/alfa-lazy/test/lazy.spec.ts
  packages/alfa-lazy/tsconfig.json
Labels: patch

#356 Improve ARIA `Node` construction performance
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/src/node.ts
  packages/alfa-aria/src/role.ts
  packages/alfa-aria/test/node.spec.tsx
  packages/alfa-rules/src/common/predicate/is-ignored.ts
  packages/alfa-rules/src/common/predicate/is-perceivable.ts
  packages/alfa-rules/test/sia-r21/rule.spec.tsx
  packages/alfa-rules/test/sia-r82/rule.spec.tsx
Labels: patch

#360 Remove step 2D of the accessible name computation
  packages/alfa-aria/src/name.ts
Labels: patch

#361 Fix `Map#size` being incorrectly reported
  CHANGELOG.md
  packages/alfa-map/src/node.ts
  packages/alfa-map/test/map.spec.ts
Labels: patch

#362 Expose elements in accessibility tree if they have a tab index
  packages/alfa-aria/src/node.ts
  packages/alfa-aria/test/node.spec.tsx
  packages/alfa-rules/test/sia-r13/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#367 Implement support for tree-structural pseudo-classes
  packages/alfa-css/src/syntax.ts
  packages/alfa-css/src/syntax/nth.ts
  packages/alfa-css/src/syntax/token.ts
  packages/alfa-css/test/syntax/nth.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-selector/src/selector.ts
  packages/alfa-selector/test/selector.spec.tsx
  packages/alfa-selector/tsconfig.json
Labels: minor

#371 Fix `separator` role handling and attribute retrieval in R16
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/test/sia-r16/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#380 Ensure that `<select>` elements can be named by connected `<label>` elements
  CHANGELOG.md
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/test/name.spec.tsx
Labels: patch

#376 Implement support for `calc()` expressions
  packages/alfa-css/package.json
  packages/alfa-css/src/index.ts
  packages/alfa-css/src/syntax/function.ts
  packages/alfa-css/src/value.ts
  packages/alfa-css/src/value/angle.ts
  packages/alfa-css/src/value/calculation.ts
  packages/alfa-css/src/value/dimension.ts
  packages/alfa-css/src/value/length.ts
  packages/alfa-css/src/value/numeric.ts
  packages/alfa-css/src/value/unit.ts
  packages/alfa-css/test/value/calculation.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-equatable/src/equatable.ts
  packages/alfa-record/package.json
  packages/alfa-record/src/record.ts
  packages/alfa-record/tsconfig.json
  packages/alfa-style/src/property/font.ts
  packages/alfa-style/test/property/font.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#387 Account for near-zero size clipped elements in `isVisible()`
  packages/alfa-rules/src/common/predicate/is-visible.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#394 Add remaining name computation steps for `<input>` and `<textarea>` elements
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/test/name.spec.tsx
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/element/predicate.ts
  packages/alfa-dom/src/node/element/predicate/has-input-type.ts
  packages/alfa-dom/tsconfig.json
  packages/alfa-predicate/src/predicate.ts
  packages/alfa-rules/src/common/predicate/has-input-type.ts
  packages/alfa-rules/src/sia-r10/rule.ts
  packages/alfa-rules/src/sia-r12/rule.ts
  packages/alfa-rules/src/sia-r28/rule.ts
  packages/alfa-rules/src/sia-r39/rule.ts
  packages/alfa-rules/tsconfig.json
Labels: patch

#383 Correctly handle children of `<iframe>` elements in accessibility tree and `isRendered()`
  packages/alfa-aria/src/node.ts
  packages/alfa-dom/src/node.ts
  packages/alfa-rules/src/common/predicate/is-rendered.ts
  packages/alfa-rules/src/sia-r57/rule.ts
  packages/alfa-rules/test/sia-r57/rule.spec.tsx
Labels: patch

#403 Implement matching for `(max|min)-(width|height)` features
  packages/alfa-media/src/index.ts
  packages/alfa-media/src/media.ts
  packages/alfa-media/src/resolver.ts
  packages/alfa-media/tsconfig.json
  packages/alfa-style/src/index.ts
  packages/alfa-style/src/resolver.ts
Labels: minor

#400 Ignore header cells of presentational tables in SIA-R46
  packages/alfa-rules/src/sia-r46/rule.ts
  packages/alfa-rules/test/sia-r46/rule.spec.tsx
Labels: patch

#398 Allow passing embedded and shadow content in `h()`
  packages/alfa-dom/src/h.ts
  packages/alfa-dom/src/node/shadow.ts
  packages/alfa-dom/test/h.spec.ts
Labels: major

#399 Make `<object>` elements with a content document focusable
  packages/alfa-dom/src/node/element.ts
  packages/alfa-rules/test/sia-r63/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#409 Adjust applicability of SIA-R14
  packages/alfa-rules/src/sia-r14/rule.ts
Labels: patch

#418 SIA-R68: Exclude elements with an `aria-busy=true` ancestor
  packages/alfa-rules/src/sia-r68/rule.ts
  packages/alfa-rules/test/sia-r68/rule.spec.tsx
Labels: patch

#414 Adjust applicability of SIA-R57
  packages/alfa-rules/src/sia-r57/rule.ts
  packages/alfa-rules/test/sia-r57/rule.spec.tsx
Labels: patch
