Repository Siteimprove/alfa, pull requests merged in 2020-11, with the labels that each got.

#511 Implement `text-decoration-*` CSS properties
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/text.ts
  packages/alfa-style/test/property/text.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#497 Implement SIA-R65
  packages/alfa-rules/src/sia-r65/rule.ts
  packages/alfa-rules/test/sia-r65/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#527 Ignore inclusive descendants of `aria-hidden=true` when computing accessible names
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/test/name.spec.tsx
  packages/alfa-rules/test/sia-r64/rule.spec.tsx
Labels: patch

#439 Pass rules to `Formatter`
  packages/alfa-cli/bin/alfa/command/audit/run.ts
  packages/alfa-formatter-earl/src/earl.ts
  packages/alfa-formatter-json/src/json.ts
  packages/alfa-formatter-sarif/src/sarif.ts
  packages/alfa-formatter/src/formatter.ts
Labels: major

#539 Support CSS text-indent property
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/text.ts
  packages/alfa-style/test/property/text.spec.tsx
Labels: minor

#541 Support CSS `position` property
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/position.ts
  packages/alfa-style/tsconfig.json
Labels: minor

#538 Implement SIA-R62
  packages/alfa-rules/src/common/predicate/has-outline.ts
  packages/alfa-rules/src/common/predicate/has-text-decoration.ts
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/src/sia-r65/rule.ts
  packages/alfa-rules/test/sia-r62/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#542 Support CSS box insets properties
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/box-insets.ts
  packages/alfa-style/test/property/box-insets.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#540 Check overflow handling of clipping ancestor in SIA-R83
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
Labels: patch

#555 SIA R16: make inapplicable to ignored elements
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/test/sia-r16/rule.spec.tsx
Labels: patch

#556 SIA R45: ignore tables with presentational role
  packages/alfa-rules/src/sia-r45/rule.ts
  packages/alfa-rules/test/sia-r45/rule.spec.tsx
Labels: patch

#554 SIA-R10: ignore disabled elements
  packages/alfa-rules/src/sia-r10/rule.ts
  packages/alfa-rules/test/sia-r10/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#549 Make elements with no content invisible
  packages/alfa-rules/src/common/predicate/is-rendered.ts
  packages/alfa-rules/src/common/predicate/is-transparent.ts
  packages/alfa-rules/src/common/predicate/is-visible.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
Labels: patch

#566 SIA R83: assume a used value for `normal` line-height
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
Labels: patch
