Repository Siteimprove/alfa, pull requests merged in 2021-03, with the labels that each got.

#728 Track ARIA editors draft
  packages/alfa-aria/scripts/attributes.js
  packages/alfa-aria/scripts/roles.js
  packages/alfa-aria/src/attribute/data.ts
  packages/alfa-aria/src/role.ts
  packages/alfa-aria/src/role/data.ts
  packages/alfa-rules/src/sia-r42/rule.ts
Labels: major

#729 Unbranch ARIA types
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/src/node.ts
  packages/alfa-aria/src/role.ts
  packages/alfa-aria/test/name.spec.tsx
  packages/alfa-aria/test/node.spec.tsx
  packages/alfa-rules/src/common/predicate/has-accessible-name.ts
  packages/alfa-rules/src/common/predicate/has-explicit-role.ts
  packages/alfa-rules/src/common/predicate/has-heading-level.ts
  packages/alfa-rules/src/common/predicate/has-implicit-role.ts
  packages/alfa-rules/src/common/predicate/has-role.ts
  packages/alfa-rules/src/common/predicate/is-ignored.ts
  packages/alfa-rules/src/sia-r10/rule.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r42/rule.ts
  packages/alfa-rules/src/sia-r57/rule.ts
  packages/alfa-rules/src/sia-r67/rule.ts
  packages/alfa-rules/src/sia-r68/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
Labels: major

#732 Refactor @siteimprove/alfa-selector
  CHANGELOG.md
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-selector/src/selector.ts
Labels: minor

#734 Limit SIA-R83 to non-inline, non-font relative heights
  CHANGELOG.md
  packages/alfa-css/src/value/length.ts
  packages/alfa-css/src/value/unit.ts
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
Labels: minor

#735 Make SIA-R87 automatically pass links that target descendants at the very beginning of a `main` landmark
  CHANGELOG.md
  packages/alfa-dom/src/node.ts
  packages/alfa-rules/src/common/predicate/is-at-the-start.ts
  packages/alfa-rules/src/sia-r87/rule.ts
  packages/alfa-rules/test/common/predicate/is-at-the-start.spec.tsx
  packages/alfa-rules/test/sia-r87/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#739 Correct handling of `opacity` when computing foreground color of elements
  CHANGELOG.md
  packages/alfa-rules/src/common/expectation/get-colors.ts
  packages/alfa-rules/test/common/expectation/get-colors.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#737 Add viewport fitting and animation awaiting to scraper and CLI
  packages/alfa-cli/bin/alfa/command/scrape/flags.ts
  packages/alfa-cli/bin/alfa/command/scrape/run.ts
  packages/alfa-scraper/package.json
  packages/alfa-scraper/src/awaiter.ts
  packages/alfa-scraper/src/scraper.ts
  packages/alfa-scraper/tsconfig.json
  yarn.lock
Labels: major

#741 Fix `isTransparent()` for text nodes of transparent elements
  CHANGELOG.md
  packages/alfa-rules/src/common/predicate/is-transparent.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
Labels: patch

#742 Fix parsing of font families specified as ident lists
  CHANGELOG.md
  packages/alfa-style/src/property/font-family.ts
  packages/alfa-style/src/property/font.ts
  packages/alfa-style/test/property/font-family.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: patch

#740 Add Chai assertions for Cypress integration
  CHANGELOG.md
  packages/alfa-chai/src/chai.ts
  packages/alfa-cypress/src/cypress.ts
  packages/alfa-cypress/src/cypress/add-command.ts
  packages/alfa-cypress/tsconfig.json
  packages/alfa-jasmine/src/jasmine.ts
  packages/alfa-jest/src/jest.ts
  packages/alfa-unexpected/src/unexpected.ts
Labels: major

#744 Don't consider `overflow: clip` as scrollable in SIA-R84
  CHANGELOG.md
  packages/alfa-rules/src/sia-r84/rule.ts
Labels: patch

#746 SIA-R84 should only consider elements scrollable along the x-axis if they specify `white-space: nowrap`
  CHANGELOG.md
  packages/alfa-rules/src/sia-r84/rule.ts
  packages/alfa-rules/test/sia-r84/rule.spec.tsx
Labels: patch

#745 Parse all pseudo-elements to avoid dropping declarations when encountering unmanaged ones
  CHANGELOG.md
  packages/alfa-selector/package.json
  packages/alfa-selector/src/selector.ts
  packages/alfa-selector/test/selector.spec.tsx
  packages/alfa-selector/tsconfig.json
  yarn.lock
Labels: patch

#750 Support `paragraph` role and use it in R62, R71, R72, R73, R74, R80, R85
  CHANGELOG.md
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/name.ts
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/src/sia-r71/rule.ts
  packages/alfa-rules/src/sia-r72/rule.ts
  packages/alfa-rules/src/sia-r73/rule.ts
  packages/alfa-rules/src/sia-r74/rule.ts
  packages/alfa-rules/src/sia-r80/rule.ts
  packages/alfa-rules/src/sia-r85/rule.ts
  packages/alfa-rules/test/sia-r62/rule.spec.tsx
  packages/alfa-rules/test/sia-r71/rule.spec.tsx
  packages/alfa-rules/test/sia-r72/rule.spec.tsx
  packages/alfa-rules/test/sia-r73/rule.spec.tsx
  packages/alfa-rules/test/sia-r74/rule.spec.tsx
  packages/alfa-rules/test/sia-r80/rule.spec.tsx
  packages/alfa-rules/test/sia-r85/rule.spec.tsx
Labels: patch
