Repository Siteimprove/alfa, pull requests merged in 2021-07, with the labels that each got.

#846 Aria attributes depending on element
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/test/node.spec.tsx
Labels: minor

#848 Make descendents of fully clipped nodes invisible
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/has-computed-style.ts
  packages/alfa-rules/src/common/predicate/is-clipped.ts
  packages/alfa-rules/src/common/predicate/is-visible.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#850 Activate R55 and R56
  packages/alfa-rules/src/rules.ts
Labels: minor

#834 Implement SIA-R54
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r54/rule.ts
  packages/alfa-rules/test/sia-r54/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#853 Refactor `Hash` and add additional methods
  packages/alfa-graph/test/graph.spec.ts
  packages/alfa-hash/src/constants.ts
  packages/alfa-hash/src/hash.ts
  packages/alfa-hash/src/index.ts
  packages/alfa-hash/tsconfig.json
  packages/alfa-map/test/map.spec.ts
  packages/alfa-network/test/network.spec.ts
Labels: minor

#855 Add `scratches` directory for experimenting
  README.md
  scratches/.gitignore
  scratches/tsconfig.json
  tsconfig.json
Labels: internal

#854 Implement SIA-R78
  packages/alfa-aria/src/node.ts
  packages/alfa-rules/src/common/expectation/get-nodes-between.ts
  packages/alfa-rules/src/common/expectation/lowest-common-ancestor.ts
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/is-at-the-start.ts
  packages/alfa-rules/src/common/predicate/is-content.ts
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r56/rule.ts
  packages/alfa-rules/src/sia-r78/rule.ts
  packages/alfa-rules/test/common/expectation/get-nodes-between.spec.tsx
  packages/alfa-rules/test/common/expectation/lowest-common-ancestor.spec.tsx
  packages/alfa-rules/test/common/predicate/is-at-the-start.spec.tsx
  packages/alfa-rules/test/sia-r78/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#859 Fix naming from subtree and implicitly referenced `<label>` elements
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/test/node.spec.tsx
Labels: patch

#858 Accept arbitrarily deeply nested children in `jsx()`
  docs/review/api/alfa-dom.api.md
  package.json
  packages/alfa-aria/test/node.spec.tsx
  packages/alfa-dom/src/jsx-runtime.ts
  packages/alfa-dom/src/jsx.ts
  yarn.lock
Labels: patch

#860 SIA-R62: accept decoration on ancestors and descendants of links.
  docs/review/api/alfa-collection.api.md
  docs/review/api/alfa-iterable.api.md
  docs/review/api/alfa-list.api.md
  docs/review/api/alfa-sequence.api.md
  docs/review/api/alfa-slice.api.md
  packages/alfa-collection/src/collection.ts
  packages/alfa-iterable/src/iterable.ts
  packages/alfa-list/src/list.ts
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/test/sia-r62/rule.spec.tsx
  packages/alfa-sequence/src/cons.ts
  packages/alfa-sequence/src/sequence.ts
  packages/alfa-slice/src/slice.ts
Labels: minor

#851 SIA-R75: Only report elements whose font size affect some text
  packages/alfa-rules/src/sia-r75/rule.ts
Labels: patch

#862 SIA R66 and R69: return `cantTell` when encountering a text shadow
  docs/review/api/alfa-css.api.md
  packages/alfa-css/src/value/length.ts
  packages/alfa-rules/src/common/expectation/get-colors.ts
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
  packages/alfa-style/src/index.ts
  packages/alfa-style/src/property/text-shadow.ts
  packages/alfa-style/test/property/text-shadow.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#866 Handle duplicate `id`s and `for` attributes in `Name.from()`
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/test/name.spec.tsx
Labels: patch
