Repository Siteimprove/alfa, pull requests merged in 2021-09, with the labels that each got.

#910 Implement SIA R76
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r46/rule.ts
  packages/alfa-rules/src/sia-r76/rule.ts
  packages/alfa-rules/test/sia-r76/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#869 Implement SIA-R79
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r79/rule.ts
  packages/alfa-rules/test/sia-r79/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#903 Add `Question.Rhetorical` to `@siteimprove/alfa-act`
  docs/review/api/alfa-act.api.md
  packages/alfa-act/package.json
  packages/alfa-act/src/interview.ts
  packages/alfa-act/src/question.ts
  packages/alfa-act/tsconfig.json
  yarn.lock
Labels: minor

#902 SIA-R87: Ask if the first focusable element is visible on focus
  packages/alfa-rules/src/sia-r87/rule.ts
  packages/alfa-rules/test/sia-r87/rule.spec.tsx
Labels: patch

#894 Add `@siteimprove/alfa-tuple` package
  docs/review/api/alfa-tuple.api.md
  packages/alfa-tuple/config/api.json
  packages/alfa-tuple/package.json
  packages/alfa-tuple/src/index.ts
  packages/alfa-tuple/src/tuple.ts
  packages/alfa-tuple/test/tuple.spec.ts
  packages/alfa-tuple/tsconfig.json
  packages/tsconfig.json
  yarn.lock
Labels: minor

#905 SIA-R7: ignores whitespace text nodes
  packages/alfa-rules/src/sia-r7/rule.ts
  packages/alfa-rules/test/sia-r7/rule.spec.tsx
Labels: patch

#907 Handle interposed backgrounds in `getForeground()` and `getBackground()`
  docs/review/api/alfa-cache.api.md
  docs/review/api/alfa-math.api.md
  docs/review/api/alfa-predicate.api.md
  packages/alfa-cache/package.json
  packages/alfa-cache/src/cache.ts
  packages/alfa-cache/tsconfig.json
  packages/alfa-math/src/real.ts
  packages/alfa-predicate/src/predicate.ts
  packages/alfa-rules/src/common/expectation/get-colors.ts
  packages/alfa-rules/src/common/expectation/get-offset-parent.ts
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/has-interposed-descendant.ts
  packages/alfa-rules/src/common/predicate/is-positioned.ts
  packages/alfa-rules/src/common/predicate/is-root.ts
  packages/alfa-rules/src/common/predicate/is-visible.ts
  packages/alfa-rules/src/sia-r66/rule.ts
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/common/expectation/get-colors.spec.tsx
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
  yarn.lock
Labels: minor

#900 SIA-R62: Add superscript and subscript as distinguishing features for links
  packages/alfa-cascade/src/user-agent.ts
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/test/sia-r62/rule.spec.tsx
Labels: minor

#911 `Autocomplete` can be inappropriate for its type and ignores `on`\`off`
  packages/alfa-rules/src/sia-r10/rule.ts
  packages/alfa-rules/test/sia-r10/rule.spec.tsx
Labels: patch

#912 Use `answerIf` where possible
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-act/src/question.ts
  packages/alfa-rules/src/common/question.ts
  packages/alfa-rules/src/sia-r65/rule.ts
  packages/alfa-rules/src/sia-r66/rule.ts
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/src/sia-r87/rule.ts
Labels: minor

#915 Implements ´programmatically hidden´
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/is-programmatically-hidden.ts
  packages/alfa-rules/tsconfig.json
Labels: minor

#913 Map `input[value]` to `aria-valuenow`
  packages/alfa-aria/src/feature.ts
Labels: patch

#920 Accept native `<video>` and `<audio>` controls in SIA-R49
  packages/alfa-rules/src/sia-r49/rule.ts
  packages/alfa-rules/test/sia-r49/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#924 SIA R83: streamline and simplify
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/has-non-wrapped-text.ts
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#925 Use Alfa's structure rather than native Map and Set
  packages/alfa-rules/src/sia-r46/rule.ts
  packages/alfa-rules/src/sia-r47/rule.ts
Labels: internal

#927 Update dependencies
  package.json
  packages/alfa-angular/package.json
  packages/alfa-cheerio/package.json
  packages/alfa-cli/bin/alfa/command/scrape/run.ts
  packages/alfa-compatibility/package.json
  packages/alfa-cypress/package.json
  packages/alfa-highlight/package.json
  packages/alfa-jasmine/package.json
  packages/alfa-jest/package.json
  packages/alfa-playwright/package.json
  packages/alfa-puppeteer/package.json
  packages/alfa-scraper/package.json
  packages/alfa-scraper/src/scraper.ts
  packages/alfa-url/src/url.ts
  packages/alfa-webdriver/package.json
  yarn.lock
Labels: dependencies

#928 SIA-R83: Only consider vertical clipping on fixed height elements
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
Labels: patch

#916 SIA-R21: Target not "programmatically hidden" elements that are not in the accessibility tree
  packages/alfa-rules/src/sia-r21/rule.ts
  packages/alfa-rules/test/sia-r21/rule.spec.tsx
Labels: patch

#932 SIA-R83: Consider that flex wrapping container definitely handle horizontal overflow
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
  packages/alfa-style/src/index.ts
  packages/alfa-style/src/property/flex-wrap.ts
  packages/alfa-style/tsconfig.json
Labels: patch

#934 SIA-R83: Support `flex-flow`
  packages/alfa-style/src/index.ts
  packages/alfa-style/src/property/flex-direction.ts
  packages/alfa-style/src/property/flex-flow.ts
  packages/alfa-style/tsconfig.json
Labels: patch

#935 Add additional `Thenable` helpers
  docs/review/api/alfa-thenable.api.md
  packages/alfa-thenable/package.json
  packages/alfa-thenable/src/thenable.ts
  packages/alfa-thenable/test/thenable.spec.ts
  packages/alfa-thenable/tsconfig.json
  yarn.lock
Labels: minor

#923 Implements SIA-R77
  packages/alfa-rules/src/sia-r77/rule.ts
  packages/alfa-rules/test/sia-r76/rule.spec.tsx
  packages/alfa-rules/test/sia-r77/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch
