Repository Siteimprove/alfa, pull requests merged in 2021-12, with the labels that each got.

#996 Add function to create a WCAG `Criterion` from its URI
  packages/alfa-wcag/src/criterion.ts
Labels: minor

#994 Add support for experimental rules, and ER62, ER87
  .yarn/releases/yarn-3.0.2.cjs
  packages/alfa-act/src/rule.ts
  packages/alfa-cascade/src/user-agent.ts
  packages/alfa-rules/src/experimental.ts
  packages/alfa-rules/src/index.ts
  packages/alfa-rules/src/sia-er62/rule.ts
  packages/alfa-rules/src/sia-er62/serialise.ts
  packages/alfa-rules/src/sia-er87/rule.ts
  packages/alfa-rules/src/tags/scope.ts
  packages/alfa-rules/src/tags/stability.ts
  packages/alfa-rules/test/sia-er62/rule.spec.tsx
  packages/alfa-rules/test/sia-er62/serialise.spec.ts
  packages/alfa-rules/test/sia-er87/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
  packages/alfa-style/src/property/value/tuple.ts
Labels: minor

#991 SIA-R14: Ignore punctuation in label names
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-rules/test/sia-r14/rule.spec.tsx
Labels: patch

#967 SIA-R62: Accept differences in `box-shadow`
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/src/sia-r62/serialise.ts
  packages/alfa-rules/test/sia-r62/rule.spec.tsx
  packages/alfa-rules/test/sia-r62/serialise.spec.ts
  packages/alfa-style/src/property/box-shadow.ts
  packages/alfa-style/test/property/box-shadow.spec.tsx
Labels: patch

#997 Add some framework tests
  packages/alfa-dom/src/node/element.ts
  packages/alfa-react/test/react.spec.tsx
  packages/alfa-react/tsconfig.json
  packages/alfa-vue/package.json
  packages/alfa-vue/test/vue.spec.ts
  packages/alfa-vue/tsconfig.json
  yarn.lock
Labels: internal

#1003 Accept title attribute for name of input type=image
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/test/name.spec.tsx
Labels: patch

#1004 Update Typescript and swap offsets order in `Shadow`
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-rules.api.md
  docs/review/api/alfa-wcag.api.md
  package.json
  packages/alfa-css/src/value/shadow.ts
  packages/alfa-rules/src/index.ts
  yarn.lock
Labels: major

#1006 Small fixes
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/experimental.ts
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r109/rule.ts
  packages/alfa-rules/src/sia-r75/rule.ts
  packages/alfa-rules/test/sia-r75/rule.spec.tsx
Labels: patch

#998 SIA-ER62: Accept difference in contrast of 3:1 or more as distinguishing feature
  packages/alfa-rules/src/common/diagnostic/contrast.ts
  packages/alfa-rules/src/common/expectation/get-colors.ts
  packages/alfa-rules/src/sia-er62/diagnostics.ts
  packages/alfa-rules/src/sia-er62/rule.ts
  packages/alfa-rules/test/common/expectation/get-colors.spec.tsx
  packages/alfa-rules/test/sia-er62/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#1009 Improve hasRequirement
  docs/review/api/alfa-act.api.md
  packages/alfa-act/src/rule.ts
Labels: minor
