Repository Siteimprove/alfa, pull requests merged in 2021-08, with the labels that each got.

#884 Revert "Bump github/codeql-action from 1.0.10 to 1.0.11"
  .github/workflows/scan.yml
Labels: actions, dependencies

#843 SIA-R83: jump to offset parent when searching for clipping ancestor
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
Labels: bug

#880 Pass text nodes in the first focusable element of the document in SIA-R57
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/node.ts
  packages/alfa-rules/src/sia-r57/rule.ts
  packages/alfa-rules/test/sia-r57/rule.spec.tsx
Labels: minor

#875 SIA-R62: accept different background image
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/src/sia-r62/serialise.ts
  packages/alfa-rules/test/sia-r62/rule.spec.tsx
  packages/alfa-rules/test/sia-r62/serialise.spec.ts
  packages/alfa-rules/tsconfig.json
  packages/alfa-style/src/property/background-origin.ts
Labels: minor

#896 Reject empty text nodes in SIA-R75
  packages/alfa-rules/src/sia-r75/rule.ts
  packages/alfa-rules/test/sia-r75/rule.spec.tsx
Labels: patch

#898 Don't count invisible text as possibly wrapped in SIA-R83
  packages/alfa-rules/src/common/predicate/has-non-wrapped-text.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
Labels: patch

#874 Implement SIA-R60
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r60/rule.ts
  packages/alfa-rules/test/sia-r60/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#870 Implement SIA-R70
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r70/rule.ts
  packages/alfa-rules/test/sia-r70/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor
