Repository Siteimprove/alfa, pull requests merged in 2021-04, with the labels that each got.

#753 Add additional vendor data to EARL and SARIF output
  packages/alfa-earl/src/earl.ts
  packages/alfa-formatter-earl/src/earl.ts
  packages/alfa-formatter-earl/tsconfig.json
  packages/alfa-formatter-sarif/src/sarif.ts
  packages/alfa-formatter-sarif/tsconfig.json
Labels: minor

#754 Support CSS `border-*` shorthand properties
  CHANGELOG.md
  packages/alfa-style/src/index.ts
  packages/alfa-style/src/property/background-image.ts
  packages/alfa-style/src/property/border-block-color.ts
  packages/alfa-style/src/property/border-block-end.ts
  packages/alfa-style/src/property/border-block-start.ts
  packages/alfa-style/src/property/border-block-style.ts
  packages/alfa-style/src/property/border-block-width.ts
  packages/alfa-style/src/property/border-block.ts
  packages/alfa-style/src/property/border-bottom.ts
  packages/alfa-style/src/property/border-color.ts
  packages/alfa-style/src/property/border-image-source.ts
  packages/alfa-style/src/property/border-image.ts
  packages/alfa-style/src/property/border-inline-color.ts
  packages/alfa-style/src/property/border-inline-end.ts
  packages/alfa-style/src/property/border-inline-start.ts
  packages/alfa-style/src/property/border-inline-style.ts
  packages/alfa-style/src/property/border-inline-width.ts
  packages/alfa-style/src/property/border-inline.ts
  packages/alfa-style/src/property/border-left.ts
  packages/alfa-style/src/property/border-radius.ts
  packages/alfa-style/src/property/border-right.ts
  packages/alfa-style/src/property/border-style.ts
  packages/alfa-style/src/property/border-top.ts
  packages/alfa-style/src/property/border-width.ts
  packages/alfa-style/src/property/border.ts
  packages/alfa-style/src/resolver.ts
  packages/alfa-style/test/property/border-[block,inline]-[end,start]-color.spec.tsx
  packages/alfa-style/test/property/border-[block,inline]-[end,start]-style.spec.tsx
  packages/alfa-style/test/property/border-[block,inline]-[end,start]-width.spec.tsx
  packages/alfa-style/test/property/border-[block,inline]-[end,start].spec.tsx
  packages/alfa-style/test/property/border-[block,inline].spec.tsx
  packages/alfa-style/test/property/border-[top,bottom]-[left,right]-radius.spec.tsx
  packages/alfa-style/test/property/border-[top,right,bottom,left]-color.spec.tsx
  packages/alfa-style/test/property/border-[top,right,bottom,left]-style.spec.tsx
  packages/alfa-style/test/property/border-[top,right,bottom,left]-width.spec.tsx
  packages/alfa-style/test/property/border-[top,right,bottom,left].spec.tsx
  packages/alfa-style/test/property/border-image-outset.spec.tsx
  packages/alfa-style/test/property/border-image-slice.spec.tsx
  packages/alfa-style/test/property/border-image-source.spec.tsx
  packages/alfa-style/test/property/border-image-width.spec.tsx
  packages/alfa-style/test/property/border-image.spec.tsx
  packages/alfa-style/test/property/border.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#438 Implement support for radial CSS gradients
  packages/alfa-css/src/index.ts
  packages/alfa-css/src/value/gradient.ts
  packages/alfa-css/src/value/gradient/linear.ts
  packages/alfa-css/src/value/gradient/radial.ts
  packages/alfa-css/src/value/position.ts
  packages/alfa-css/test/value/gradient/radial.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-style/src/property/background-image.ts
  packages/alfa-style/src/property/background-position-x.ts
  packages/alfa-style/src/property/background-position-y.ts
  packages/alfa-style/src/property/border-image-source.ts
  packages/alfa-style/src/resolver.ts
Labels: minor

#763 Implement remaining `display` grammar
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/src/node.ts
  packages/alfa-rules/src/common/predicate/is-rendered.ts
  packages/alfa-style/src/property/display.ts
  packages/alfa-style/test/property/display.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: major

#770 Add basic tests for R11
  packages/alfa-rules/test/sia-r11/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#772 Remove second expectation from R62
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/test/sia-r62/rule.spec.tsx
Labels: major

#773 Implement pseudo classes equality
  packages/alfa-css/src/syntax/nth.ts
  packages/alfa-selector/src/selector.ts
Labels: minor

#778 Name computation: skip step 1 when descending
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/test/name.spec.tsx
Labels: patch

#779 SIA R62: accept different font weight
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/test/sia-r62/rule.spec.tsx
Labels: patch
