Repository Siteimprove/alfa, pull requests merged in 2021-05, with the labels that each got.

#786 Extended diagnostic for R14
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-rules/test/sia-r14/rule.spec.tsx
  packages/alfa-rules/test/sia-r42/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: major

#788 Fix background size
  packages/alfa-style/src/property/background-size.ts
  packages/alfa-style/src/property/background.ts
  packages/alfa-style/test/property/background-size.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: major

#789 Assume no background on size
  packages/alfa-rules/src/common/expectation/get-colors.ts
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
Labels: patch

#791 SIA R17: add test
  packages/alfa-rules/test/sia-r17/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: internal

#793 SIA R4: Add test
  packages/alfa-rules/test/sia-r4/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: internal

#792 SIA R3: add test
  packages/alfa-rules/test/sia-r3/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: internal

#795 SIA R6: Added test
  packages/alfa-rules/test/sia-r6/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: internal

#794 SIA R5: add test
  packages/alfa-rules/test/sia-r5/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: internal

#800 SIA R12: Add Test
  packages/alfa-rules/test/sia-r12/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: internal

#805 Hasrole: use accessible node
  packages/alfa-rules/src/common/predicate/has-role.ts
  packages/alfa-rules/src/sia-r10/rule.ts
  packages/alfa-rules/src/sia-r11/rule.ts
  packages/alfa-rules/src/sia-r12/rule.ts
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/src/sia-r18/rule.ts
  packages/alfa-rules/src/sia-r2/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r42/rule.ts
  packages/alfa-rules/src/sia-r45/rule.ts
  packages/alfa-rules/src/sia-r46/rule.ts
  packages/alfa-rules/src/sia-r53/rule.ts
  packages/alfa-rules/src/sia-r57/rule.ts
  packages/alfa-rules/src/sia-r59/rule.ts
  packages/alfa-rules/src/sia-r61/rule.ts
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/src/sia-r64/rule.ts
  packages/alfa-rules/src/sia-r66/rule.ts
  packages/alfa-rules/src/sia-r68/rule.ts
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/src/sia-r71/rule.ts
  packages/alfa-rules/src/sia-r72/rule.ts
  packages/alfa-rules/src/sia-r73/rule.ts
  packages/alfa-rules/src/sia-r74/rule.ts
  packages/alfa-rules/src/sia-r8/rule.ts
  packages/alfa-rules/src/sia-r80/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/src/sia-r82/rule.ts
  packages/alfa-rules/src/sia-r85/rule.ts
  packages/alfa-rules/src/sia-r87/rule.ts
  packages/alfa-rules/src/sia-r90/rule.ts
  packages/alfa-rules/src/sia-r94/rule.ts
  packages/alfa-rules/test/common/predicate/has-role.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: major

#807 SIA-R19: Add test
  packages/alfa-rules/test/sia-r19/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: internal

#806 SIA-R8: Added tests
  packages/alfa-rules/test/sia-r8/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: internal

#804 R16 extended diagnostic
  packages/alfa-aria/src/role.ts
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/test/sia-r16/rule.spec.tsx
Labels: major

#801 R62 extended diagnostic
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/test/sia-r62/rule.spec.tsx
Labels: major

#817 Support text-decoration-thickness
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-style/src/index.ts
  packages/alfa-style/src/property/text-decoration-thickness.ts
  packages/alfa-style/src/property/text-decoration.ts
  packages/alfa-style/test/property/text-decoration.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#766 Remove unused `@siteimprove/alfa-json-ld` APIs
  packages/alfa-json-ld/package.json
  packages/alfa-json-ld/src/expand.ts
  packages/alfa-json-ld/src/guards.ts
  packages/alfa-json-ld/src/index.ts
  packages/alfa-json-ld/src/json-ld.ts
  packages/alfa-json-ld/src/types.ts
  packages/alfa-json-ld/test/expand.spec.ts
  packages/alfa-json-ld/test/helpers/person.ts
  packages/alfa-json-ld/tsconfig.json
  packages/alfa-scraper/src/awaiter.ts
  packages/alfa-scraper/src/scraper.ts
  yarn.lock
Labels: major

#764 Remove `syntax()` from `@siteimprove/alfa-highlight`
  packages/alfa-highlight/package.json
  packages/alfa-highlight/src/index.ts
  packages/alfa-highlight/src/syntax.ts
  packages/alfa-highlight/tsconfig.json
  packages/alfa-highlight/types/emphasize.d.ts
  yarn.lock
Labels: major

#765 Adjust `Graph` and `Network` types
  packages/alfa-graph/src/graph.ts
  packages/alfa-graph/test/graph.spec.ts
  packages/alfa-network/src/network.ts
  packages/alfa-network/test/network.spec.ts
Labels: major

#818 Trying to increase Nodejs heap size
  .github/workflows/integrate.yml
Labels: internal
