Repository Siteimprove/alfa, pull requests merged in 2021-01, with the labels that each got.

#637 Keep source of explicit `initial` properties
  packages/alfa-style/src/style.ts
  packages/alfa-style/test/style.spec.tsx
Labels: patch

#640 Add `--cpu-profile` and `--heap-profile` flags to `alfa audit` command
  packages/alfa-cli/bin/alfa/command/audit/flags.ts
  packages/alfa-cli/bin/alfa/command/audit/run.ts
  packages/alfa-cli/bin/alfa/profiler.ts
  packages/alfa-cli/tsconfig.json
Labels: minor

#644 Make `#toJSON()` parametric for all container types
  packages/alfa-act/src/outcome.ts
  packages/alfa-array/src/array.ts
  packages/alfa-branched/src/branched.ts
  packages/alfa-collection/src/collection.ts
  packages/alfa-either/src/either.ts
  packages/alfa-either/src/left.ts
  packages/alfa-either/src/right.ts
  packages/alfa-iterable/src/iterable.ts
  packages/alfa-json/src/serializable.ts
  packages/alfa-lazy/src/lazy.ts
  packages/alfa-list/src/list.ts
  packages/alfa-map/src/map.ts
  packages/alfa-option/src/option.ts
  packages/alfa-option/src/some.ts
  packages/alfa-record/src/record.ts
  packages/alfa-result/src/err.ts
  packages/alfa-result/src/ok.ts
  packages/alfa-result/src/result.ts
  packages/alfa-sequence/src/cons.ts
  packages/alfa-sequence/src/nil.ts
  packages/alfa-sequence/src/sequence.ts
  packages/alfa-set/src/set.ts
  packages/alfa-slice/src/slice.ts
  packages/alfa-table/src/table.ts
Labels: major

#648 Make SIA-R14 assume that non-essential text is imperceivable
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-rules/test/sia-r14/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#650 Fix parsing of <position> CSS values
  packages/alfa-css/src/value/position.ts
  packages/alfa-css/test/value/position.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-style/src/property/background.ts
Labels: major

#643 Add @siteimprove/alfa-performance package
  packages/alfa-performance/package.json
  packages/alfa-performance/src/index.ts
  packages/alfa-performance/src/now.ts
  packages/alfa-performance/src/performance.ts
  packages/alfa-performance/tsconfig.json
  packages/tsconfig.json
Labels: minor

#653 Make content document of non-rendered elements also not rendered
  packages/alfa-rules/src/common/predicate/is-rendered.ts
Labels: patch

#654 Implement SIA-R95
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r95/rule.ts
  packages/alfa-rules/test/sia-r95/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#656 Allow measuring performance events in `Audit#evaluate()`
  packages/alfa-act/package.json
  packages/alfa-act/src/audit.ts
  packages/alfa-act/tsconfig.json
Labels: minor

#662 Assume that `<audio>` elements have audio in SIA-R48 and SIA-R49
  packages/alfa-rules/src/sia-r48/rule.ts
  packages/alfa-rules/src/sia-r49/rule.ts
Labels: patch

#616 Account for additional techniques for hiding content in `isVisible()`
  packages/alfa-rules/src/common/predicate/is-clipped.ts
  packages/alfa-rules/src/common/predicate/is-offscreen.ts
  packages/alfa-rules/src/common/predicate/is-replaced.ts
  packages/alfa-rules/src/common/predicate/is-transparent.ts
  packages/alfa-rules/src/common/predicate/is-visible.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#667 Make `Value.JSON` optionally parametric
  packages/alfa-css/src/value.ts
  packages/alfa-css/src/value/angle.ts
  packages/alfa-css/src/value/color/hex.ts
  packages/alfa-css/src/value/color/hsl.ts
  packages/alfa-css/src/value/color/named.ts
  packages/alfa-css/src/value/color/rgb.ts
  packages/alfa-css/src/value/dimension.ts
  packages/alfa-css/src/value/gradient/linear.ts
  packages/alfa-css/src/value/image.ts
  packages/alfa-css/src/value/integer.ts
  packages/alfa-css/src/value/keyword.ts
  packages/alfa-css/src/value/length.ts
  packages/alfa-css/src/value/number.ts
  packages/alfa-css/src/value/numeric.ts
  packages/alfa-css/src/value/percentage.ts
  packages/alfa-css/src/value/position.ts
  packages/alfa-css/src/value/shadow.ts
  packages/alfa-css/src/value/string.ts
  packages/alfa-css/src/value/transform/matrix.ts
  packages/alfa-css/src/value/transform/perspective.ts
  packages/alfa-css/src/value/transform/rotate.ts
  packages/alfa-css/src/value/transform/scale.ts
  packages/alfa-css/src/value/transform/skew.ts
  packages/alfa-css/src/value/transform/translate.ts
  packages/alfa-css/src/value/url.ts
  packages/alfa-style/src/property/value/list.ts
Labels: minor

#428 Introduce `@siteimprove/alfa-protractor` package
  packages/alfa-protractor/package.json
  packages/alfa-protractor/src/index.ts
  packages/alfa-protractor/src/protractor.ts
  packages/alfa-protractor/tsconfig.json
  packages/tsconfig.json
  yarn.lock
Labels: minor
