Repository Siteimprove/alfa, pull requests merged in 2021-06, with the labels that each got.

#819 SIA R65: accept different border as focus indicator
  packages/alfa-rules/src/common/predicate/has-border.ts
  packages/alfa-rules/src/sia-r65/rule.ts
  packages/alfa-rules/test/sia-r65/rule.spec.tsx
Labels: patch

#821 Support `font-variant` CSS property
  packages/alfa-style/src/index.ts
  packages/alfa-style/src/property/font-variant-caps.ts
  packages/alfa-style/src/property/font-variant-east-asian.ts
  packages/alfa-style/src/property/font-variant-ligatures.ts
  packages/alfa-style/src/property/font-variant-numeric.ts
  packages/alfa-style/src/property/font-variant-position.ts
  packages/alfa-style/src/property/font-variant.ts
  packages/alfa-style/src/property/font.ts
  packages/alfa-style/test/property/font-variant.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#829 Implement SIA R56
  packages/alfa-rules/src/common/group.ts
  packages/alfa-rules/src/common/normalize.ts
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r56/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/test/sia-r56/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#831 Accessible name: reject whitespace descendants
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/test/name.spec.tsx
Labels: patch

#827 Consider element with `height` or `width` of 0 as invisible unless the text overflows
  packages/alfa-rules/src/common/predicate/is-clipped.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
Labels: patch

#835 Implement SIA-R55
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r56/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/test/sia-r55/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#836 SIA R55: clean up unused imports
  packages/alfa-rules/src/sia-r55/rule.ts
Labels: internal

#838 Pass roles as part of diagnostics in SIA-R55 and SIA-R56
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r56/rule.ts
Labels: minor

#840 Add `archive` option in `Scraper#scrape()`
  packages/alfa-cli/bin/alfa/command/scrape/flags.ts
  packages/alfa-cli/bin/alfa/command/scrape/run.ts
  packages/alfa-scraper/src/archive.ts
  packages/alfa-scraper/src/index.ts
  packages/alfa-scraper/src/scraper.ts
  packages/alfa-scraper/tsconfig.json
Labels: minor
