Repository Siteimprove/alfa, pull requests merged in 2021-02, with the labels that each got.

#678 Limit SIA-R40 to explicit `region` roles
  packages/alfa-rules/src/sia-r40/rule.ts
Labels: patch

#591 Implement the `Shape` CSS value type
  packages/alfa-array/src/array.ts
  packages/alfa-css/src/value/keyword.ts
  packages/alfa-css/src/value/shape.ts
  packages/alfa-css/src/value/shape/circle.ts
  packages/alfa-css/src/value/shape/ellipse.ts
  packages/alfa-css/src/value/shape/inset.ts
  packages/alfa-css/src/value/shape/polygon.ts
  packages/alfa-css/src/value/shape/radius.ts
  packages/alfa-css/src/value/shape/rectangle.ts
  packages/alfa-css/test/value/shape/circle.spec.ts
  packages/alfa-css/test/value/shape/ellipse.spec.ts
  packages/alfa-css/test/value/shape/inset.spec.ts
  packages/alfa-css/test/value/shape/polygon.spec.ts
  packages/alfa-css/test/value/shape/rectangle.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-parser/src/parser.ts
Labels: minor

#573 Implement CSS clip and clip-path properties
  packages/alfa-css/src/index.ts
  packages/alfa-css/src/value/box.ts
  packages/alfa-css/src/value/shape.ts
  packages/alfa-css/test/value/shape.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/background.ts
  packages/alfa-style/src/property/clip-path.ts
  packages/alfa-style/src/property/clip.ts
  packages/alfa-style/test/property/clip.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#688 Treat content clipped by masking as invisible
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/is-clipped.ts
  packages/alfa-rules/src/common/predicate/is-visible.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
  packages/alfa-style/src/property/position.ts
Labels: patch

#693 Support `font` shorthand property
  packages/alfa-css/src/value/percentage.ts
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/property/box-insets.ts
  packages/alfa-style/src/property/font.ts
  packages/alfa-style/test/property/font.spec.tsx
Labels: minor

#695 Rework @siteimprove/alfa-trilean package
  packages/alfa-act/src/outcome.ts
  packages/alfa-rules/src/common/expectation/is-passed.ts
  packages/alfa-rules/src/sia-r27/rule.ts
  packages/alfa-rules/src/sia-r30/rule.ts
  packages/alfa-rules/src/sia-r35/rule.ts
  packages/alfa-rules/src/sia-r37/rule.ts
  packages/alfa-rules/src/sia-r38/rule.ts
  packages/alfa-rules/src/sia-r50/rule.ts
  packages/alfa-rules/tsconfig.json
  packages/alfa-trilean/package.json
  packages/alfa-trilean/src/index.ts
  packages/alfa-trilean/src/iterable.ts
  packages/alfa-trilean/src/predicate.ts
  packages/alfa-trilean/src/trilean.ts
  packages/alfa-trilean/test/iterable.spec.tsx
  packages/alfa-trilean/test/predicate.spec.tsx
  packages/alfa-trilean/test/trilean.spec.ts
  packages/alfa-trilean/tsconfig.json
Labels: major

#696 Add @siteimprove/alfa-network package
  packages/alfa-network/package.json
  packages/alfa-network/src/index.ts
  packages/alfa-network/src/network.ts
  packages/alfa-network/test/network.spec.ts
  packages/alfa-network/tsconfig.json
  packages/tsconfig.json
Labels: minor

#702 Add @siteimprove/alfa-selective package
  packages/alfa-selective/package.json
  packages/alfa-selective/src/index.ts
  packages/alfa-selective/src/selective.ts
  packages/alfa-selective/test/selective.spec.ts
  packages/alfa-selective/tsconfig.json
  packages/tsconfig.json
Labels: minor

#267 Switch to native Node.js source map support
  .github/workflows/integrate.yml
  package.json
  packages/alfa-test/package.json
  packages/alfa-test/src/format.ts
  packages/alfa-test/src/index.ts
  packages/alfa-test/src/stack.ts
  packages/alfa-test/tsconfig.json
  scripts/common/tester.js
  yarn.lock
Labels: internal

#258 Upgrade to Yarn Berry
  .github/workflows/integrate.yml
  .github/workflows/release.yml
  .github/workflows/scan.yml
  .gitignore
  .yarn/.gitignore
  .yarn/releases/yarn-2.4.0.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: internal

#675 SIA R7 ignore invisible text and fully overwritten attributes
  packages/alfa-rules/src/sia-r7/rule.ts
  packages/alfa-rules/test/sia-r7/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#676 Implement cannot-be-a-base-url flag
  CHANGELOG.md
  packages/alfa-rules/test/common/evaluate.ts
  packages/alfa-url/src/url.ts
  packages/alfa-url/test/url.spec.ts
Labels: minor

#713 Accept color difference as a valid focus indicator in SIA-R65
  CHANGELOG.md
  packages/alfa-rules/src/sia-r65/rule.ts
  packages/alfa-rules/test/sia-r65/rule.spec.tsx
Labels: patch

#714 Accept background color difference as a valid focus indicator in SIA-R65
  CHANGELOG.md
  packages/alfa-rules/src/sia-r65/rule.ts
  packages/alfa-rules/test/sia-r65/rule.spec.tsx
Labels: patch

#715 Accept box shadow as a valid focus indicator in SIA-R65
  CHANGELOG.md
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/has-box-shadow.ts
  packages/alfa-rules/src/sia-r65/rule.ts
  packages/alfa-rules/test/sia-r65/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#716 <a> name - subtree priority over `title`
  CHANGELOG.md
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/test/name.spec.tsx
Labels: patch

#699 Rework audit interviewers for CLI
  CHANGELOG.md
  packages/alfa-act/src/audit.ts
  packages/alfa-act/src/interview.ts
  packages/alfa-act/src/oracle.ts
  packages/alfa-act/src/question.ts
  packages/alfa-act/src/rule.ts
  packages/alfa-cli/bin/alfa/command/audit/flags.ts
  packages/alfa-cli/bin/alfa/command/audit/run.ts
  packages/alfa-cli/bin/alfa/oracle.ts
  packages/alfa-cli/package.json
  packages/alfa-cli/tsconfig.json
  packages/alfa-interviewer/package.json
  packages/alfa-interviewer/src/index.ts
  packages/alfa-interviewer/src/interviewer.ts
  packages/alfa-interviewer/tsconfig.json
  packages/alfa-rules/src/common/expectation/media-text-alternative.ts
  packages/alfa-rules/src/common/question.ts
  packages/alfa-rules/test/common/evaluate.ts
  packages/alfa-rules/test/common/oracle.ts
  packages/tsconfig.json
  yarn.lock
Labels: major

#722 Rework media query and handle media ranges
  CHANGELOG.md
  README.md
  packages/alfa-css/src/syntax/component.ts
  packages/alfa-css/src/value/angle.ts
  packages/alfa-css/src/value/dimension.ts
  packages/alfa-css/src/value/length.ts
  packages/alfa-css/src/value/numeric.ts
  packages/alfa-media/src/index.ts
  packages/alfa-media/src/media.ts
  packages/alfa-media/test/media.spec.ts
  packages/alfa-media/tsconfig.json
  packages/alfa-rules/src/sia-r44/rule.ts
  packages/alfa-slice/src/slice.ts
Labels: major

#725 Accept spaces around CSS variable names in `var()` functions
  CHANGELOG.md
  packages/alfa-style/src/style.ts
  packages/alfa-style/test/style.spec.tsx
Labels: patch
