Repository Siteimprove/alfa, pull requests merged in 2022-05, with the labels that each got.

#1134 SIA-ER62: `background-image` should ignore transparent link element
  packages/alfa-rules/src/sia-er62/rule.ts
  packages/alfa-rules/test/sia-er62/rule.expectation.spec.tsx
Labels: patch

#1135 Change :focus-visible to match :focus elements
  docs/review/api/alfa-selector.api.md
  packages/alfa-rules/test/sia-r65/rule.spec.tsx
  packages/alfa-selector/src/selector.ts
Labels: minor

#1136 Update dependencies
  package.json
  packages/alfa-unexpected/package.json
  yarn.lock
Labels: dependencies

#1147 ER62: fixes some corner cases with nested paragraphs
  packages/alfa-rules/src/sia-er62/rule.ts
  packages/alfa-rules/test/sia-er62/rule.applicability.spec.tsx
Labels: patch

#1130 `getColors`: ignore interposed elements which have a fully transparent background
  docs/review/api/alfa-style.api.md
  packages/alfa-rules/src/common/dom/get-colors.ts
  packages/alfa-rules/test/common/dom/get-colors.spec.tsx
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
  packages/alfa-style/src/element/element.ts
  packages/alfa-style/src/element/predicate/has-transparent-background.ts
  packages/alfa-style/src/style.ts
  packages/alfa-style/test/node/predicate/has-transparent-background.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: minor

#1151 Do not expose elements with a non-rendered ancestor, even if referenced by `aria-owns`
  packages/alfa-aria/src/node.ts
  packages/alfa-aria/test/node.spec.tsx
  packages/alfa-style/src/node/predicate/is-rendered.ts
Labels: patch
