Repository Siteimprove/alfa, pull requests merged in 2022-03, with the labels that each got.

#1095 `isClipped`: recurse to offset parent and fix masking comparison
  packages/alfa-rules/src/common/predicate/is-clipped.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
Labels: patch

#1098 Add diagnostics in `cantTell` outcomes
  docs/review/api/alfa-act.api.md
  packages/alfa-act/package.json
  packages/alfa-act/src/diagnostic.ts
  packages/alfa-act/src/interview.ts
  packages/alfa-act/src/outcome.ts
  packages/alfa-act/src/question.ts
  packages/alfa-act/src/rule.ts
  packages/alfa-act/tsconfig.json
  packages/alfa-rules/src/common/dom/get-colors.ts
  packages/alfa-rules/test/common/outcome.ts
  packages/alfa-rules/test/sia-r66/rule.spec.tsx
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
  yarn.lock
Labels: minor

#1099 Simplify expectation helper
  packages/alfa-rules/src/common/act/expectation.ts
Labels: internal

#1100 Use windows-2019 as integrate target
  .github/workflows/integrate.yml
Labels: actions

#1087 SIA-R18: Accepts attributes allowed by ARIA in HTML
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/has-display-size.ts
  packages/alfa-rules/src/sia-r18/rule.ts
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r18/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#1097 isProgrammaticallyHidden: removes `hidden` attribute condition
  packages/alfa-rules/src/common/predicate/is-programmatically-hidden.ts
  packages/alfa-rules/test/sia-r21/rule.spec.tsx
Labels: internal

#1108 SIA-R55, SIA-R56: Ignore `form` and `section` with no name
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/has-incorrect-role-without-name.ts
  packages/alfa-rules/src/sia-r40/rule.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r56/rule.ts
  packages/alfa-rules/test/sia-r55/rule.spec.tsx
  packages/alfa-rules/test/sia-r56/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#1110 Pre-parse media and import rules when building style tree
  docs/review/api/alfa-dom.api.md
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-dom/package.json
  packages/alfa-dom/src/style/rule/import.ts
  packages/alfa-dom/src/style/rule/media.ts
  packages/alfa-rules/src/sia-r44/rule.ts
  yarn.lock
Labels: internal

#1073 Typescript version
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-rules.api.md
  package.json
  packages/alfa-act/src/interview.ts
  packages/alfa-rules/src/common/act/expectation.ts
  packages/alfa-rules/src/common/act/question.ts
  packages/alfa-rules/src/sia-er87/rule.ts
  packages/alfa-rules/src/sia-r82/rule.ts
  packages/alfa-rules/src/sia-r87/rule.ts
  packages/alfa-rules/test/sia-r82/rule.spec.tsx
  yarn.lock
Labels: minor

#1109 SIA-R11: applies to role inheriting from `link`
  packages/alfa-rules/src/sia-r11/rule.ts
  packages/alfa-rules/test/sia-r11/rule.spec.tsx
Labels: patch

#1114 Export type predicates for diagnostics
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/diagnostic.ts
  packages/alfa-rules/src/common/diagnostic/contrast.ts
  packages/alfa-rules/src/common/dom/get-colors.ts
  packages/alfa-rules/src/index.ts
  packages/alfa-rules/src/sia-er62/diagnostics.ts
  packages/alfa-rules/src/sia-r109/rule.ts
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r56/rule.ts
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/src/sia-r70/rule.ts
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/tsconfig.json
Labels: minor

#1115 Allow rules to ask optional questions by providing default answer
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-act/src/interview.ts
  packages/alfa-act/src/question.ts
  packages/alfa-rules/src/common/act/question.ts
  packages/alfa-rules/src/sia-er65/rule.ts
  packages/alfa-rules/test/common/oracle.ts
  packages/alfa-rules/test/sia-er65/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: major

#1117 Remove `alfa-protractor`
  config/package-dependency-graph.ts
  docs/api/alfa-protractor.md
  docs/api/alfa-protractor.protractor_namespace.md
  docs/api/alfa-protractor.protractor_namespace.topage_1_function.md
  docs/api/alfa-protractor.protractor_namespace.type_typealias.md
  docs/dependency-graph.dot
  docs/dependency-graph.png
  docs/review/api/alfa-protractor.api.md
  packages/alfa-protractor/config/api.json
  packages/alfa-protractor/package.json
  packages/alfa-protractor/src/index.ts
  packages/alfa-protractor/src/protractor.ts
  packages/alfa-protractor/tsconfig.json
  packages/tsconfig.json
  yarn.lock
Labels: major

#1116 SIA-R83: Accept font relative media queries as handling overflow
  docs/review/api/alfa-cascade.api.md
  docs/review/api/alfa-dom.api.md
  docs/review/api/alfa-media.api.md
  packages/alfa-cascade/src/index.ts
  packages/alfa-cascade/src/rule-tree.ts
  packages/alfa-dom/src/style/rule.ts
  packages/alfa-media/src/media.ts
  packages/alfa-rules/package.json
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
  yarn.lock
Labels: minor
