Repository Siteimprove/alfa, pull requests merged in 2022-02, with the labels that each got.

#1031 SIA-ER62: Only apply to links that have different foreground from their container
  packages/alfa-rules/src/common/expectation/get-colors.ts
  packages/alfa-rules/src/sia-er62/diagnostics.ts
  packages/alfa-rules/src/sia-er62/rule.ts
  packages/alfa-rules/test/sia-er62/rule.spec.tsx
Labels: minor

#1041 `isRendered`: Consider fallback content (descendant of media elements) as not rendered
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/is-fallback.ts
  packages/alfa-rules/src/common/predicate/is-rendered.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#1057 Update some dependencies
  package.json
  packages/alfa-webdriver/package.json
  yarn.lock
Labels: dependencies

#1051 Pre-parse media queries in style tree
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/package.json
  packages/alfa-dom/src/style/rule/media.ts
  packages/alfa-dom/tsconfig.json
  packages/alfa-rules/src/sia-r44/rule.ts
  yarn.lock
Labels: minor

#1056 Separate message from diagnostic in questions
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-act/src/question.ts
  packages/alfa-assert/test/fixture/rule.ts
  packages/alfa-rules/src/common/act/question.ts
  packages/alfa-rules/src/common/expectation/media-text-alternative.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r23/rule.ts
  packages/alfa-rules/src/sia-r24/rule.ts
  packages/alfa-rules/src/sia-r25/rule.ts
  packages/alfa-rules/src/sia-r33/rule.ts
  packages/alfa-rules/src/sia-r39/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r48/rule.ts
  packages/alfa-rules/src/sia-r49/rule.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
Labels: major

#1053 SIA-ER62: Tell in diagnostics all distinguishable properties
  packages/alfa-rules/src/sia-er62/diagnostics.ts
  packages/alfa-rules/src/sia-er62/rule.ts
  packages/alfa-rules/test/sia-er62/common.ts
  packages/alfa-rules/test/sia-er62/rule.applicability.spec.tsx
  packages/alfa-rules/test/sia-er62/rule.expectation.contrast.spec.tsx
  packages/alfa-rules/test/sia-er62/rule.expectation.spec.tsx
  packages/alfa-rules/test/sia-er62/rule.expectation.textdecoration.spec.tsx
  packages/alfa-rules/test/sia-er62/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#1075 Expose DOM's nodes type
  docs/review/api/alfa-dom.api.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/src/node/attribute.ts
  packages/alfa-dom/src/node/comment.ts
  packages/alfa-dom/src/node/document.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/fragment.ts
  packages/alfa-dom/src/node/shadow.ts
  packages/alfa-dom/src/node/text.ts
  packages/alfa-dom/src/node/type.ts
Labels: minor

#1067 Parsing TabIndex as HTML specification
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/test/node/element.spec.tsx
Labels: bug

#1078 SIA-ER62: Distinguish between link and container color name in diagnostics
  packages/alfa-rules/src/common/diagnostic/contrast.ts
  packages/alfa-rules/src/common/outcome/contrast.ts
  packages/alfa-rules/src/sia-er62/diagnostics.ts
  packages/alfa-rules/src/sia-er62/rule.ts
  packages/alfa-rules/src/sia-r66/rule.ts
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/test/sia-er62/common.ts
  packages/alfa-rules/test/sia-er62/rule.applicability.spec.tsx
  packages/alfa-rules/test/sia-er62/rule.expectation.contrast.spec.tsx
  packages/alfa-rules/test/sia-er62/rule.expectation.spec.tsx
  packages/alfa-rules/test/sia-er62/rule.expectation.textdecoration.spec.tsx
  packages/alfa-rules/test/sia-r66/rule.spec.tsx
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
Labels: minor

#1084 Media: queries `0` are accepted as `0px`
  docs/review/api/alfa-media.api.md
  packages/alfa-media/src/media.ts
  packages/alfa-media/test/media.spec.ts
Labels: minor

#1068 SIA-R23, SIA-R24, SIA-R33: ask only for transcript link
  packages/alfa-rules/src/common/expectation/media-transcript.ts
  packages/alfa-rules/src/sia-r23/rule.ts
  packages/alfa-rules/src/sia-r24/rule.ts
  packages/alfa-rules/src/sia-r33/rule.ts
  packages/alfa-rules/test/sia-r23/rule.spec.tsx
  packages/alfa-rules/test/sia-r24/rule.spec.tsx
  packages/alfa-rules/test/sia-r33/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#1086 Improve performance management in `alfa-act`.
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-assert.api.md
  docs/review/api/alfa-performance.api.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-act/src/audit.ts
  packages/alfa-act/src/rule.ts
  packages/alfa-assert/package.json
  packages/alfa-assert/src/assertion.ts
  packages/alfa-assert/tsconfig.json
  packages/alfa-performance/src/performance.ts
  packages/alfa-rules/src/index.ts
  yarn.lock
Labels: minor
