Repository Siteimprove/alfa, pull requests merged in 2022-07, with the labels that each got.

#1178 Rename `IsPerceivable`, and introduce `isIncludedInTheAccessibilityTree`
  docs/review/api/alfa-aria.api.md
  packages/alfa-aria/src/dom/dom.ts
  packages/alfa-aria/src/dom/predicate/is-included-accessibility-tree.ts
  packages/alfa-aria/src/dom/predicate/is-perceivable.ts
  packages/alfa-aria/src/index.ts
  packages/alfa-aria/tsconfig.json
  packages/alfa-rules/src/common/applicability/audio.ts
  packages/alfa-rules/src/common/expectation/media-text-alternative.ts
  packages/alfa-rules/src/common/expectation/media-transcript.ts
  packages/alfa-rules/src/common/predicate/is-at-the-start.ts
  packages/alfa-rules/src/sia-r10/rule.ts
  packages/alfa-rules/src/sia-r11/rule.ts
  packages/alfa-rules/src/sia-r12/rule.ts
  packages/alfa-rules/src/sia-r13/rule.ts
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/src/sia-r18/rule.ts
  packages/alfa-rules/src/sia-r2/rule.ts
  packages/alfa-rules/src/sia-r28/rule.ts
  packages/alfa-rules/src/sia-r39/rule.ts
  packages/alfa-rules/src/sia-r40/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r42/rule.ts
  packages/alfa-rules/src/sia-r43/rule.ts
  packages/alfa-rules/src/sia-r45/rule.ts
  packages/alfa-rules/src/sia-r46/rule.ts
  packages/alfa-rules/src/sia-r49/rule.ts
  packages/alfa-rules/src/sia-r53/rule.ts
  packages/alfa-rules/src/sia-r54/rule.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r56/rule.ts
  packages/alfa-rules/src/sia-r57/rule.ts
  packages/alfa-rules/src/sia-r60/rule.ts
  packages/alfa-rules/src/sia-r61/rule.ts
  packages/alfa-rules/src/sia-r63/rule.ts
  packages/alfa-rules/src/sia-r64/rule.ts
  packages/alfa-rules/src/sia-r66/rule.ts
  packages/alfa-rules/src/sia-r68/rule.ts
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/src/sia-r7/rule.ts
  packages/alfa-rules/src/sia-r76/rule.ts
  packages/alfa-rules/src/sia-r77/rule.ts
  packages/alfa-rules/src/sia-r78/rule.ts
  packages/alfa-rules/src/sia-r8/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/src/sia-r82/rule.ts
  packages/alfa-rules/src/sia-r86/rule.ts
  packages/alfa-rules/src/sia-r94/rule.ts
Labels: major

#1179 SIA-R78: Only accept accessible content between accessible headings
  packages/alfa-rules/src/sia-r78/rule.ts
  packages/alfa-rules/test/sia-r78/rule.spec.tsx
Labels: patch

#1180 Replace SIA-R62 with SIA-ER62
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/diagnostic.ts
  packages/alfa-rules/src/deprecated.ts
  packages/alfa-rules/src/experimental.ts
  packages/alfa-rules/src/index.ts
  packages/alfa-rules/src/sia-dr62/rule.ts
  packages/alfa-rules/src/sia-dr62/serialise.ts
  packages/alfa-rules/src/sia-er62/rule.ts
  packages/alfa-rules/src/sia-r62/diagnostics.ts
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/src/sia-r62/serialise.ts
  packages/alfa-rules/src/tags/stability.ts
  packages/alfa-rules/test/sia-dr62/rule.spec.tsx
  packages/alfa-rules/test/sia-dr62/serialise.spec.ts
  packages/alfa-rules/test/sia-r62/common.ts
  packages/alfa-rules/test/sia-r62/rule.applicability.spec.tsx
  packages/alfa-rules/test/sia-r62/rule.expectation.contrast.spec.tsx
  packages/alfa-rules/test/sia-r62/rule.expectation.spec.tsx
  packages/alfa-rules/test/sia-r62/rule.expectation.textdecoration.spec.tsx
  packages/alfa-rules/test/sia-r62/serialise.spec.ts
  packages/alfa-rules/tsconfig.json
Labels: major

#1164 SIA-R65: Provide classes and number of matches in diagnostic
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/diagnostic.ts
  packages/alfa-rules/src/sia-er65/rule.ts
  packages/alfa-rules/src/sia-r65/diagnostics.ts
  packages/alfa-rules/src/sia-r65/rule.ts
  packages/alfa-rules/test/sia-er65/rule.spec.tsx
  packages/alfa-rules/test/sia-r65/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#1182 SIA-R66, SIA-R69: `getForeground` should resolve `currentcolor` automatically
  packages/alfa-rules/src/common/dom/get-colors.ts
  packages/alfa-rules/test/common/dom/get-colors.spec.tsx
Labels: patch

#1185 SIA-R16: only apply to explicit role
  docs/review/api/alfa-aria.api.md
  packages/alfa-aria/src/dom/dom.ts
  packages/alfa-aria/src/dom/predicate/has-non-default-role.ts
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/index.ts
  packages/alfa-aria/tsconfig.json
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/test/sia-r16/rule.spec.tsx
Labels: minor

#1188 Export previous heading in R53 diagnostic
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/diagnostic.ts
  packages/alfa-rules/src/sia-r53/rule.ts
  packages/alfa-rules/test/sia-r53/rule.spec.tsx
Labels: minor

#1189 Improve typing of `Array.sortWith`
  docs/review/api/alfa-array.api.md
  packages/alfa-array/src/array.ts
  packages/alfa-rules/src/sia-r62/diagnostics.ts
Labels: minor

#1194 Allow formatters to be synchronous
  docs/review/api/alfa-formatter.api.md
  packages/alfa-formatter-earl/package.json
  packages/alfa-formatter-earl/src/earl.ts
  packages/alfa-formatter-earl/tsconfig.json
  packages/alfa-formatter-json/src/json.ts
  packages/alfa-formatter-sarif/src/sarif.ts
  packages/alfa-formatter/package.json
  packages/alfa-formatter/src/formatter.ts
  packages/alfa-formatter/tsconfig.json
  yarn.lock
Labels: minor

#1191 R66/R69 should ignore elements that are used in name of disabled widgets
  docs/review/api/alfa-aria.api.md
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/test/name.spec.tsx
  packages/alfa-rules/src/sia-r66/rule.ts
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/test/sia-r66/rule.spec.tsx
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
Labels: patch

#1193 Include Accessible name testable statements
  packages/alfa-aria/package.json
  packages/alfa-aria/scripts/name-testable-statements.js
  packages/alfa-aria/scripts/roles.js
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/test/name-testable-statements.spec.tsx
  packages/alfa-aria/test/name.spec.tsx
  packages/alfa-aria/tsconfig.json
Labels: patch

#1196 SIA-R19: Accept negative integers and numbers
  packages/alfa-rules/src/sia-r19/rule.ts
  packages/alfa-rules/test/sia-r19/rule.spec.tsx
Labels: patch

#1197 Export a super-type for rules
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/index.ts
Labels: patch

#1195 Refactor `calc` expression and some resolver
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/index.ts
  packages/alfa-css/src/value/calculation.ts
  packages/alfa-css/src/value/color.ts
  packages/alfa-css/src/value/color/hex.ts
  packages/alfa-css/src/value/color/hsl.ts
  packages/alfa-css/src/value/color/named.ts
  packages/alfa-css/src/value/color/rgb.ts
  packages/alfa-css/src/value/gradient.ts
  packages/alfa-css/src/value/gradient/linear.ts
  packages/alfa-css/src/value/gradient/radial.ts
  packages/alfa-css/src/value/numeric.ts
  packages/alfa-css/src/value/numeric/angle.ts
  packages/alfa-css/src/value/numeric/dimension.ts
  packages/alfa-css/src/value/numeric/integer.ts
  packages/alfa-css/src/value/numeric/length.ts
  packages/alfa-css/src/value/numeric/number.ts
  packages/alfa-css/src/value/numeric/numeric.ts
  packages/alfa-css/src/value/numeric/percentage.ts
  packages/alfa-css/src/value/position.ts
  packages/alfa-css/src/value/shadow.ts
  packages/alfa-css/src/value/shape/inset.ts
  packages/alfa-css/src/value/shape/polygon.ts
  packages/alfa-css/src/value/shape/radius.ts
  packages/alfa-css/src/value/shape/rectangle.ts
  packages/alfa-css/src/value/transform.ts
  packages/alfa-css/src/value/transform/matrix.ts
  packages/alfa-css/src/value/transform/perspective.ts
  packages/alfa-css/src/value/transform/rotate.ts
  packages/alfa-css/src/value/transform/scale.ts
  packages/alfa-css/src/value/transform/skew.ts
  packages/alfa-css/src/value/transform/translate.ts
  packages/alfa-css/src/value/unit.ts
  packages/alfa-css/src/value/unit/converter.ts
  packages/alfa-css/src/value/unit/unit.ts
  packages/alfa-css/test/value/calculation.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-style/package.json
  packages/alfa-style/src/property/font-size.ts
  packages/alfa-style/src/resolver.ts
  packages/alfa-style/test/property/font-size.spec.tsx
  packages/alfa-style/tsconfig.json
  yarn.lock
Labels: minor

#1199 SIA-R53: Add getter for previous element in diagnostic
  packages/alfa-rules/src/sia-r53/rule.ts
Labels: patch

#1198 Keep subtype in collections with .sortWith
  docs/review/api/alfa-array.api.md
  docs/review/api/alfa-collection.api.md
  docs/review/api/alfa-iterable.api.md
  docs/review/api/alfa-list.api.md
  docs/review/api/alfa-sequence.api.md
  docs/review/api/alfa-slice.api.md
  packages/alfa-array/src/array.ts
  packages/alfa-collection/src/collection.ts
  packages/alfa-iterable/src/iterable.ts
  packages/alfa-list/src/list.ts
  packages/alfa-sequence/src/cons.ts
  packages/alfa-sequence/src/sequence.ts
  packages/alfa-slice/src/slice.ts
Labels: minor

#1204 Map `<select>` to `listbox` all the time
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/test/node.spec.tsx
  packages/alfa-rules/test/sia-r42/rule.spec.tsx
Labels: patch

#1200 Compute accessible name correctly from the content
  packages/alfa-aria/scripts/name-testable-statements.js
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/src/role/data.ts
  packages/alfa-aria/test/name-testable-statements.spec.tsx
  packages/alfa-aria/test/name.spec.tsx
Labels: patch
