Repository Siteimprove/alfa, pull requests merged in 2022-01, with the labels that each got.

#1013 Devtools improvements
  docs/review/api/alfa-assert.api.md
  packages/alfa-assert/src/assertion.ts
  packages/alfa-assert/test/asserter.spec.ts
  packages/alfa-assert/test/fixture/rule.ts
Labels: minor

#1019 Clean up a bit oracle building
  packages/alfa-rules/test/common/oracle.ts
Labels: internal

#1020 Map questions' uri to the expected answer type and register questions
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-act/src/audit.ts
  packages/alfa-act/src/interview.ts
  packages/alfa-act/src/oracle.ts
  packages/alfa-act/src/outcome.ts
  packages/alfa-act/src/question.ts
  packages/alfa-act/src/rule.ts
  packages/alfa-assert/test/asserter.spec.ts
  packages/alfa-assert/test/fixture/rule.ts
  packages/alfa-rules/src/common/applicability/audio.ts
  packages/alfa-rules/src/common/applicability/video.ts
  packages/alfa-rules/src/common/expectation/media-text-alternative.ts
  packages/alfa-rules/src/common/expectation/video-description-track-accurate.ts
  packages/alfa-rules/src/common/question.ts
  packages/alfa-rules/src/experimental.ts
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-er87/rule.ts
  packages/alfa-rules/src/sia-r109/rule.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r22/rule.ts
  packages/alfa-rules/src/sia-r23/rule.ts
  packages/alfa-rules/src/sia-r24/rule.ts
  packages/alfa-rules/src/sia-r25/rule.ts
  packages/alfa-rules/src/sia-r26/rule.ts
  packages/alfa-rules/src/sia-r27/rule.ts
  packages/alfa-rules/src/sia-r29/rule.ts
  packages/alfa-rules/src/sia-r30/rule.ts
  packages/alfa-rules/src/sia-r31/rule.ts
  packages/alfa-rules/src/sia-r32/rule.ts
  packages/alfa-rules/src/sia-r33/rule.ts
  packages/alfa-rules/src/sia-r34/rule.ts
  packages/alfa-rules/src/sia-r35/rule.ts
  packages/alfa-rules/src/sia-r36/rule.ts
  packages/alfa-rules/src/sia-r37/rule.ts
  packages/alfa-rules/src/sia-r38/rule.ts
  packages/alfa-rules/src/sia-r39/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r48/rule.ts
  packages/alfa-rules/src/sia-r49/rule.ts
  packages/alfa-rules/src/sia-r50/rule.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r65/rule.ts
  packages/alfa-rules/src/sia-r66/rule.ts
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/src/sia-r82/rule.ts
  packages/alfa-rules/src/sia-r87/rule.ts
  packages/alfa-rules/test/common/oracle.ts
  packages/alfa-rules/test/sia-r38/rule.spec.tsx
Labels: major

#1025 Serialise `path` in DOM Nodes JSON
  docs/review/api/alfa-dom.api.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-dom/src/h.ts
  packages/alfa-dom/src/jsx.ts
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/src/node/attribute.ts
  packages/alfa-dom/src/node/attribute/predicate/has-name.ts
  packages/alfa-dom/src/node/comment.ts
  packages/alfa-dom/src/node/document.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/element/predicate/has-name.ts
  packages/alfa-dom/src/node/element/predicate/is-suggested-focusable.ts
  packages/alfa-dom/src/node/fragment.ts
  packages/alfa-dom/src/node/text.ts
  packages/alfa-dom/src/node/type.ts
Labels: minor

#1027 Replace Questions' message by Diagnostic
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-act/src/question.ts
  packages/alfa-assert/test/fixture/rule.ts
  packages/alfa-rules/src/common/expectation/media-text-alternative.ts
  packages/alfa-rules/src/common/question.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r23/rule.ts
  packages/alfa-rules/src/sia-r24/rule.ts
  packages/alfa-rules/src/sia-r25/rule.ts
  packages/alfa-rules/src/sia-r33/rule.ts
  packages/alfa-rules/src/sia-r39/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r48/rule.ts
  packages/alfa-rules/src/sia-r49/rule.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
Labels: major

#1028 Update vulnerable dependencies
  package.json
  yarn.lock
Labels: internal

#1026 Add test in multimedia rules
  packages/alfa-rules/src/common/applicability/audio.ts
  packages/alfa-rules/src/common/applicability/video.ts
  packages/alfa-rules/src/common/expectation/media-text-alternative.ts
  packages/alfa-rules/test/sia-r22/rule.spec.tsx
  packages/alfa-rules/test/sia-r23/rule.spec.tsx
  packages/alfa-rules/test/sia-r25/rule.spec.tsx
  packages/alfa-rules/test/sia-r26/rule.spec.tsx
  packages/alfa-rules/test/sia-r27/rule.spec.tsx
  packages/alfa-rules/test/sia-r29/rule.spec.tsx
  packages/alfa-rules/test/sia-r30/rule.spec.tsx
  packages/alfa-rules/test/sia-r31/rule.spec.tsx
  packages/alfa-rules/test/sia-r32/rule.spec.tsx
  packages/alfa-rules/test/sia-r33/rule.spec.tsx
  packages/alfa-rules/test/sia-r34/rule.spec.tsx
  packages/alfa-rules/test/sia-r35/rule.spec.tsx
  packages/alfa-rules/test/sia-r36/rule.spec.tsx
  packages/alfa-rules/test/sia-r37/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: patch

#1032 SIA-ER62: Merge R62 into ER62
  packages/alfa-rules/src/sia-er62/diagnostics.ts
  packages/alfa-rules/src/sia-er62/rule.ts
  packages/alfa-rules/src/sia-er62/serialise.ts
  packages/alfa-rules/test/sia-er62/rule.spec.tsx
Labels: minor

#1040 SIA-R47: parses properties case insensitively
  packages/alfa-rules/src/sia-r47/rule.ts
  packages/alfa-rules/test/sia-r47/rule.spec.tsx
Labels: bug

#1045 Consider stretched elements as visible
  packages/alfa-rules/src/common/predicate/is-visible.ts
  packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
Labels: patch

#1047 Added version tag and marked ER62 and ER87 as version 2
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/index.ts
  packages/alfa-rules/src/sia-er62/rule.ts
  packages/alfa-rules/src/sia-er87/rule.ts
  packages/alfa-rules/src/tags/index.ts
  packages/alfa-rules/src/tags/stability.ts
  packages/alfa-rules/src/tags/version.ts
  packages/alfa-rules/tsconfig.json
Labels: minor

#1049 Update puppeteer
  packages/alfa-puppeteer/package.json
  packages/alfa-scraper/package.json
  yarn.lock
Labels: dependencies
