Repository Siteimprove/alfa, pull requests merged in 2023-02, with the labels that each got.

#1330 Improve exported rules types
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/index.ts
Labels: major

#1331 Fix typos in ADR documents
  docs/architecture/decisions/adr-002.md
  docs/architecture/decisions/adr-007.md
  docs/architecture/decisions/adr-008.md
  docs/architecture/decisions/adr-010.md
  docs/architecture/decisions/adr-011.md
  docs/architecture/decisions/adr-014.md
  docs/architecture/decisions/adr-015.md
Labels: documentation

#1335 Update rules mappings according to ACT rules
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/src/sia-r47/rule.ts
  packages/alfa-rules/src/sia-r95/rule.ts
Labels: internal

#1334 Compute line-height from percentage of font-size of self instead of from parent
  packages/alfa-style/src/property/line-height.ts
  packages/alfa-style/test/property/line-height.spec.tsx
Labels: patch

#1337 Add minimal status reporter with progress indicator
  .github/workflows/integrate.yml
  .github/workflows/release.yml
  .github/workflows/scan.yml
  scripts/build.js
  scripts/common/builder.js
  scripts/common/flags.js
  scripts/common/reporter.js
Labels: internal

#1344 Set up PR commands
  .github/workflows/pr-commands.yml
  .pr-commands/config.json
Labels: internal

#1339 SIA-R10: Accept `webauthn` token
  packages/alfa-rules/src/sia-r10/rule.ts
  packages/alfa-rules/test/sia-r10/rule.spec.tsx
Labels: patch

#1346 Add guide on writing a parser
  README.md
  docs/guides/README.md
  docs/guides/writing-a-parser.md
Labels: documentation

#1352 Parse `:host` pseudo-class selector
  docs/review/api/alfa-selector.api.md
  packages/alfa-selector/src/selector.ts
  packages/alfa-selector/test/selector.spec.tsx
Labels: minor

#1355 `hasIncorrectRoleWithoutName`: fix `<aside>` exception
  docs/review/api/alfa-dom.api.md
  packages/alfa-aria/src/dom/predicate/has-incorrect-role-without-name.ts
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/test/dom/predicate/has-incorrect-role-without-name.spec.tsx
  packages/alfa-aria/tsconfig.json
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/element/predicate.ts
  packages/alfa-dom/src/node/element/predicate/is-scoped-to.ts
  packages/alfa-dom/tsconfig.json
Labels: minor

#1354 Update whitespace parser to parse one or more
  docs/review/api/alfa-parser.api.md
  packages/alfa-css/src/syntax/token.ts
  packages/alfa-css/test/value/color/rgb.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-parser/src/parser.ts
Labels: patch

#1358 SIA-R16: Make `aria-controls` optional for role `combobox`
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/test/sia-r16/rule.spec.tsx
Labels: patch

#1357 alfa-dom: Use exports map
  packages/alfa-dom/package.json
Labels: major

#1359 SIA-R21: Remove unused import
  packages/alfa-rules/src/sia-r21/rule.ts
Labels: internal

#1361 Write debugging guide
  docs/guides/README.md
  docs/guides/debugging.md
Labels: documentation
