Repository Siteimprove/alfa, pull requests merged in 2023-09, with the labels that each got.

#1465 SIA-R54: ignore empty elements
  .changeset/eighty-years-design.md
  packages/alfa-rules/src/sia-r54/rule.ts
  packages/alfa-rules/test/sia-r54/rule.spec.tsx
Labels: patch

#1462 Improve changelog generation and format
  .changeset/config.json
  .changeset/tidy-starfishes-lie.md
  .github/workflows/alfa-release.yml
  .github/workflows/integrate.yml
  .gitignore
  CHANGELOG.md
  config/knip.ts
  config/package-dependency-graph.ts
  docs/dependency-graph.dot
  docs/dependency-graph.png
  docs/review/api/alfa-rectangle.api.md
  docs/review/api/alfa-toolchain.api.md
  package.json
  packages/alfa-rectangle/config/api-extractor.json
  packages/alfa-toolchain/CHANGELOG.md
  packages/alfa-toolchain/README.md
  packages/alfa-toolchain/config/api-extractor.json
  packages/alfa-toolchain/package.json
  packages/alfa-toolchain/src/changeset/build-changelog.ts
  packages/alfa-toolchain/src/changeset/changelog-global.ts
  packages/alfa-toolchain/src/changeset/changelog-individual.ts
  packages/alfa-toolchain/src/changeset/get-changeset-details.ts
  packages/alfa-toolchain/src/changeset/helpers.ts
  packages/alfa-toolchain/src/index.ts
  packages/alfa-toolchain/src/validation/validate-changesets.ts
  packages/alfa-toolchain/test/changeset/build-changelog.spec.tsx
  packages/alfa-toolchain/test/changeset/get-changeset-details.spec.tsx
  packages/alfa-toolchain/tsconfig.json
  packages/tsconfig.json
  scratches/tsconfig.json
  scripts/src/changelog.ts
  scripts/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: internal

#1464 Use layout to improve handling of interposed elements
  .changeset/calm-camels-sell.md
  .changeset/empty-ears-cheat.md
  .changeset/lovely-bees-type.md
  docs/review/api/alfa-selector.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-rules/src/common/expectation/contrast.ts
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
  packages/alfa-selector/src/context.ts
  packages/alfa-style/src/element/element.ts
  packages/alfa-style/src/element/helpers/get-bounding-box.ts
  packages/alfa-style/src/style.ts
  packages/alfa-style/tsconfig.json
Labels: minor

#1469 More structural validations of the project
  .changeset/odd-chefs-act.md
  .github/workflows/integrate.yml
  config/validate-structure.json
  docs/review/api/alfa-toolchain.api.md
  packages/alfa-aria/tsconfig.json
  packages/alfa-bits/tsconfig.json
  packages/alfa-dom/tsconfig.json
  packages/alfa-iana/tsconfig.json
  packages/alfa-option/tsconfig.json
  packages/alfa-rules/tsconfig.json
  packages/alfa-selector/tsconfig.json
  packages/alfa-style/tsconfig.json
  packages/alfa-toolchain/README.md
  packages/alfa-toolchain/package.json
  packages/alfa-toolchain/src/index.ts
  packages/alfa-toolchain/src/validation/has-extractor-config.ts
  packages/alfa-toolchain/src/validation/index.ts
  packages/alfa-toolchain/src/validation/validate-all.ts
  packages/alfa-toolchain/src/validation/validate-changesets.ts
  packages/alfa-toolchain/src/validation/validate-package-json.ts
  packages/alfa-toolchain/src/validation/validate-workspace-tsconfig.ts
  packages/alfa-toolchain/tsconfig.json
  packages/alfa-tuple/tsconfig.json
  yarn.lock
Labels: minor, Improvement

#1470 Name computation: Include shadow DOM in name from content
  .changeset/nine-yaks-grow.md
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/test/name.spec.tsx
Labels: patch

#1472 Use `buttonface` for UA `<button>` background color
  .changeset/stupid-lies-hang.md
  packages/alfa-cascade/src/user-agent.ts
  packages/alfa-rules/test/sia-dr66/rule.spec.tsx
  packages/alfa-rules/test/sia-dr69/rule.spec.tsx
  packages/alfa-rules/test/sia-r66/rule.spec.tsx
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
Labels: patch
