Repository Siteimprove/alfa, pull requests merged in 2023-05, with the labels that each got.

#1405 Typescript 5
  docs/review/api/alfa-aria.api.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-selector.api.md
  docs/review/api/alfa-style.api.md
  package.json
  packages/alfa-dom/src/h.ts
  packages/alfa-style/src/style.ts
  packages/alfa-tuple/src/tuple.ts
  yarn.lock
Labels: dependencies, internal

#1407 Add `withDocumentElement` helper for Applicability
  .changeset/wet-actors-search.md
  packages/alfa-rules/src/common/applicability/with-document-element.ts
  packages/alfa-rules/src/sia-er87/rule.ts
  packages/alfa-rules/src/sia-r1/rule.ts
  packages/alfa-rules/src/sia-r109/rule.ts
  packages/alfa-rules/src/sia-r59/rule.ts
  packages/alfa-rules/src/sia-r61/rule.ts
  packages/alfa-rules/src/sia-r70/rule.ts
  packages/alfa-rules/src/sia-r87/rule.ts
  packages/alfa-rules/tsconfig.json
Labels: internal

#1408 Remove useless void argument in hasUniqueId
  .changeset/cold-mugs-wave.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/node/element/predicate/has-unique-id.ts
  packages/alfa-rules/src/sia-r3/rule.ts
Labels: minor

#1406 Abstract Math calculation in style properties
  .changeset/gold-pens-shave.md
  .changeset/short-feet-drive.md
  .changeset/short-rings-drop.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/value/math-expression/math.ts
  packages/alfa-style/package.json
  packages/alfa-style/src/property/font-size.ts
  packages/alfa-style/src/property/line-height.ts
  packages/alfa-style/src/property/outline-offset.ts
  packages/alfa-style/src/property/outline-width.ts
  packages/alfa-style/src/property/value/compound.ts
  packages/alfa-style/src/resolver.ts
  packages/alfa-style/tsconfig.json
  yarn.lock
Labels: major

#1409 `hasTabIndex`: accepts number(s) and add tests
  .changeset/fifty-hats-protect.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/package.json
  packages/alfa-dom/src/node/element/predicate/has-tab-index.ts
  packages/alfa-dom/test/node/predicate/has-tab-index.spec.tsx
  packages/alfa-dom/tsconfig.json
  yarn.lock
Labels: minor

#1415 Clean up deprecated rules
  .changeset/quiet-lobsters-behave.md
  .changeset/sweet-days-reply.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/diagnostic.ts
  packages/alfa-rules/src/common/expectation/contrast.ts
  packages/alfa-rules/src/deprecated.ts
  packages/alfa-rules/src/experimental.ts
  packages/alfa-rules/src/sia-dr18/rule.ts
  packages/alfa-rules/src/sia-dr62/rule.ts
  packages/alfa-rules/src/sia-dr62/serialise.ts
  packages/alfa-rules/src/sia-dr66/rule.ts
  packages/alfa-rules/src/sia-dr69/rule.ts
  packages/alfa-rules/src/sia-dr91/rule.ts
  packages/alfa-rules/src/sia-dr92/rule.ts
  packages/alfa-rules/src/sia-dr93/rule.ts
  packages/alfa-rules/src/sia-dr95/rule.ts
  packages/alfa-rules/src/sia-r18/rule.ts
  packages/alfa-rules/src/sia-r66/rule.ts
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/test/sia-dr18/rule.spec.tsx
  packages/alfa-rules/test/sia-dr62/rule.spec.tsx
  packages/alfa-rules/test/sia-dr62/serialise.spec.ts
  packages/alfa-rules/test/sia-dr66/rule.spec.tsx
  packages/alfa-rules/test/sia-dr69/rule.spec.tsx
  packages/alfa-rules/test/sia-dr91/rule.spec.tsx
  packages/alfa-rules/test/sia-dr92/rule.spec.tsx
  packages/alfa-rules/test/sia-dr93/rule.spec.tsx
  packages/alfa-rules/test/sia-dr95/rule.spec.tsx
  packages/alfa-rules/test/sia-r18/rule.spec.tsx
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: major

#1417 Clean up changesets
  .changeset/cold-mugs-wave.md
  .changeset/gold-pens-shave.md
  .changeset/purple-cats-applaud.md
  .changeset/short-rings-drop.md
  .changeset/sweet-days-reply.md
  .changeset/ten-jars-think.md
  .changeset/wet-actors-search.md
Labels: documentation

#1418 Add missing dependencies
  .changeset/lucky-carpets-develop.md
  packages/alfa-http/package.json
  packages/alfa-http/tsconfig.json
  packages/alfa-web/package.json
  packages/alfa-web/tsconfig.json
  yarn.lock
Labels: internal

#1419 Export `ColorError` diagnostic
  .changeset/bright-plants-sort.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/diagnostic.ts
Labels: patch

#1420 "Constrast" typo
  .changeset/gold-crabs-prove.md
  .changeset/long-dolphins-begin.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/diagnostic.ts
  packages/alfa-rules/src/sia-r62/diagnostics.ts
  packages/alfa-rules/src/sia-r62/rule.ts
Labels: patch

#1424 Remove compound `Length` from `alfa-style`
  .changeset/forty-wasps-grab.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/value.ts
  packages/alfa-css/src/value/numeric/length.ts
  packages/alfa-css/test/value/numeric/length.spec.tsx
  packages/alfa-rules/src/sia-r62/serialise.ts
  packages/alfa-style/src/element/predicate/has-border.ts
  packages/alfa-style/src/element/predicate/has-outline.ts
  packages/alfa-style/src/property/border-top-width.ts
  packages/alfa-style/src/property/letter-spacing.ts
  packages/alfa-style/src/property/outline-offset.ts
  packages/alfa-style/src/property/outline-width.ts
  packages/alfa-style/src/property/value/compound.ts
  packages/alfa-style/src/property/word-spacing.ts
Labels: major

#1413 Query API for `alfa-dom`
  .changeset/odd-bats-wink.md
  docs/review/api/alfa-collection.api.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/src/node.ts
  packages/alfa-collection/src/collection.ts
  packages/alfa-dom/src/index.ts
  packages/alfa-dom/src/node/document.ts
  packages/alfa-dom/src/node/query/element-descendants.ts
  packages/alfa-dom/src/node/query/element-id-map.ts
  packages/alfa-dom/src/node/query/index.ts
  packages/alfa-dom/test/node/query/element-descendants.spec.tsx
  packages/alfa-dom/test/node/query/element-id-map.spec.tsx
  packages/alfa-dom/tsconfig.json
  packages/alfa-rules/src/sia-r19/rule.ts
Labels: major
