Repository Siteimprove/alfa, pull requests merged in 2023-10, with the labels that each got.

#1454 Calculatable `Position`
  .changeset/clever-falcons-press.md
  .changeset/cuddly-items-repeat.md
  .changeset/shy-schools-flash.md
  .changeset/silver-papayas-develop.md
  .changeset/smart-mayflies-jog.md
  .changeset/thick-ways-clap.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/value/image/gradient-radial.ts
  packages/alfa-css/src/value/numeric/length-percentage.ts
  packages/alfa-css/src/value/position.ts
  packages/alfa-css/src/value/position/component.ts
  packages/alfa-css/src/value/position/index.ts
  packages/alfa-css/src/value/position/keywords.ts
  packages/alfa-css/src/value/position/position.ts
  packages/alfa-css/src/value/position/side.ts
  packages/alfa-css/src/value/shape/circle.ts
  packages/alfa-css/src/value/shape/ellipse.ts
  packages/alfa-css/test/value/position.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-rules/test/sia-r62/serialise.spec.ts
  packages/alfa-style/src/property/background-position-x.ts
  packages/alfa-style/src/property/background-position-y.ts
  packages/alfa-style/src/resolver.ts
  packages/alfa-style/test/property/background.spec.tsx
Labels: major

#1480 Update dependencies
  config/knip.ts
  package.json
  yarn.lock
Labels: dependencies

#1481 Configure Renovate
  config/alfa-renovate.json
  renovate.json
Labels: dependencies

#1478 Calculatable shape
  .changeset/gold-buttons-notice.md
  .changeset/shy-schools-flash.md
  .changeset/thick-ways-clap.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/value/image/gradient/linear/side.ts
  packages/alfa-css/src/value/image/gradient/radial/radial.ts
  packages/alfa-css/src/value/numeric/length-percentage.ts
  packages/alfa-css/src/value/position/component.ts
  packages/alfa-css/src/value/position/position.ts
  packages/alfa-css/src/value/position/side.ts
  packages/alfa-css/src/value/shape/basic-shape.ts
  packages/alfa-css/src/value/shape/circle.ts
  packages/alfa-css/src/value/shape/corner.ts
  packages/alfa-css/src/value/shape/ellipse.ts
  packages/alfa-css/src/value/shape/inset.ts
  packages/alfa-css/src/value/shape/polygon.ts
  packages/alfa-css/src/value/shape/radius.ts
  packages/alfa-css/src/value/shape/rectangle.ts
  packages/alfa-css/src/value/shape/shape.ts
  packages/alfa-css/test/value/shape/circle.spec.ts
  packages/alfa-css/test/value/shape/ellipse.spec.ts
  packages/alfa-css/test/value/shape/inset.spec.ts
  packages/alfa-css/test/value/shape/polygon.spec.ts
  packages/alfa-css/test/value/shape/rectangle.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-style/src/property/background-position-x.ts
  packages/alfa-style/src/property/background-position-y.ts
  packages/alfa-style/src/resolver.ts
Labels: major

#1474 Store original device layout was scraped with
  .changeset/beige-colts-chew.md
  .changeset/brave-dolphins-smash.md
  .changeset/chilled-laws-hammer.md
  .changeset/metal-planets-hammer.md
  .changeset/slow-moles-thank.md
  docs/review/api/alfa-dom.api.md
  docs/review/api/alfa-json.api.md
  docs/review/api/alfa-style.api.md
  docs/review/api/alfa-tree.api.md
  packages/alfa-dom/package.json
  packages/alfa-dom/src/h.ts
  packages/alfa-dom/src/jsx.ts
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/src/node/document.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/element/predicate/has-box.ts
  packages/alfa-dom/src/node/fragment.ts
  packages/alfa-dom/src/node/shadow.ts
  packages/alfa-dom/test/jsx.spec.tsx
  packages/alfa-dom/tsconfig.json
  packages/alfa-json/src/serializable.ts
  packages/alfa-rules/src/common/expectation/contrast.ts
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
  packages/alfa-style/src/element/element.ts
  packages/alfa-style/src/element/helpers/get-bounding-box.ts
  packages/alfa-style/src/node/predicate/is-clipped.ts
  packages/alfa-style/src/node/predicate/is-offscreen.ts
  packages/alfa-style/src/style.ts
  packages/alfa-style/test/node/predicate/is-clipped.spec.tsx
  packages/alfa-style/test/node/predicate/is-offscreen.spec.tsx
  packages/alfa-style/tsconfig.json
  packages/alfa-tree/src/tree.ts
  packages/alfa-web/src/page.ts
  packages/alfa-web/test/page.spec.tsx
  packages/alfa-web/tsconfig.json
  yarn.lock
Labels: major

#1485 Consider that images scale to specified dimensions, rather than overflowing.
  .changeset/strong-islands-relax.md
  packages/alfa-style/src/node/predicate/is-clipped.ts
  packages/alfa-style/test/node/predicate/is-visible.spec.tsx
Labels: patch

#1487 Remove `parsebase` functions
  .changeset/happy-gorillas-flash.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/value/numeric/angle.ts
  packages/alfa-css/src/value/numeric/integer.ts
  packages/alfa-css/src/value/numeric/length.ts
  packages/alfa-css/src/value/numeric/number.ts
  packages/alfa-css/src/value/numeric/percentage.ts
  packages/alfa-media/src/media.ts
  packages/alfa-style/src/property/border-image-slice.ts
  packages/alfa-style/src/property/border-radius.ts
Labels: major

#1491 Properly use `Value.HasCalculation` in CSS values
  .changeset/thin-melons-hope.md
  packages/alfa-css/src/value/collection/list.ts
  packages/alfa-css/src/value/collection/tuple.ts
  packages/alfa-css/src/value/resolvable.ts
  packages/alfa-css/src/value/shadow.ts
Labels: major

#1493 Streamline CSS numeric types a bit
  .changeset/green-days-fly.md
  .changeset/sharp-apricots-explain.md
  .changeset/shiny-worms-push.md
  packages/alfa-css/src/value/color/color.ts
  packages/alfa-css/src/value/color/format.ts
  packages/alfa-css/src/value/color/hsl.ts
  packages/alfa-css/src/value/color/rgb.ts
  packages/alfa-css/src/value/numeric/angle-percentage.ts
  packages/alfa-css/src/value/numeric/angle.ts
  packages/alfa-css/src/value/numeric/dimension.ts
  packages/alfa-css/src/value/numeric/integer.ts
  packages/alfa-css/src/value/numeric/length-percentage.ts
  packages/alfa-css/src/value/numeric/length.ts
  packages/alfa-css/src/value/numeric/number.ts
  packages/alfa-css/src/value/numeric/numeric.ts
  packages/alfa-css/src/value/numeric/percentage.ts
  packages/alfa-css/test/value/numeric/angle-percentage.spec.ts
  packages/alfa-css/test/value/numeric/length-percentage.spec.ts
  packages/alfa-css/test/value/numeric/percentage.spec.ts
  packages/alfa-rules/src/sia-r84/rule.ts
  packages/alfa-style/src/node/predicate/is-clipped.ts
  packages/alfa-style/src/property/border-image-width.ts
  packages/alfa-style/src/property/height.ts
  packages/alfa-style/src/property/opacity.ts
Labels: minor
