Repository Siteimprove/alfa, pull requests merged in 2023-03, with the labels that each got.

#1364 Cache applicability
  packages/alfa-rules/src/common/applicability/audio.ts
  packages/alfa-rules/src/common/applicability/role-attributes.ts
  packages/alfa-rules/src/common/applicability/video.ts
  packages/alfa-rules/src/sia-r110/rule.ts
  packages/alfa-rules/src/sia-r21/rule.ts
  packages/alfa-rules/tsconfig.json
Labels: internal, Performance

#1365 Fix bug in whitespace parser due to incorrect use of `Slice` type
  packages/alfa-css/src/syntax/token.ts
  packages/alfa-css/test/syntax/token.spec.ts
  packages/alfa-css/tsconfig.json
Labels: patch

#1369 Remove unused imports
  packages/alfa-rules/src/common/applicability/role-attributes.ts
  packages/alfa-rules/src/sia-er18/rule.ts
  packages/alfa-rules/src/sia-r1/rule.ts
  packages/alfa-rules/src/sia-r10/rule.ts
  packages/alfa-rules/src/sia-r11/rule.ts
  packages/alfa-rules/src/sia-r12/rule.ts
  packages/alfa-rules/src/sia-r13/rule.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/src/sia-r18/rule.ts
  packages/alfa-rules/src/sia-r19/rule.ts
  packages/alfa-rules/src/sia-r2/rule.ts
  packages/alfa-rules/src/sia-r20/rule.ts
  packages/alfa-rules/src/sia-r28/rule.ts
  packages/alfa-rules/src/sia-r3/rule.ts
  packages/alfa-rules/src/sia-r39/rule.ts
  packages/alfa-rules/src/sia-r40/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r43/rule.ts
  packages/alfa-rules/src/sia-r45/rule.ts
  packages/alfa-rules/src/sia-r46/rule.ts
  packages/alfa-rules/src/sia-r47/rule.ts
  packages/alfa-rules/src/sia-r53/rule.ts
  packages/alfa-rules/src/sia-r54/rule.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r56/rule.ts
  packages/alfa-rules/src/sia-r59/rule.ts
  packages/alfa-rules/src/sia-r63/rule.ts
  packages/alfa-rules/src/sia-r64/rule.ts
  packages/alfa-rules/src/sia-r67/rule.ts
  packages/alfa-rules/src/sia-r70/rule.ts
  packages/alfa-rules/src/sia-r71/rule.ts
  packages/alfa-rules/src/sia-r72/rule.ts
  packages/alfa-rules/src/sia-r73/rule.ts
  packages/alfa-rules/src/sia-r74/rule.ts
  packages/alfa-rules/src/sia-r77/rule.ts
  packages/alfa-rules/src/sia-r8/rule.ts
  packages/alfa-rules/src/sia-r80/rule.ts
  packages/alfa-rules/src/sia-r82/rule.ts
  packages/alfa-rules/src/sia-r85/rule.ts
  packages/alfa-rules/src/sia-r86/rule.ts
  packages/alfa-rules/src/sia-r9/rule.ts
  packages/alfa-rules/src/sia-r94/rule.ts
  packages/alfa-rules/src/sia-r95/rule.ts
  packages/alfa-rules/src/sia-r96/rule.ts
Labels: internal

#1367 Remove `array` property from `Slice`
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-parser.api.md
  docs/review/api/alfa-slice.api.md
  packages/alfa-css/src/syntax/block.ts
  packages/alfa-css/src/syntax/component.ts
  packages/alfa-css/src/syntax/declaration.ts
  packages/alfa-css/src/syntax/function.ts
  packages/alfa-css/src/syntax/token.ts
  packages/alfa-css/test/syntax/block.spec.ts
  packages/alfa-css/test/syntax/component.spec.ts
  packages/alfa-css/test/syntax/declaration.spec.ts
  packages/alfa-css/test/syntax/function.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-parser/src/parser.ts
  packages/alfa-rules/src/sia-r10/rule.ts
  packages/alfa-slice/src/slice.ts
  packages/alfa-slice/test/slice.spec.ts
  packages/alfa-style/src/style.ts
  packages/alfa-xpath/src/syntax/token.ts
Labels: major

#1376 Improve `Flattened` type
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-rules.api.md
  package.json
  packages/alfa-act/src/audit.ts
  packages/alfa-act/src/cache.ts
  packages/alfa-act/src/interview.ts
  packages/alfa-act/src/oracle.ts
  packages/alfa-act/src/outcome.ts
  packages/alfa-act/src/question.ts
  packages/alfa-act/src/rule.ts
  packages/alfa-dom/src/jsx.ts
  packages/alfa-rules/src/common/act/expectation.ts
  packages/alfa-rules/src/common/act/is-passed.ts
  packages/alfa-rules/src/index.ts
  packages/alfa-rules/test/common/evaluate.ts
  packages/alfa-rules/test/common/outcome.ts
  yarn.lock
Labels: major

#1381 SIA-R16, SIA-R19: Make open `combobox` require `aria-controls`
  docs/review/api/alfa-aria.api.md
  packages/alfa-aria/src/node.ts
  packages/alfa-aria/src/node/predicate.ts
  packages/alfa-aria/src/node/predicate/has-attribute.ts
  packages/alfa-aria/src/node/predicate/has-role.ts
  packages/alfa-aria/tsconfig.json
  packages/alfa-rules/src/common/predicate/is-aria-controls-required.ts
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/src/sia-r19/rule.ts
  packages/alfa-rules/test/sia-r16/rule.spec.tsx
  packages/alfa-rules/test/sia-r19/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#1386 SIA-R13: ignore `<iframe>` with negative `tabindex`
  packages/alfa-rules/src/sia-r13/rule.ts
  packages/alfa-rules/test/sia-r13/rule.spec.tsx
Labels: patch

#1387 SIA-R78: accept accordions (headings containing button/link)
  packages/alfa-rules/src/sia-r78/rule.ts
  packages/alfa-rules/test/sia-r78/rule.spec.tsx
Labels: patch

#1375 Use `hasComputedStyle` and `hasCascadedStyle` in more places
  packages/alfa-rules/src/sia-r71/rule.ts
  packages/alfa-rules/src/sia-r72/rule.ts
  packages/alfa-rules/src/sia-r74/rule.ts
  packages/alfa-rules/src/sia-r80/rule.ts
  packages/alfa-rules/src/sia-r85/rule.ts
  packages/alfa-rules/test/sia-r74/rule.spec.tsx
  packages/alfa-style/src/element/predicate/is-inert.ts
  packages/alfa-style/src/node/predicate/is-transparent.ts
  packages/alfa-style/test/node/predicate/is-transparent.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: patch
