Repository Siteimprove/alfa, pull requests merged in 2023-11, with the labels that each got.

#1503 Fix API extractor and extract missing
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-network.api.md
  docs/review/api/alfa-style.api.md
  docs/review/api/alfa-xpath.api.md
  scripts/api-extractor.mjs
Labels: internal

#1497 Remove unused question
  .changeset/strange-hairs-share.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/question.ts
  packages/alfa-rules/test/common/oracle.ts
Labels: major

#1502 Send accessible name diagnostic
  .changeset/beige-birds-taste.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/diagnostic.ts
  packages/alfa-rules/src/common/diagnostic.ts
  packages/alfa-rules/src/common/diagnostic/with-accessible-name.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r39/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/test/sia-r15/rule.spec.tsx
  packages/alfa-rules/test/sia-r39/rule.spec.tsx
  packages/alfa-rules/test/sia-r41/rule.spec.tsx
  packages/alfa-rules/test/sia-r81/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#1496 Use parser helpers in `alfa-css` tests
  packages/alfa-css/test/calculation/calculation.spec.ts
  packages/alfa-css/test/calculation/math-functions.spec.ts
  packages/alfa-css/test/common/parse.ts
  packages/alfa-css/test/value/collection/tuple.spec.ts
  packages/alfa-css/test/value/image/image.spec.ts
  packages/alfa-css/test/value/image/linear-gradient.spec.ts
  packages/alfa-css/test/value/image/radial-gradient.spec.ts
  packages/alfa-css/test/value/numeric/angle-percentage.spec.ts
  packages/alfa-css/test/value/numeric/length-percentage.spec.ts
  packages/alfa-css/test/value/numeric/percentage.spec.ts
  packages/alfa-css/test/value/position.spec.ts
  packages/alfa-css/test/value/shape.spec.ts
  packages/alfa-css/test/value/shape/circle.spec.ts
  packages/alfa-css/test/value/shape/ellipse.spec.ts
  packages/alfa-css/test/value/shape/inset.spec.ts
  packages/alfa-css/test/value/shape/polygon.spec.ts
  packages/alfa-css/test/value/shape/rectangle.spec.ts
Labels: internal

#1495 Turn `partiallyResolve()` into a `Value` method
  .changeset/bright-gorillas-travel.md
  .changeset/dry-peaches-draw.md
  .changeset/long-plums-join.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-css/src/calculation/math-expression/function.ts
  packages/alfa-css/src/calculation/math-expression/kind.ts
  packages/alfa-css/src/calculation/math-expression/operation.ts
  packages/alfa-css/src/calculation/numeric/numeric.ts
  packages/alfa-css/src/value/collection/list.ts
  packages/alfa-css/src/value/collection/tuple.ts
  packages/alfa-css/src/value/color/format.ts
  packages/alfa-css/src/value/image/gradient/gradient.ts
  packages/alfa-css/src/value/image/gradient/item/hint.ts
  packages/alfa-css/src/value/image/gradient/item/item.ts
  packages/alfa-css/src/value/image/gradient/item/stop.ts
  packages/alfa-css/src/value/image/gradient/linear/corner.ts
  packages/alfa-css/src/value/image/gradient/linear/linear.ts
  packages/alfa-css/src/value/image/gradient/linear/side.ts
  packages/alfa-css/src/value/image/gradient/radial/circle.ts
  packages/alfa-css/src/value/image/gradient/radial/ellipse.ts
  packages/alfa-css/src/value/image/gradient/radial/extent.ts
  packages/alfa-css/src/value/image/gradient/radial/radial.ts
  packages/alfa-css/src/value/image/gradient/radial/shape.ts
  packages/alfa-css/src/value/image/image.ts
  packages/alfa-css/src/value/numeric/angle-percentage.ts
  packages/alfa-css/src/value/numeric/dimension.ts
  packages/alfa-css/src/value/numeric/integer.ts
  packages/alfa-css/src/value/numeric/length-percentage.ts
  packages/alfa-css/src/value/numeric/number.ts
  packages/alfa-css/src/value/numeric/numeric.ts
  packages/alfa-css/src/value/numeric/percentage.ts
  packages/alfa-css/src/value/position/component.ts
  packages/alfa-css/src/value/position/position.ts
  packages/alfa-css/src/value/position/side.ts
  packages/alfa-css/src/value/resolvable.ts
  packages/alfa-css/src/value/shape/basic-shape.ts
  packages/alfa-css/src/value/shape/circle.ts
  packages/alfa-css/src/value/shape/ellipse.ts
  packages/alfa-css/src/value/shape/inset.ts
  packages/alfa-css/src/value/shape/polygon.ts
  packages/alfa-css/src/value/shape/radius.ts
  packages/alfa-css/src/value/shape/shape.ts
  packages/alfa-css/src/value/transform/transform.ts
  packages/alfa-css/src/value/transform/translate.ts
  packages/alfa-css/src/value/value.ts
  packages/alfa-css/test/value/numeric/angle-percentage.spec.ts
  packages/alfa-css/test/value/numeric/percentage.spec.ts
  packages/alfa-css/test/value/position.spec.ts
  packages/alfa-rules/src/common/diagnostic/contrast.ts
  packages/alfa-rules/src/common/diagnostic/text-spacing.ts
  packages/alfa-rules/src/common/diagnostic/with-bad-elements.ts
  packages/alfa-rules/src/common/diagnostic/with-role.ts
  packages/alfa-rules/src/deprecated.ts
  packages/alfa-rules/src/experimental.ts
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/tags/version.ts
  packages/alfa-xpath/src/functions/fn.ts
Labels: major

#1504 Send role diagnostic in R8
  .changeset/chilled-sloths-wonder.md
  packages/alfa-rules/src/sia-r8/rule.ts
  packages/alfa-rules/test/sia-r8/rule.spec.tsx
Labels: minor

#1505 Factor heading diagnostics
  .changeset/funny-ducks-approve.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/diagnostic.ts
  packages/alfa-rules/src/common/diagnostic.ts
  packages/alfa-rules/src/common/diagnostic/with-other-heading.ts
  packages/alfa-rules/src/sia-r53/rule.ts
  packages/alfa-rules/src/sia-r78/rule.ts
  packages/alfa-rules/test/sia-r53/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: major

#1506 SIA-R70: Accept `<hgroup>`
  .changeset/old-badgers-drive.md
  .changeset/purple-lemons-buy.md
  packages/alfa-aria/src/feature.ts
  packages/alfa-rules/src/sia-r70/rule.ts
Labels: patch

#1509 Reject changesets with major bumps
  .changeset/mighty-hounds-fly.md
  config/validate-structure.json
  docs/review/api/alfa-toolchain.api.md
  packages/alfa-toolchain/package.json
  packages/alfa-toolchain/src/validation/validate-all.ts
  packages/alfa-toolchain/src/validation/validate-changesets.ts
  packages/alfa-toolchain/tsconfig.json
  yarn.lock
Labels: minor

#1516 Show tested file during `yarn test`
  scripts/test.mjs
Labels: internal

#1513 Fix `this` binding issue in alfa-performance
  .changeset/metal-points-build.md
  packages/alfa-performance/src/now.ts
Labels: patch

#1514 Compute selector specificity at parse time.
  .changeset/eleven-shrimps-tap.md
  .changeset/rude-rivers-check.md
  docs/review/api/alfa-selector.api.md
  docs/review/api/alfa-test.api.md
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-map/test/property.spec.ts
  packages/alfa-selector/package.json
  packages/alfa-selector/src/selector/complex.ts
  packages/alfa-selector/src/selector/compound.ts
  packages/alfa-selector/src/selector/list.ts
  packages/alfa-selector/src/selector/relative.ts
  packages/alfa-selector/src/selector/selector.ts
  packages/alfa-selector/src/selector/simple/attribute.ts
  packages/alfa-selector/src/selector/simple/class.ts
  packages/alfa-selector/src/selector/simple/id.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/has.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/is.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/not.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/pseudo-class.ts
  packages/alfa-selector/src/selector/simple/pseudo-element/pseudo-element.ts
  packages/alfa-selector/src/selector/simple/type.ts
  packages/alfa-selector/src/selector/simple/universal.ts
  packages/alfa-selector/src/specificity.ts
  packages/alfa-selector/test/basic.spec.ts
  packages/alfa-selector/test/complex.spec.ts
  packages/alfa-selector/test/compound.spec.ts
  packages/alfa-selector/test/list.spec.ts
  packages/alfa-selector/test/pseudo-class.spec.tsx
  packages/alfa-selector/test/pseudo-element.spec.ts
  packages/alfa-selector/test/specificity.spec.ts
  packages/alfa-selector/tsconfig.json
  packages/alfa-test/README.md
  packages/alfa-test/src/index.ts
  packages/alfa-test/src/rng.ts
  packages/alfa-test/src/test.ts
  packages/alfa-test/tsconfig.json
  yarn.lock
Labels: minor

#1517 SIA-R10: Accept `one-time-code`
  .changeset/tall-mails-kiss.md
  packages/alfa-rules/src/sia-r10/rule.ts
Labels: patch

#1518 Add :where selector
  .changeset/smart-weeks-bathe.md
  docs/review/api/alfa-selector.api.md
  packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/where.ts
  packages/alfa-selector/test/specificity.spec.ts
  packages/alfa-selector/tsconfig.json
Labels: minor
