Repository Siteimprove/alfa, pull requests merged in 2023-06, with the labels that each got.

#1428 Description tracks deprecation
  .changeset/lemon-eagles-wash.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/deprecated.ts
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-dr34/rule.ts
  packages/alfa-rules/src/sia-dr36/rule.ts
  packages/alfa-rules/src/sia-r35/rule.ts
  packages/alfa-rules/src/sia-r37/rule.ts
  packages/alfa-rules/src/sia-r38/rule.ts
  packages/alfa-rules/test/sia-dr34/rule.spec.tsx
  packages/alfa-rules/test/sia-dr36/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: major

#1430 Update package-dependency-graph and node
  .github/workflows/alfa-release.yml
  .github/workflows/integrate.yml
  .github/workflows/scan.yml
  package.json
  yarn.lock
Labels: internal

#1427 Add `alfa-rectangle` package
  .changeset/clever-turtles-flow.md
  .changeset/heavy-onions-exist.md
  docs/dependency-graph.dot
  docs/dependency-graph.png
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/package.json
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/tsconfig.json
  packages/alfa-rectangle/package.json
  packages/alfa-rectangle/src/index.ts
  packages/alfa-rectangle/src/rectangle.ts
  packages/alfa-rectangle/test/rectangle.spec.ts
  packages/alfa-rectangle/tsconfig.json
  packages/tsconfig.json
  yarn.lock
Labels: minor

#1434 SIA-R78: change scope to `Page`
  .changeset/cool-moose-knock.md
  packages/alfa-rules/src/sia-r78/rule.ts
Labels: patch

#1435 Accept more URIs in `Criterion.fromURI`
  .changeset/nice-socks-approve.md
  packages/alfa-wcag/src/criterion.ts
Labels: patch

#1438 Clean up changesets
  .changeset/cold-tables-sing.md
  .changeset/cool-moose-knock.md
  .changeset/gold-pens-shave.md
  .changeset/great-kiwis-chew.md
  .changeset/hip-baboons-applaud.md
  .changeset/tiny-bulldogs-check.md
  .changeset/wild-horses-press.md
Labels: internal

#1441 Removed `alfa-highlight`
  packages/alfa-highlight/CHANGELOG.md
  packages/alfa-highlight/config/api-extractor.json
  packages/alfa-highlight/package.json
  packages/alfa-highlight/src/index.ts
  packages/alfa-highlight/src/marker.ts
  packages/alfa-highlight/tsconfig.json
  packages/alfa-test/package.json
  packages/alfa-test/src/format.ts
  packages/alfa-test/tsconfig.json
  packages/tsconfig.json
  yarn.lock
Labels: major

#1443 Support for `dimension-percentage` type and calculation
  .changeset/few-parrots-tickle.md
  .changeset/nasty-impalas-act.md
  .changeset/real-buses-fix.md
  .changeset/selfish-horses-run.md
  .changeset/unlucky-tools-move.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/calculation/math-expression/math.ts
  packages/alfa-css/src/calculation/numeric/dimension.ts
  packages/alfa-css/src/value/numeric/angle-percentage.ts
  packages/alfa-css/src/value/numeric/angle.ts
  packages/alfa-css/src/value/numeric/dimension.ts
  packages/alfa-css/src/value/numeric/index.ts
  packages/alfa-css/src/value/numeric/integer.ts
  packages/alfa-css/src/value/numeric/length-percentage.ts
  packages/alfa-css/src/value/numeric/length.ts
  packages/alfa-css/src/value/numeric/numeric.ts
  packages/alfa-css/src/value/numeric/percentage.ts
  packages/alfa-css/src/value/transform/function.ts
  packages/alfa-css/src/value/value.ts
  packages/alfa-css/test/value/numeric/angle-percentage.spec.ts
  packages/alfa-css/test/value/numeric/length-percentage.spec.ts
  packages/alfa-css/test/value/numeric/length.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-media/src/resolver.ts
  packages/alfa-rules/src/sia-r74/rule.ts
  packages/alfa-rules/src/sia-r75/rule.ts
  packages/alfa-style/src/node/predicate/is-clipped.ts
  packages/alfa-style/src/property/background-size.ts
  packages/alfa-style/src/property/border-top-left-radius.ts
  packages/alfa-style/src/property/font-size.ts
  packages/alfa-style/src/property/line-height.ts
  packages/alfa-style/src/property/text-decoration-thickness.ts
  packages/alfa-style/src/property/text-indent.ts
  packages/alfa-style/src/property/top.ts
  packages/alfa-style/src/property/value/compound.ts
  packages/alfa-style/src/property/vertical-align.ts
  packages/alfa-style/src/resolver.ts
  packages/alfa-style/test/property/font-size.spec.tsx
  packages/alfa-style/test/property/top.spec.tsx
  packages/alfa-style/tsconfig.json
Labels: major
