Repository Siteimprove/alfa, pull requests merged in 2023-04, with the labels that each got.

#1389 Add list of Alfa projects to documentation
  docs/README.md
  docs/guides/README.md
Labels: documentation

#1394 Rename `isAriaControlsRequired` -> `isAriaControlsOpitonal`
  .changeset/purple-cats-applaud.md
  packages/alfa-rules/src/common/predicate/is-aria-controls-optional.ts
  packages/alfa-rules/src/sia-r16/rule.ts
  packages/alfa-rules/src/sia-r19/rule.ts
  packages/alfa-rules/tsconfig.json
Labels: patch

#1398 Tools update
  .github/workflows/scan.yml
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/releases/yarn-3.0.2.cjs
  .yarn/releases/yarn-3.5.0.cjs
  .yarnrc.yml
  package.json
  packages/alfa-aria/package.json
  packages/alfa-wcag/package.json
  yarn.lock
Labels: dependencies, internal, actions

#1401 Regenerate API documentation in release action
  .github/workflows/alfa-release.yml
  .github/workflows/release.yml
Labels: internal

#1397 Style refactor: streamlining type parameters and extracting variables mangling
  docs/review/api/alfa-style.api.md
  packages/alfa-style/src/property.ts
  packages/alfa-style/src/style.ts
  packages/alfa-style/src/variable.ts
  packages/alfa-style/test/variable.spec.ts
  packages/alfa-style/tsconfig.json
Labels: internal

#1402 Add `Maybe#toOption` and move out of `Option` namespace
  .changeset/dry-apples-think.md
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-option.api.md
  packages/alfa-act/src/rule.ts
  packages/alfa-option/src/index.ts
  packages/alfa-option/src/maybe.ts
  packages/alfa-option/src/option.ts
  packages/alfa-option/test/maybe.spec.ts
  packages/alfa-option/tsconfig.json
  packages/alfa-rules/src/common/act/expectation.ts
Labels: major
