Repository Siteimprove/alfa, pull requests merged in 2023-12, with the labels that each got.

#1526 [renovate]: Automatically dedupe after update
  config/alfa-renovate.json
Labels: internal

#1524 Accept "of selector" syntax in `:nth-[last]-child` pseudo-classes
  .changeset/breezy-horses-smell.md
  docs/review/api/alfa-selector.api.md
  packages/alfa-selector/src/selector/selector.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/nth-child.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/nth-last-child.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/pseudo-class.ts
  packages/alfa-selector/test/nth-[last]-child.spec.tsx
  packages/alfa-selector/test/pseudo-class.spec.tsx
  packages/alfa-selector/tsconfig.json
Labels: minor

#1523 Clone-replace for `alfa-dom` `Node`s
  .changeset/twelve-shrimps-call.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/package.json
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/src/node/attribute.ts
  packages/alfa-dom/src/node/comment.ts
  packages/alfa-dom/src/node/document.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/fragment.ts
  packages/alfa-dom/src/node/shadow.ts
  packages/alfa-dom/src/node/text.ts
  packages/alfa-dom/src/node/type.ts
  packages/alfa-dom/test/node.spec.tsx
  packages/alfa-dom/tsconfig.json
  yarn.lock
Labels: minor

#1529 Add diagnostics to can't tell outcomes
  .changeset/new-maps-rush.md
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r39/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/test/sia-r15/rule.spec.tsx
  packages/alfa-rules/test/sia-r39/rule.spec.tsx
  packages/alfa-rules/test/sia-r41/rule.spec.tsx
  packages/alfa-rules/test/sia-r81/rule.spec.tsx
Labels: minor

#1531 Correctly cache `isVisible` in case of empty context
  packages/alfa-style/src/node/predicate/is-visible.ts
Labels: patch

#1534 Streamline and test `@siteimprove/alfa-cascade`
  .changeset/four-parents-jog.md
  .changeset/pink-walls-remain.md
  .changeset/tiny-eyes-attack.md
  docs/review/api/alfa-cascade.api.md
  docs/review/api/alfa-selector.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-cascade/README.md
  packages/alfa-cascade/package.json
  packages/alfa-cascade/src/ancestor-filter.ts
  packages/alfa-cascade/src/cascade.ts
  packages/alfa-cascade/src/rule-tree.ts
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-cascade/test/ancestor-filter.spec.tsx
  packages/alfa-cascade/test/rule-tree.spec.ts
  packages/alfa-cascade/tsconfig.json
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-selector/src/selector/complex.ts
  packages/alfa-selector/src/selector/compound.ts
  packages/alfa-selector/src/selector/selector.ts
  packages/alfa-selector/src/selector/simple/class.ts
  packages/alfa-selector/src/selector/simple/id.ts
  packages/alfa-selector/src/selector/simple/type.ts
  packages/alfa-selector/test/basic.spec.ts
  packages/alfa-selector/test/complex.spec.ts
  packages/alfa-selector/test/compound.spec.ts
  packages/alfa-selector/test/list.spec.ts
  packages/alfa-selector/test/nth-[last]-child.spec.tsx
  packages/alfa-selector/test/pseudo-class.spec.tsx
  packages/alfa-style/src/style.ts
  yarn.lock
Labels: major

#1537 Rename diagnostic `WithAccessibleName` to `WithName` and property `accessibleName` to `name`
  .changeset/few-ravens-shave.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/diagnostic.ts
  packages/alfa-rules/src/common/diagnostic.ts
  packages/alfa-rules/src/common/diagnostic/with-accessible-name.ts
  packages/alfa-rules/src/common/diagnostic/with-name.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r39/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/test/sia-r15/rule.spec.tsx
  packages/alfa-rules/test/sia-r39/rule.spec.tsx
  packages/alfa-rules/test/sia-r41/rule.spec.tsx
  packages/alfa-rules/test/sia-r81/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: major

#1538 Assume audio is playing and that it has controls based on attributes
  .changeset/tasty-stingrays-grab.md
  packages/alfa-rules/src/common/applicability/audio.ts
  packages/alfa-rules/test/sia-r23/rule.spec.tsx
  packages/alfa-rules/test/sia-r29/rule.spec.tsx
Labels: minor

#1539 Store rule type in abstract class
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/style/rule.ts
  packages/alfa-dom/src/style/rule/condition.ts
  packages/alfa-dom/src/style/rule/font-face.ts
  packages/alfa-dom/src/style/rule/grouping.ts
  packages/alfa-dom/src/style/rule/import.ts
  packages/alfa-dom/src/style/rule/keyframe.ts
  packages/alfa-dom/src/style/rule/keyframes.ts
  packages/alfa-dom/src/style/rule/media.ts
  packages/alfa-dom/src/style/rule/namespace.ts
  packages/alfa-dom/src/style/rule/page.ts
  packages/alfa-dom/src/style/rule/style.ts
  packages/alfa-dom/src/style/rule/supports.ts
Labels: internal

#1541 Align R18 with specification
  .changeset/violet-coats-tie.md
  packages/alfa-aria/src/feature.ts
  packages/alfa-rules/src/sia-r18/rule.ts
  packages/alfa-rules/test/sia-r18/rule.spec.tsx
Labels: patch

#1540 `alfa-cascade`: Clean up, refactor, add tests.
  .changeset/fast-rules-leave.md
  .changeset/moody-lizards-enjoy.md
  .changeset/pretty-buttons-own.md
  .changeset/selfish-elephants-float.md
  .changeset/tender-starfishes-drum.md
  .changeset/weak-rockets-add.md
  .changeset/wet-stingrays-tap.md
  docs/review/api/alfa-cascade.api.md
  docs/review/api/alfa-comparable.api.md
  docs/review/api/alfa-dom.api.md
  docs/review/api/alfa-selector.api.md
  packages/alfa-cascade/package.json
  packages/alfa-cascade/src/ancestor-filter.ts
  packages/alfa-cascade/src/block.ts
  packages/alfa-cascade/src/cascade.ts
  packages/alfa-cascade/src/precedence/index.ts
  packages/alfa-cascade/src/precedence/order.ts
  packages/alfa-cascade/src/precedence/origin.ts
  packages/alfa-cascade/src/precedence/precedence.ts
  packages/alfa-cascade/src/rule-tree.ts
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-cascade/test/ancestor-filter.spec.tsx
  packages/alfa-cascade/test/cascade.spec.tsx
  packages/alfa-cascade/test/rule-tree.spec.ts
  packages/alfa-cascade/test/selector-map.spec.tsx
  packages/alfa-cascade/tsconfig.json
  packages/alfa-comparable/package.json
  packages/alfa-comparable/src/comparable.ts
  packages/alfa-comparable/src/comparer.ts
  packages/alfa-comparable/test/comparable.spec.ts
  packages/alfa-comparable/tsconfig.json
  packages/alfa-dom/src/h.ts
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-selector/package.json
  packages/alfa-selector/src/index.ts
  packages/alfa-selector/src/specificity.ts
  packages/alfa-selector/tsconfig.json
  packages/alfa-style/src/style.ts
  yarn.lock
Labels: major
