Repository Siteimprove/alfa, pull requests merged in 2023-07, with the labels that each got.

#1446 Support for calculatable collections of CSS values
  .changeset/big-mice-fail.md
  .changeset/orange-geese-raise.md
  docs/review/api/alfa-css.api.md
  packages/alfa-css/src/value/collection/list.ts
  packages/alfa-css/src/value/collection/tuple.ts
  packages/alfa-css/src/value/keyword.ts
  packages/alfa-css/src/value/numeric/angle-percentage.ts
  packages/alfa-css/src/value/numeric/angle.ts
  packages/alfa-css/src/value/numeric/dimension.ts
  packages/alfa-css/src/value/numeric/integer.ts
  packages/alfa-css/src/value/numeric/length-percentage.ts
  packages/alfa-css/src/value/numeric/length.ts
  packages/alfa-css/src/value/numeric/number.ts
  packages/alfa-css/src/value/numeric/numeric.ts
  packages/alfa-css/src/value/numeric/percentage.ts
  packages/alfa-css/src/value/resolvable.ts
  packages/alfa-css/src/value/string.ts
  packages/alfa-css/src/value/value.ts
  packages/alfa-css/test/value/collection/list.spec.tsx
  packages/alfa-css/test/value/collection/tuple.spec.tsx
  packages/alfa-css/tsconfig.json
  packages/alfa-style/src/property/background-repeat.ts
  packages/alfa-style/src/property/background.ts
  packages/alfa-style/src/property/border-image-slice.ts
  packages/alfa-style/src/property/display.ts
  packages/alfa-style/src/property/font-variant.ts
Labels: major

#1440 Element accept optional rectangle
  .changeset/grumpy-hounds-yawn.md
  .changeset/mighty-pigs-grab.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/h.ts
  packages/alfa-dom/src/jsx.ts
  packages/alfa-dom/src/native.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/test/jsx.spec.tsx
  packages/alfa-dom/tsconfig.json
  packages/alfa-rectangle/src/rectangle.ts
Labels: minor

#1447 Helper type for CSS parser
  .changeset/sharp-cameras-film.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/calculation/math-expression/math.ts
  packages/alfa-css/src/calculation/numeric/angle.ts
  packages/alfa-css/src/calculation/numeric/integer.ts
  packages/alfa-css/src/calculation/numeric/length.ts
  packages/alfa-css/src/calculation/numeric/number.ts
  packages/alfa-css/src/calculation/numeric/percentage.ts
  packages/alfa-css/src/syntax/block.ts
  packages/alfa-css/src/syntax/component.ts
  packages/alfa-css/src/syntax/declaration.ts
  packages/alfa-css/src/syntax/function.ts
  packages/alfa-css/src/syntax/index.ts
  packages/alfa-css/src/syntax/nth.ts
  packages/alfa-css/src/syntax/parser.ts
  packages/alfa-css/src/syntax/token.ts
  packages/alfa-css/src/value/box.ts
  packages/alfa-css/src/value/collection/list.ts
  packages/alfa-css/src/value/color/color.ts
  packages/alfa-css/src/value/color/current.ts
  packages/alfa-css/src/value/color/hex.ts
  packages/alfa-css/src/value/color/hsl.ts
  packages/alfa-css/src/value/color/named.ts
  packages/alfa-css/src/value/color/rgb.ts
  packages/alfa-css/src/value/color/system.ts
  packages/alfa-css/src/value/image/gradient-linear.ts
  packages/alfa-css/src/value/image/gradient-radial.ts
  packages/alfa-css/src/value/image/gradient.ts
  packages/alfa-css/src/value/image/image.ts
  packages/alfa-css/src/value/image/url.ts
  packages/alfa-css/src/value/keyword.ts
  packages/alfa-css/src/value/numeric/angle.ts
  packages/alfa-css/src/value/numeric/integer.ts
  packages/alfa-css/src/value/numeric/length.ts
  packages/alfa-css/src/value/numeric/number.ts
  packages/alfa-css/src/value/numeric/percentage.ts
  packages/alfa-css/src/value/position.ts
  packages/alfa-css/src/value/shadow.ts
  packages/alfa-css/src/value/shape/circle.ts
  packages/alfa-css/src/value/shape/ellipse.ts
  packages/alfa-css/src/value/shape/inset.ts
  packages/alfa-css/src/value/shape/polygon.ts
  packages/alfa-css/src/value/shape/radius.ts
  packages/alfa-css/src/value/shape/rectangle.ts
  packages/alfa-css/src/value/shape/shape.ts
  packages/alfa-css/src/value/string.ts
  packages/alfa-css/src/value/transform/matrix.ts
  packages/alfa-css/src/value/transform/perspective.ts
  packages/alfa-css/src/value/transform/rotate.ts
  packages/alfa-css/src/value/transform/scale.ts
  packages/alfa-css/src/value/transform/skew.ts
  packages/alfa-css/src/value/transform/transform.ts
  packages/alfa-css/src/value/transform/translate.ts
  packages/alfa-css/tsconfig.json
Labels: internal

#1448 Accept calculated value in CSS colors
  .changeset/silly-days-flash.md
  .changeset/sour-rules-give.md
  .changeset/tender-phones-move.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  package.json
  packages/alfa-css/src/syntax/function.ts
  packages/alfa-css/src/syntax/token.ts
  packages/alfa-css/src/value/collection/list.ts
  packages/alfa-css/src/value/collection/tuple.ts
  packages/alfa-css/src/value/color/color.ts
  packages/alfa-css/src/value/color/format.ts
  packages/alfa-css/src/value/color/hex.ts
  packages/alfa-css/src/value/color/hsl.ts
  packages/alfa-css/src/value/color/named.ts
  packages/alfa-css/src/value/color/rgb.ts
  packages/alfa-css/src/value/shadow.ts
  packages/alfa-css/src/value/value.ts
  packages/alfa-css/test/value/collection/list.spec.ts
  packages/alfa-css/test/value/collection/tuple.spec.ts
  packages/alfa-css/test/value/color/hex.spec.ts
  packages/alfa-css/test/value/color/hsl.spec.ts
  packages/alfa-css/test/value/color/named.spec.ts
  packages/alfa-css/test/value/color/rgb.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-style/src/property/background-color.ts
  packages/alfa-style/src/property/border-top-color.ts
  packages/alfa-style/src/property/box-shadow.ts
  packages/alfa-style/src/property/color.ts
  packages/alfa-style/src/property/outline-color.ts
  packages/alfa-style/src/property/text-decoration-color.ts
  packages/alfa-style/src/property/text-shadow.ts
  packages/alfa-style/src/resolver.ts
  yarn.lock
Labels: major

#1450 Use layout to improve visibility checks
  .changeset/chilly-rats-speak.md
  .changeset/grumpy-hounds-yawn.md
  .changeset/selfish-horses-run.md
  .changeset/stupid-tables-yawn.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/element/predicate.ts
  packages/alfa-dom/src/node/element/predicate/has-box.ts
  packages/alfa-dom/tsconfig.json
  packages/alfa-style/package.json
  packages/alfa-style/src/node/predicate/has-same-foreground-as-background.ts
  packages/alfa-style/src/node/predicate/is-clipped.ts
  packages/alfa-style/src/node/predicate/is-offscreen.ts
  packages/alfa-style/src/node/predicate/is-visible.ts
  packages/alfa-style/src/property/overflow-y.ts
  packages/alfa-style/test/node/predicate/is-clipped.spec.tsx
  packages/alfa-style/test/node/predicate/is-offscreen.spec.tsx
  packages/alfa-style/test/node/predicate/is-visible.spec.tsx
  packages/alfa-style/tsconfig.json
  yarn.lock
Labels: minor

#1451 Use layout to improve SIA-R83
  .changeset/breezy-llamas-admire.md
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
Labels: minor

#1456 Fix false positive bug in R75
  .changeset/silver-lions-smoke.md
  packages/alfa-rules/src/sia-r75/rule.ts
  packages/alfa-rules/test/sia-r75/rule.spec.tsx
Labels: patch

#1455 Calculatable `Shadow`
  .changeset/early-penguins-buy.md
  .changeset/tidy-tips-walk.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/README.md
  packages/alfa-css/src/value/collection/list.ts
  packages/alfa-css/src/value/collection/tuple.ts
  packages/alfa-css/src/value/resolvable.ts
  packages/alfa-css/src/value/shadow.ts
  packages/alfa-css/src/value/value.ts
  packages/alfa-css/test/value/shadow.spec.ts
  packages/alfa-css/tsconfig.json
  packages/alfa-style/README.md
  packages/alfa-style/src/element/predicate/is-visible-shadow.ts
  packages/alfa-style/src/property/box-shadow.ts
  packages/alfa-style/src/property/text-shadow.ts
  packages/alfa-style/test/property/box-shadow.spec.tsx
Labels: major
