Repository Siteimprove/alfa, pull requests merged in 2024-04, with the labels that each got.

#1592 R113 follow up
  .changeset/brown-cougars-laugh.md
  .changeset/warm-tools-return.md
  .changeset/wise-trainers-report.md
  docs/review/api/alfa-rectangle.api.md
  packages/alfa-rectangle/docs/circle-rectangle-intersection.png
  packages/alfa-rectangle/src/rectangle.ts
  packages/alfa-rectangle/test/rectangle.spec.ts
  packages/alfa-rules/package.json
  packages/alfa-rules/src/common/diagnostic/with-bounding-box.ts
  packages/alfa-rules/src/sia-r111/rule.ts
  packages/alfa-rules/src/sia-r113/rule.ts
  packages/alfa-rules/test/sia-r113/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
  yarn.lock
Labels: minor

#1587 Add Manual mode
  .changeset/stale-nails-poke.md
  docs/review/api/alfa-act.api.md
  packages/alfa-act/src/outcome.ts
Labels: patch

#1594 SIA-R111 and SIA-R113 applicability improvements
  .changeset/slimy-socks-cry.md
  packages/alfa-rules/src/common/applicability/targets-of-pointer-events.ts
  packages/alfa-rules/src/sia-r111/rule.ts
  packages/alfa-rules/src/sia-r113/rule.ts
  packages/alfa-rules/test/sia-r113/rule.spec.tsx
Labels: patch

#1596 Support and scrape user preferences
  .changeset/popular-pigs-search.md
  .changeset/strong-foxes-glow.md
  docs/review/api/alfa-device.api.md
  packages/alfa-css-feature/src/media/feature/discrete.ts
  packages/alfa-css-feature/src/media/feature/index.ts
  packages/alfa-css-feature/src/media/feature/media.ts
  packages/alfa-css-feature/src/media/feature/orientation.ts
  packages/alfa-css-feature/test/media.spec.ts
  packages/alfa-css-feature/test/user-preferences.spec.ts
  packages/alfa-css-feature/tsconfig.json
  packages/alfa-device/src/native.ts
  packages/alfa-device/src/preference.ts
Labels: minor

#1597 Inline `Device.Native.fromWindow`
  .changeset/shy-walls-know.md
  packages/alfa-device/src/native.ts
Labels: patch

#1600 Unified document serializer
  .changeset/great-weeks-wash.md
  .changeset/sharp-scissors-flash.md
  .changeset/shy-seals-fly.md
  .changeset/thin-boats-wash.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-device/src/native.ts
  packages/alfa-dom/package.json
  packages/alfa-dom/src/h.ts
  packages/alfa-dom/src/native.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/style/block.ts
  packages/alfa-dom/src/style/rule/font-face.ts
  packages/alfa-dom/src/style/rule/keyframe.ts
  packages/alfa-dom/src/style/rule/page.ts
  packages/alfa-dom/src/style/rule/style.ts
  packages/alfa-dom/test/native.spec.tsx
  packages/alfa-dom/tsconfig.json
  packages/alfa-web/src/native.ts
  yarn.lock
Labels: major

#1599 Taborder fix
  .changeset/strong-adults-clap.md
  packages/alfa-dom/package.json
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/src/node/element/predicate/is-suggested-focusable.ts
  packages/alfa-dom/test/node.spec.tsx
  packages/alfa-dom/tsconfig.json
  yarn.lock
Labels: patch

#1601 Factor R111 and R113 outcome
  .changeset/mean-glasses-hang.md
  packages/alfa-rules/src/common/outcome/target-size.ts
  packages/alfa-rules/src/sia-r111/rule.ts
  packages/alfa-rules/src/sia-r113/rule.ts
  packages/alfa-rules/test/sia-r111/rule.spec.tsx
  packages/alfa-rules/test/sia-r113/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
Labels: minor

#1603 Support `layer` and `supports` condition in `@import` CSS rules
  .changeset/empty-boats-camp.md
  .changeset/young-impalas-report.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-dom.api.md
  package.json
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-cascade/test/selector-map.spec.tsx
  packages/alfa-css-feature/src/supports/query.ts
  packages/alfa-dom/src/h.ts
  packages/alfa-dom/src/native.ts
  packages/alfa-dom/src/style/rule/import.ts
  yarn.lock
Labels: major

#1604 Css revert
  .changeset/empty-glasses-carry.md
  .changeset/great-feet-nail.md
  docs/review/api/alfa-cascade.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-cascade/src/index.ts
  packages/alfa-cascade/src/precedence/encapsulation.ts
  packages/alfa-cascade/src/precedence/origin.ts
  packages/alfa-rules/test/sia-r62/serialise.spec.ts
  packages/alfa-style/src/longhand.ts
  packages/alfa-style/src/shorthands.ts
  packages/alfa-style/src/style.ts
  packages/alfa-style/test/common.ts
  packages/alfa-style/test/style.spec.tsx
Labels: major

#1605 Fix serialization of boxes
  .changeset/six-numbers-raise.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/shadow.ts
  packages/alfa-dom/src/node/type.ts
  packages/alfa-dom/test/node.spec.tsx
Labels: bug

#1606 Correctly encapsulate `Native.fromNode`
  .changeset/many-kings-fold.md
  packages/alfa-dom/src/native.ts
Labels: patch
