Repository Siteimprove/alfa, pull requests merged in 2024-11, with the labels that each got.

#1708 Support for `perspective` CSS property
  .changeset/sweet-teachers-hammer.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/value/transform/perspective.ts
  packages/alfa-style/src/longhands.ts
  packages/alfa-style/src/property/perspective.ts
  packages/alfa-style/src/tsconfig.json
  packages/alfa-style/test/property/perspective.spec.tsx
  packages/alfa-style/test/tsconfig.json
Labels: minor, Language support

#1709 Add `Query.getDescendants` with a customisable predicate.
  .changeset/grumpy-shoes-ring.md
  .changeset/itchy-turtles-explain.md
  docs/review/api/alfa-dom.api.md
  docs/review/api/alfa-refinement.api.md
  packages/alfa-dom/src/node/query/descendants.ts
  packages/alfa-dom/src/node/query/element-descendants.ts
  packages/alfa-dom/src/node/query/element-id-map.ts
  packages/alfa-dom/src/node/query/inclusive-element-descendants.ts
  packages/alfa-dom/src/node/query/index.ts
  packages/alfa-dom/src/tsconfig.json
  packages/alfa-dom/test/node/query/descendants.spec.tsx
  packages/alfa-dom/test/node/query/element-descendants.spec.tsx
  packages/alfa-dom/test/tsconfig.json
  packages/alfa-refinement/package.json
  packages/alfa-refinement/src/refinement.ts
  packages/alfa-refinement/src/tsconfig.json
  yarn.lock
Labels: minor

#1707 Support for `will-change` CSS property
  .changeset/few-wasps-travel.md
  .changeset/perfect-walls-wash.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-string.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/package.json
  packages/alfa-css/src/tsconfig.json
  packages/alfa-css/src/value/box.ts
  packages/alfa-css/src/value/color/color.ts
  packages/alfa-css/src/value/color/current.ts
  packages/alfa-css/src/value/color/hsl.ts
  packages/alfa-css/src/value/color/rgb.ts
  packages/alfa-css/src/value/color/system.ts
  packages/alfa-css/src/value/contain.ts
  packages/alfa-css/src/value/image/gradient/radial/circle.ts
  packages/alfa-css/src/value/image/gradient/radial/ellipse.ts
  packages/alfa-css/src/value/image/gradient/radial/extent.ts
  packages/alfa-css/src/value/image/gradient/radial/radial.ts
  packages/alfa-css/src/value/image/image.ts
  packages/alfa-css/src/value/image/index.ts
  packages/alfa-css/src/value/index.ts
  packages/alfa-css/src/value/position/component.ts
  packages/alfa-css/src/value/position/keywords.ts
  packages/alfa-css/src/value/position/position.ts
  packages/alfa-css/src/value/position/side.ts
  packages/alfa-css/src/value/shadow.ts
  packages/alfa-css/src/value/shape/circle.ts
  packages/alfa-css/src/value/shape/ellipse.ts
  packages/alfa-css/src/value/shape/inset.ts
  packages/alfa-css/src/value/shape/polygon.ts
  packages/alfa-css/src/value/shape/radius.ts
  packages/alfa-css/src/value/shape/rectangle.ts
  packages/alfa-css/src/value/shape/shape.ts
  packages/alfa-css/src/value/textual/custom-ident.ts
  packages/alfa-css/src/value/textual/ident.ts
  packages/alfa-css/src/value/textual/index.ts
  packages/alfa-css/src/value/textual/keyword.ts
  packages/alfa-css/src/value/textual/string.ts
  packages/alfa-css/src/value/textual/url.ts
  packages/alfa-string/src/string.ts
  packages/alfa-style/src/longhands.ts
  packages/alfa-style/src/property/will-change.ts
  packages/alfa-style/src/tsconfig.json
  packages/alfa-style/test/property/will-change.spec.tsx
  packages/alfa-style/test/tsconfig.json
  yarn.lock
Labels: minor, Language support

#1710 SIA-R83: accept more breakpoints
  .changeset/poor-hounds-perform.md
  .changeset/shy-radios-sip.md
  docs/review/api/alfa-string.api.md
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-string/package.json
  packages/alfa-string/src/string.ts
  packages/alfa-string/test/string.spec.ts
  packages/alfa-string/test/tsconfig.json
  packages/alfa-string/tsconfig.json
  yarn.lock
Labels: minor

#1712 Extract Visible inner text grabber
  .changeset/lucky-kiwis-cheat.md
  .changeset/nasty-paws-begin.md
  .changeset/nasty-paws-search.md
  .changeset/wise-mails-behave.md
  docs/review/api/alfa-string.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-string/src/string.ts
  packages/alfa-style/package.json
  packages/alfa-style/src/node/helpers/inner-text.ts
  packages/alfa-style/src/node/node.ts
  packages/alfa-style/src/style.ts
  packages/alfa-style/src/tsconfig.json
  packages/alfa-style/test/node/helpers/inner-text.spec.tsx
  packages/alfa-style/test/tsconfig.json
  yarn.lock
Labels: minor

#1713 Add SIA-R114: `<title>` is descriptive
  .changeset/shaggy-paws-dance.md
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/src/common/act/index.ts
  packages/alfa-rules/src/common/act/question.ts
  packages/alfa-rules/src/experimental.ts
  packages/alfa-rules/src/sia-r114/rule.ts
  packages/alfa-rules/src/tsconfig.json
  packages/alfa-rules/test/sia-r114/rule.spec.tsx
  packages/alfa-rules/test/tsconfig.json
Labels: minor

#1714 Add ARIA and Best Practice requirements
  .changeset/new-goats-unite.md
  .changeset/rare-plants-develop.md
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-rules.api.md
  docs/review/api/alfa-wcag.api.md
  packages/alfa-act/src/requirement.ts
  packages/alfa-rules/src/index.ts
  packages/alfa-rules/src/requirements/aria.ts
  packages/alfa-rules/src/requirements/best-practice.ts
  packages/alfa-rules/src/requirements/index.ts
  packages/alfa-rules/src/sia-r18/rule.ts
  packages/alfa-rules/src/sia-r19/rule.ts
  packages/alfa-rules/src/sia-r20/rule.ts
  packages/alfa-rules/src/sia-r21/rule.ts
  packages/alfa-rules/src/sia-r40/rule.ts
  packages/alfa-rules/src/sia-r53/rule.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r56/rule.ts
  packages/alfa-rules/src/sia-r57/rule.ts
  packages/alfa-rules/src/sia-r59/rule.ts
  packages/alfa-rules/src/sia-r60/rule.ts
  packages/alfa-rules/src/sia-r61/rule.ts
  packages/alfa-rules/src/sia-r70/rule.ts
  packages/alfa-rules/src/sia-r72/rule.ts
  packages/alfa-rules/src/sia-r75/rule.ts
  packages/alfa-rules/src/sia-r78/rule.ts
  packages/alfa-rules/src/sia-r79/rule.ts
  packages/alfa-rules/src/sia-r85/rule.ts
  packages/alfa-rules/src/sia-r86/rule.ts
  packages/alfa-rules/src/sia-r87/rule.ts
  packages/alfa-rules/src/tsconfig.json
  packages/alfa-wcag/src/criterion.ts
  packages/alfa-wcag/src/technique.ts
Labels: minor

#1715 Remove duplicated test
  packages/alfa-rules/test/sia-r114/rule.spec.tsx
Labels: internal

#1717 Escape SIA-R44 early if there is no orientation media query
  packages/alfa-rules/src/sia-r44/rule.ts
Labels: internal, Performance
