Repository Siteimprove/alfa, pull requests merged in 2024-01, with the labels that each got.

#1542 Refactor `@siteimprove/alfa-media`
  docs/review/api/alfa-dom.api.md
  docs/review/api/alfa-media.api.md
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-dom/src/style/rule/supports.ts
  packages/alfa-media/package.json
  packages/alfa-media/src/condition/and.ts
  packages/alfa-media/src/condition/condition.ts
  packages/alfa-media/src/condition/index.ts
  packages/alfa-media/src/condition/not.ts
  packages/alfa-media/src/condition/or.ts
  packages/alfa-media/src/feature/comparison.ts
  packages/alfa-media/src/feature/feature.ts
  packages/alfa-media/src/feature/height.ts
  packages/alfa-media/src/feature/index.ts
  packages/alfa-media/src/feature/orientation.ts
  packages/alfa-media/src/feature/scripting.ts
  packages/alfa-media/src/feature/width.ts
  packages/alfa-media/src/index.ts
  packages/alfa-media/src/list.ts
  packages/alfa-media/src/matchable.ts
  packages/alfa-media/src/media.ts
  packages/alfa-media/src/modifier.ts
  packages/alfa-media/src/query.ts
  packages/alfa-media/src/resolver.ts
  packages/alfa-media/src/type.ts
  packages/alfa-media/src/value/bound.ts
  packages/alfa-media/src/value/discrete.ts
  packages/alfa-media/src/value/index.ts
  packages/alfa-media/src/value/range.ts
  packages/alfa-media/src/value/value.ts
  packages/alfa-media/test/media.spec.ts
  packages/alfa-media/tsconfig.json
  yarn.lock
Labels: internal

#1546 `@siteimprove/alfa-dom`: Break circular import
  packages/alfa-dom/src/node/element.ts
Labels: internal

#1547 Fix tree traversal of flat tree
  .changeset/dirty-lizards-explode.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/shadow.ts
  packages/alfa-dom/src/node/text.ts
  packages/alfa-dom/src/node/traversal/get-nodes-between.ts
  packages/alfa-dom/test/traversal.spec.tsx
  packages/alfa-dom/tsconfig.json
Labels: patch

#1550 Add `style` attribute and importance to cascade sort
  .changeset/kind-singers-teach.md
  docs/review/api/alfa-cascade.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-cascade/src/block.ts
  packages/alfa-cascade/src/cascade.ts
  packages/alfa-cascade/src/precedence/origin.ts
  packages/alfa-cascade/src/precedence/precedence.ts
  packages/alfa-cascade/src/rule-tree.ts
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-cascade/test/cascade.spec.tsx
  packages/alfa-cascade/test/rule-tree.spec.ts
  packages/alfa-cascade/test/selector-map.spec.tsx
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-style/src/style.ts
  packages/alfa-style/src/variable.ts
  packages/alfa-style/test/style.spec.tsx
  packages/alfa-style/test/variable.spec.ts
Labels: minor

#1551 Make punctuation-only texts inapplicable in R69
  .changeset/nine-cycles-search.md
  packages/alfa-rules/src/sia-r69/rule.ts
  packages/alfa-rules/test/sia-r69/rule.spec.tsx
Labels: minor

#1553 Support `:host` pseudo class
  .changeset/curly-apes-repeat.md
  .changeset/eighty-peaches-clean.md
  docs/review/api/alfa-selector.api.md
  packages/alfa-cascade/src/block.ts
  packages/alfa-cascade/src/cascade.ts
  packages/alfa-cascade/src/precedence/encapsulation.ts
  packages/alfa-cascade/src/precedence/index.ts
  packages/alfa-cascade/src/precedence/order.ts
  packages/alfa-cascade/src/precedence/precedence.ts
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-cascade/test/block.spec.tsx
  packages/alfa-cascade/test/cascade.spec.tsx
  packages/alfa-cascade/test/rule-tree.spec.ts
  packages/alfa-cascade/test/selector-map.spec.tsx
  packages/alfa-cascade/tsconfig.json
  packages/alfa-selector/package.json
  packages/alfa-selector/src/selector/index.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/host.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/pseudo-class.ts
  packages/alfa-selector/src/specificity.ts
  packages/alfa-selector/test/pseudo-class.spec.tsx
  packages/alfa-selector/tsconfig.json
  packages/alfa-style/test/style.spec.tsx
  yarn.lock
Labels: minor

#1554 Support `:host-context` pseudo-class
  .changeset/rare-masks-lick.md
  docs/review/api/alfa-selector.api.md
  packages/alfa-cascade/README.md
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-cascade/test/cascade.spec.tsx
  packages/alfa-selector/src/selector/index.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/host-context.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/host.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/pseudo-class.ts
  packages/alfa-selector/test/pseudo-class.spec.tsx
  packages/alfa-selector/tsconfig.json
Labels: minor

#1559 Support `::slotted` pseudo-element
  .changeset/eighty-peaches-clean.md
  .changeset/kind-singers-teach.md
  .changeset/rare-masks-lick.md
  docs/review/api/alfa-selector.api.md
  packages/alfa-cascade/src/block.ts
  packages/alfa-cascade/src/cascade.ts
  packages/alfa-cascade/src/precedence/encapsulation.ts
  packages/alfa-cascade/src/rule-tree.ts
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-cascade/test/block.spec.tsx
  packages/alfa-cascade/test/cascade.spec.tsx
  packages/alfa-cascade/test/rule-tree.spec.ts
  packages/alfa-cascade/test/selector-map.spec.tsx
  packages/alfa-selector/src/selector/complex.ts
  packages/alfa-selector/src/selector/compound.ts
  packages/alfa-selector/src/selector/index.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/host.ts
  packages/alfa-selector/src/selector/simple/pseudo-element/index.ts
  packages/alfa-selector/src/selector/simple/pseudo-element/pseudo-element.ts
  packages/alfa-selector/src/selector/simple/pseudo-element/slotted.ts
  packages/alfa-selector/test/pseudo-class.spec.tsx
  packages/alfa-selector/test/pseudo-element.spec.tsx
  packages/alfa-selector/test/shadow.spec.tsx
  packages/alfa-selector/tsconfig.json
Labels: minor

#1560 Fix ownership of rules
  .changeset/gentle-tomatoes-draw.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/style/rule.ts
  packages/alfa-dom/test/style.spec.ts
  packages/alfa-dom/tsconfig.json
Labels: patch
