Repository Siteimprove/alfa, pull requests merged in 2024-07, with the labels that each got.

#1643 Move changeset generator to CJS
  .gitignore
  docs/review/api/alfa-toolchain.api.md
  packages/alfa-toolchain/package.json
  packages/alfa-toolchain/src/changeset/changelog-individual.cts
  packages/alfa-toolchain/src/index.ts
  packages/alfa-toolchain/src/tsconfig.json
Labels: internal

#1644 Fix usages of `__dirname`
  .changeset/dull-beers-attend.md
  packages/alfa-aria/scripts/attributes.ts
  packages/alfa-aria/scripts/name-testable-statements.ts
  packages/alfa-aria/scripts/roles.ts
  packages/alfa-compatibility/scripts/browsers.ts
  packages/alfa-compatibility/scripts/features.ts
  packages/alfa-iana/scripts/languages.ts
  packages/alfa-wcag/scripts/criteria.ts
  packages/alfa-wcag/scripts/techniques.ts
Labels: internal

#1645 Fix `files` to also include `.cjs` file in the package.
  .changeset/six-turtles-push.md
  packages/alfa-toolchain/package.json
Labels: internal

#1630 R111 and R113: Handle targets scrolled behind
  .changeset/dry-ducks-pretend.md
  .changeset/great-eagles-work.md
  docs/review/api/alfa-style.api.md
  packages/alfa-rules/src/common/applicability/targets-of-pointer-events.ts
  packages/alfa-rules/test/sia-r113/rule.spec.tsx
  packages/alfa-style/src/node/node.ts
  packages/alfa-style/src/node/predicate/is-scrolled-behind.ts
  packages/alfa-style/src/style.ts
  packages/alfa-style/src/tsconfig.json
  packages/alfa-style/test/node/predicate/is-scrolled-behind.spec.tsx
  packages/alfa-style/test/tsconfig.json
Labels: bug

#1647 Grab adopted stylesheets in Native.fromNode
  packages/alfa-dom/src/native.ts
  packages/alfa-dom/test/native.spec.tsx
Labels: Language support

#1648 Include descendants in clickable area computation
  .changeset/happy-lions-tie.md
  .changeset/sixty-trainers-sleep.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/node/query/inclusive-element-descendants.ts
  packages/alfa-dom/src/node/query/index.ts
  packages/alfa-dom/src/tsconfig.json
  packages/alfa-rules/src/common/applicability/targets-of-pointer-events.ts
  packages/alfa-rules/src/common/dom/get-clickable-box.ts
  packages/alfa-rules/src/common/predicate/has-sufficient-size.ts
  packages/alfa-rules/src/sia-r111/rule.ts
  packages/alfa-rules/src/sia-r113/rule.ts
  packages/alfa-rules/src/tsconfig.json
  packages/alfa-rules/test/sia-r111/rule.spec.tsx
  packages/alfa-rules/test/sia-r113/rule.spec.tsx
Labels: bug

#1650 Add `assignedSlot` to high verbosity serialization of elements
  .changeset/shaggy-maps-give.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/test/node.spec.tsx
Labels: minor

#1654 Revert to yarn publish
  .changeset/soft-dodos-carry.md
  .github/workflows/alfa-release.yml
Labels: internal

#1655 Improve handling of default options in `Page#toJSON`
  .changeset/dirty-horses-exist.md
  packages/alfa-web/src/page.ts
Labels: patch

#1656 Adopted Style Sheets JSDOM workaround
  .changeset/twenty-trees-sit.md
  packages/alfa-dom/src/native.ts
  packages/alfa-dom/test/native.spec.tsx
Labels: patch

#1658 Export version for easier access
  .changeset/olive-jars-drive.md
  .github/workflows/alfa-release.yml
  docs/review/api/alfa-rules.api.md
  packages/alfa-rules/get-version.sh
  packages/alfa-rules/package.json
  packages/alfa-rules/src/index.ts
  packages/alfa-rules/src/tsconfig.json
  packages/alfa-rules/src/version.ts
Labels: patch

#1659 Publish with npm
  .changeset/lemon-pans-jog.md
  .github/workflows/alfa-release.yml
Labels: internal

#1660 Add z-index property
  .changeset/rude-kiwis-nail.md
  docs/review/api/alfa-style.api.md
  packages/alfa-style/src/longhands.ts
  packages/alfa-style/src/property/z-index.ts
  packages/alfa-style/src/tsconfig.json
  packages/alfa-style/test/property/z-index.spec.tsx
  packages/alfa-style/test/tsconfig.json
Labels: Language support

#1662 Update Puppeteer
  packages/alfa-aria/package.json
  packages/alfa-wcag/package.json
  yarn.lock
Labels: dependencies
