Repository Siteimprove/alfa, pull requests merged in 2024-09, with the labels that each got.

#1677 De-activate npmjs publication
  .changeset/quiet-squids-kiss.md
  .github/workflows/alfa-release.yml
Labels: minor

#1678 Make arguments of `Native` functions optional
  .changeset/neat-papayas-vanish.md
  .changeset/rude-hornets-buy.md
  packages/alfa-device/src/native.ts
  packages/alfa-dom/src/native.ts
  packages/alfa-dom/test/native.spec.tsx
Labels: internal

#1680 Npmjs publish
  .changeset/fluffy-pumpkins-happen.md
  .github/workflows/alfa-release.yml
Labels: internal

#1683 Improve visibility detection of `<option>`
  .changeset/gentle-birds-sniff.md
  .changeset/nasty-cooks-greet.md
  .changeset/olive-goats-fix.md
  .changeset/seven-eggs-run.md
  .changeset/swift-meals-check.md
  .changeset/twenty-flies-applaud.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-aria/src/feature.ts
  packages/alfa-dom/src/index.ts
  packages/alfa-dom/src/jsx-runtime.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/element/augment.ts
  packages/alfa-dom/src/node/element/input-type.ts
  packages/alfa-dom/src/node/element/predicate/has-display-size.ts
  packages/alfa-dom/src/node/element/predicate/has-input-type.ts
  packages/alfa-dom/src/tsconfig.json
  packages/alfa-dom/test/node/element.spec.tsx
  packages/alfa-rules/package.json
  packages/alfa-rules/src/sia-dr18/rule.ts
  packages/alfa-rules/src/sia-r18/rule.ts
  packages/alfa-rules/src/tsconfig.json
  packages/alfa-style/src/node/predicate/is-option-hidden.ts
  packages/alfa-style/src/node/predicate/is-visible.ts
  packages/alfa-style/src/tsconfig.json
  packages/alfa-style/test/node/predicate/is-option-hidden.spec.tsx
  packages/alfa-style/test/node/predicate/is-visible.spec.tsx
  packages/alfa-style/test/tsconfig.json
  yarn.lock
Labels: major

#1684 Support `:checked` pseudo-class
  .changeset/strange-masks-fly.md
  docs/review/api/alfa-selector.api.md
  packages/alfa-selector/src/selector/simple/pseudo-class/checked.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
  packages/alfa-selector/src/tsconfig.json
  packages/alfa-selector/test/pseudo-class.spec.tsx
Labels: minor, Language support

#1686 Clean up
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/query/inclusive-element-descendants.ts
  packages/alfa-style/src/node/predicate/is-option-hidden.ts
  packages/alfa-style/src/node/predicate/is-scrolled-behind.ts
Labels: internal

#1679 Add support for `contain` property
  .changeset/hip-ducks-call.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/tsconfig.json
  packages/alfa-css/src/value/contain.ts
  packages/alfa-css/src/value/index.ts
  packages/alfa-style/src/longhands.ts
  packages/alfa-style/src/property/contain.ts
  packages/alfa-style/src/tsconfig.json
  packages/alfa-style/test/property/contain.spec.tsx
  packages/alfa-style/test/tsconfig.json
Labels: minor, Language support

#1689 Support used values
  .changeset/ninety-ligers-fetch.md
  .changeset/twenty-snails-tap.md
  docs/review/api/alfa-style.api.md
  packages/alfa-style/src/longhand.ts
  packages/alfa-style/src/predicate/is-block-container.ts
  packages/alfa-style/src/predicate/is-flex-container.ts
  packages/alfa-style/src/predicate/is-grid-container.ts
  packages/alfa-style/src/property/overflow-x.ts
  packages/alfa-style/src/property/overflow-y.ts
  packages/alfa-style/src/property/text-overflow.ts
  packages/alfa-style/src/style.ts
  packages/alfa-style/src/tsconfig.json
  packages/alfa-style/test/common.ts
  packages/alfa-style/test/property/overflow.spec.tsx
  packages/alfa-style/test/property/text-overflow.spec.tsx
  packages/alfa-style/test/tsconfig.json
Labels: minor

#1688 Support for `scale` and `translate` CSS properties
  .changeset/angry-chairs-serve.md
  .changeset/witty-starfishes-chew.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-style.api.md
  packages/alfa-css/src/value/transform/scale.ts
  packages/alfa-css/src/value/transform/transform.ts
  packages/alfa-css/src/value/transform/translate.ts
  packages/alfa-css/test/value/transform/scale.spec.ts
  packages/alfa-css/test/value/transform/translate.spec.ts
  packages/alfa-style/src/longhands.ts
  packages/alfa-style/src/property/scale.ts
  packages/alfa-style/src/property/translate.ts
  packages/alfa-style/src/tsconfig.json
  packages/alfa-style/test/property/scale.spec.tsx
  packages/alfa-style/test/property/transform.spec.tsx
  packages/alfa-style/test/property/translate.spec.tsx
  packages/alfa-style/test/tsconfig.json
Labels: minor, Language support

#1690 Document / check list how to add a new style property
  docs/guides/README.md
  docs/guides/changeset.md
  docs/guides/debugging.md
  docs/guides/writing-a-parser.md
  packages/alfa-style/docs/adding-new-property.md
Labels: documentation
