Repository Siteimprove/alfa, pull requests merged in 2024-06, with the labels that each got.

#1619 Improve CSS rule type detection
  .changeset/healthy-peaches-begin.md
  packages/alfa-dom/src/native.ts
Labels: patch

#1620 Clean up code
  packages/alfa-cascade/test/cascade.spec.tsx
  packages/alfa-css/src/value/image/gradient/gradient.ts
  packages/alfa-css/test/value/numeric/angle-percentage.spec.ts
  packages/alfa-iana/scripts/languages.js
  packages/alfa-style/src/property/border-image-outset.ts
  packages/alfa-style/src/property/border-radius.ts
Labels: internal

#1618 Add verbosity option for JSON serialization of tree nodes
  .changeset/eight-jokes-rescue.md
  .changeset/orange-hairs-fold.md
  .changeset/yellow-gifts-sort.md
  .github/workflows/integrate.yml
  docs/review/api/alfa-act.api.md
  docs/review/api/alfa-aria.api.md
  docs/review/api/alfa-cascade.api.md
  docs/review/api/alfa-dom.api.md
  docs/review/api/alfa-json.api.md
  docs/review/api/alfa-rules.api.md
  docs/review/api/alfa-selector.api.md
  docs/review/api/alfa-style.api.md
  docs/review/api/alfa-table.api.md
  docs/review/api/alfa-tree.api.md
  docs/review/api/alfa-web.api.md
  docs/review/api/alfa-xpath.api.md
  packages/alfa-act/src/outcome.ts
  packages/alfa-dom/src/h.ts
  packages/alfa-dom/src/jsx.ts
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/src/node/attribute.ts
  packages/alfa-dom/src/node/comment.ts
  packages/alfa-dom/src/node/document.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/fragment.ts
  packages/alfa-dom/src/node/shadow.ts
  packages/alfa-dom/src/node/text.ts
  packages/alfa-dom/src/node/type.ts
  packages/alfa-dom/test/h.spec.ts
  packages/alfa-dom/test/node.spec.tsx
  packages/alfa-json/src/serializable.ts
  packages/alfa-rules/src/common/act/group.ts
  packages/alfa-rules/test/common/evaluate.ts
  packages/alfa-tree/src/tree.ts
Labels: major

#1622 Accept and pass down options in serialization of collection-like types (and `Page` and releated)
  .changeset/lazy-phones-search.md
  docs/review/api/alfa-array.api.md
  docs/review/api/alfa-collection.api.md
  docs/review/api/alfa-css-feature.api.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-device.api.md
  docs/review/api/alfa-graph.api.md
  docs/review/api/alfa-http.api.md
  docs/review/api/alfa-iterable.api.md
  docs/review/api/alfa-lazy.api.md
  docs/review/api/alfa-list.api.md
  docs/review/api/alfa-map.api.md
  docs/review/api/alfa-media.api.md
  docs/review/api/alfa-option.api.md
  docs/review/api/alfa-record.api.md
  docs/review/api/alfa-result.api.md
  docs/review/api/alfa-rules.api.md
  docs/review/api/alfa-selector.api.md
  docs/review/api/alfa-sequence.api.md
  docs/review/api/alfa-set.api.md
  docs/review/api/alfa-slice.api.md
  docs/review/api/alfa-web.api.md
  docs/review/api/alfa-xpath.api.md
  packages/alfa-array/src/array.ts
  packages/alfa-collection/src/collection.ts
  packages/alfa-device/src/device.ts
  packages/alfa-device/src/display.ts
  packages/alfa-device/src/preference.ts
  packages/alfa-device/src/scripting.ts
  packages/alfa-device/src/viewport.ts
  packages/alfa-graph/src/graph.ts
  packages/alfa-http/src/header.ts
  packages/alfa-http/src/headers.ts
  packages/alfa-http/src/request.ts
  packages/alfa-http/src/response.ts
  packages/alfa-iterable/src/iterable.ts
  packages/alfa-lazy/src/lazy.ts
  packages/alfa-list/src/list.ts
  packages/alfa-map/src/map.ts
  packages/alfa-option/src/option.ts
  packages/alfa-option/src/some.ts
  packages/alfa-record/src/record.ts
  packages/alfa-result/src/err.ts
  packages/alfa-result/src/ok.ts
  packages/alfa-result/src/result.ts
  packages/alfa-rules/test/common/evaluate.ts
  packages/alfa-rules/test/sia-r41/rule.spec.tsx
  packages/alfa-sequence/src/cons.ts
  packages/alfa-sequence/src/sequence.ts
  packages/alfa-set/src/set.ts
  packages/alfa-slice/src/slice.ts
  packages/alfa-web/src/page.ts
Labels: minor

#1627 Ignore empty URLs in background images
  .changeset/fifty-shrimps-hear.md
  packages/alfa-rules/src/common/dom/get-colors/get-layers.ts
  packages/alfa-rules/test/common/dom/get-colors.spec.tsx
Labels: patch

#1629 Support `:any-link`
  .changeset/silly-wombats-do.md
  docs/review/api/alfa-selector.api.md
  packages/alfa-selector/src/common/is-link.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/any-link.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/link.ts
  packages/alfa-selector/src/selector/simple/pseudo-class/visited.ts
  packages/alfa-selector/test/pseudo-class.spec.tsx
  packages/alfa-selector/tsconfig.json
Labels: minor

#1625 Accept dimension divisions in calculations
  .changeset/big-camels-rhyme.md
  .changeset/big-cobras-sing.md
  .changeset/little-weeks-knock.md
  .changeset/nine-trainers-search.md
  .changeset/pretty-ways-reply.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-selective.api.md
  packages/alfa-css/docs/dependency-graph.dot
  packages/alfa-css/docs/dependency-graph.svg
  packages/alfa-css/src/calculation/math-expression/expression.ts
  packages/alfa-css/src/calculation/math-expression/function.ts
  packages/alfa-css/src/calculation/math-expression/index.ts
  packages/alfa-css/src/calculation/math-expression/math.ts
  packages/alfa-css/src/calculation/math-expression/operation.ts
  packages/alfa-css/src/calculation/math-expression/value.ts
  packages/alfa-css/src/calculation/numeric/dimension.ts
  packages/alfa-css/src/calculation/numeric/length.ts
  packages/alfa-css/src/unit/unit.ts
  packages/alfa-css/src/value/numeric/angle-percentage.ts
  packages/alfa-css/src/value/numeric/angle.ts
  packages/alfa-css/src/value/numeric/dimension.ts
  packages/alfa-css/src/value/numeric/integer.ts
  packages/alfa-css/src/value/numeric/length-percentage.ts
  packages/alfa-css/src/value/numeric/length.ts
  packages/alfa-css/src/value/numeric/number.ts
  packages/alfa-css/src/value/numeric/numeric.ts
  packages/alfa-css/src/value/numeric/percentage.ts
  packages/alfa-css/src/value/resolvable.ts
  packages/alfa-css/src/value/shadow.ts
  packages/alfa-css/src/value/transform/translate.ts
  packages/alfa-css/test/calculation/math-functions.spec.ts
  packages/alfa-css/test/value/numeric/angle-percentage.spec.ts
  packages/alfa-css/test/value/numeric/angle.spec.ts
  packages/alfa-css/test/value/numeric/length-percentage.spec.ts
  packages/alfa-css/test/value/numeric/length.spec.ts
  packages/alfa-css/test/value/numeric/number.spec.ts
  packages/alfa-css/test/value/numeric/percentage.spec.ts
  packages/alfa-rules/docs/dependency-graph.svg
  packages/alfa-selective/package.json
  packages/alfa-selective/src/selective.ts
  packages/alfa-selective/tsconfig.json
  packages/alfa-style/docs/dependency-graph.dot
  packages/alfa-style/docs/dependency-graph.svg
  packages/alfa-style/src/property/background-color.ts
  packages/alfa-style/src/property/border-image-slice.ts
  packages/alfa-style/src/property/border-top-color.ts
  packages/alfa-style/src/property/color.ts
  packages/alfa-style/src/property/cursor.ts
  packages/alfa-style/src/property/font-weight.ts
  packages/alfa-style/src/property/outline-color.ts
  packages/alfa-style/src/property/text-decoration-color.ts
  packages/alfa-style/src/property/text-decoration-thickness.ts
  packages/alfa-toolchain/docs/dependency-graph.dot
  packages/alfa-toolchain/docs/dependency-graph.svg
  yarn.lock
Labels: minor

#1631 Fix a type declaration
  .changeset/odd-weeks-design.md
  docs/review/api/alfa-css.api.md
  packages/alfa-css/src/value/numeric/numeric.ts
Labels: patch

#1634 Update typescript
  .changeset/nasty-horses-build.md
  docs/review/api/alfa-aria.api.md
  docs/review/api/alfa-cascade.api.md
  docs/review/api/alfa-css.api.md
  docs/review/api/alfa-dom.api.md
  docs/review/api/alfa-option.api.md
  docs/review/api/alfa-result.api.md
  docs/review/api/alfa-rules.api.md
  docs/review/api/alfa-selector.api.md
  docs/review/api/alfa-style.api.md
  docs/review/api/alfa-table.api.md
  docs/review/api/alfa-tree.api.md
  docs/review/api/alfa-web.api.md
  docs/review/api/alfa-xpath.api.md
  package.json
  packages/alfa-option/package.json
  packages/alfa-option/src/none.ts
  packages/alfa-option/src/option.ts
  packages/alfa-option/src/some.ts
  packages/alfa-option/tsconfig.json
  packages/alfa-result/package.json
  packages/alfa-result/src/err.ts
  packages/alfa-result/src/ok.ts
  packages/alfa-result/src/result.ts
  packages/alfa-result/tsconfig.json
  packages/alfa-rules/src/sia-r87/rule.ts
  packages/alfa-rules/test/sia-r41/rule.spec.tsx
  packages/alfa-table/src/cell.ts
  packages/alfa-xpath/src/syntax/lexer.ts
  yarn.lock
Labels: minor

#1635 Fix export field
  .changeset/sour-candles-protect.md
  packages/alfa-device/package.json
Labels: internal
