Repository Siteimprove/alfa, pull requests merged in 2024-02, with the labels that each got.

#1564 Implement SIA-R111 (Target size)
  .changeset/lovely-lamps-roll.md
  .changeset/pretty-eels-sin.md
  docs/review/api/alfa-style.api.md
  packages/alfa-rules/src/rules.ts
  packages/alfa-rules/src/sia-r111/rule.ts
  packages/alfa-rules/test/sia-r111/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
  packages/alfa-style/src/longhands.ts
  packages/alfa-style/src/property/pointer-events.ts
  packages/alfa-style/tsconfig.json
Labels: minor

#1566 Fix spacing in name computation
  .changeset/afraid-beers-share.md
  .changeset/thick-hornets-accept.md
  .changeset/wicked-trains-scream.md
  docs/review/api/alfa-aria.api.md
  packages/alfa-aria/scripts/name-testable-statements.js
  packages/alfa-aria/src/dom/predicate/has-accessible-name.ts
  packages/alfa-aria/src/feature.ts
  packages/alfa-aria/src/name.ts
  packages/alfa-aria/src/name/index.ts
  packages/alfa-aria/src/name/name.ts
  packages/alfa-aria/src/name/predicate.ts
  packages/alfa-aria/src/name/predicate/has-value.ts
  packages/alfa-aria/src/name/predicate/index.ts
  packages/alfa-aria/src/name/source.ts
  packages/alfa-aria/src/name/state.ts
  packages/alfa-aria/test/name-testable-statements.spec.tsx
  packages/alfa-aria/test/name.spec.tsx
  packages/alfa-aria/test/node.spec.tsx
  packages/alfa-aria/tsconfig.json
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/text.ts
Labels: major

#1567 Await on `prettier.format`
  packages/alfa-aria/scripts/attributes.js
  packages/alfa-aria/scripts/roles.js
  packages/alfa-compatibility/scripts/browsers.js
  packages/alfa-compatibility/scripts/features.js
  packages/alfa-iana/scripts/languages.js
  packages/alfa-wcag/scripts/criteria.js
  packages/alfa-wcag/scripts/techniques.js
Labels: internal

#1568 Accessible name: add spaces around table cell content
  .changeset/afraid-beers-share.md
  packages/alfa-aria/scripts/name-testable-statements.js
  packages/alfa-aria/src/name/name.ts
  packages/alfa-aria/test/name-testable-statements.spec.tsx
Labels: patch

#1572 Add package `alfa-string`
  .changeset/eight-dancers-itch.md
  config/package-dependency-graph.ts
  docs/dependency-graph.dot
  docs/dependency-graph.png
  docs/review/api/alfa-string.api.md
  packages/alfa-act/package.json
  packages/alfa-act/src/diagnostic.ts
  packages/alfa-act/tsconfig.json
  packages/alfa-aria/package.json
  packages/alfa-aria/src/node/container.ts
  packages/alfa-aria/src/node/element.ts
  packages/alfa-aria/tsconfig.json
  packages/alfa-dom/package.json
  packages/alfa-dom/src/node/document.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/fragment.ts
  packages/alfa-dom/src/node/shadow.ts
  packages/alfa-dom/src/style/rule/font-face.ts
  packages/alfa-dom/src/style/rule/keyframe.ts
  packages/alfa-dom/src/style/rule/keyframes.ts
  packages/alfa-dom/src/style/rule/media.ts
  packages/alfa-dom/src/style/rule/page.ts
  packages/alfa-dom/src/style/rule/style.ts
  packages/alfa-dom/src/style/rule/supports.ts
  packages/alfa-dom/tsconfig.json
  packages/alfa-rules/package.json
  packages/alfa-rules/src/common/normalize.ts
  packages/alfa-rules/src/sia-r10/rule.ts
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-rules/src/sia-r15/rule.ts
  packages/alfa-rules/src/sia-r41/rule.ts
  packages/alfa-rules/src/sia-r55/rule.ts
  packages/alfa-rules/src/sia-r56/rule.ts
  packages/alfa-rules/src/sia-r62/serialise.ts
  packages/alfa-rules/src/sia-r81/rule.ts
  packages/alfa-rules/tsconfig.json
  packages/alfa-string/config/api-extractor.json
  packages/alfa-string/package.json
  packages/alfa-string/src/index.ts
  packages/alfa-string/src/string.ts
  packages/alfa-string/tsconfig.json
  packages/tsconfig.json
  yarn.lock
Labels: minor

#1573 Fix detection of empty titles
  .changeset/sharp-chefs-glow.md
  docs/review/api/alfa-string.api.md
  packages/alfa-dom/src/node.ts
  packages/alfa-rules/src/common/predicate.ts
  packages/alfa-rules/src/common/predicate/is-whitespace.ts
  packages/alfa-rules/src/sia-r1/rule.ts
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-rules/src/sia-r4/rule.ts
  packages/alfa-rules/src/sia-r5/rule.ts
  packages/alfa-rules/src/sia-r57/rule.ts
  packages/alfa-rules/src/sia-r62/rule.ts
  packages/alfa-rules/src/sia-r7/rule.ts
  packages/alfa-rules/src/sia-r74/rule.ts
  packages/alfa-rules/src/sia-r80/rule.ts
  packages/alfa-rules/test/sia-r1/rule.spec.tsx
  packages/alfa-rules/test/sia-r74/rule.spec.tsx
  packages/alfa-rules/tsconfig.json
  packages/alfa-string/src/string.ts
Labels: patch

#1574 Add model for `@layer` rules in `alfa-dom`
  .changeset/stale-numbers-shake.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/index.ts
  packages/alfa-dom/src/style/rule.ts
  packages/alfa-dom/src/style/rule/layer.ts
  packages/alfa-dom/src/style/rule/media.ts
  packages/alfa-dom/tsconfig.json
Labels: minor

#1577 Add model for CSS layers in `alfa-cascade`
  .changeset/four-peaches-wave.md
  docs/review/api/alfa-cascade.api.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-cascade/src/block.ts
  packages/alfa-cascade/src/cascade.ts
  packages/alfa-cascade/src/precedence/index.ts
  packages/alfa-cascade/src/precedence/layer.ts
  packages/alfa-cascade/src/precedence/precedence.ts
  packages/alfa-cascade/src/rule-tree.ts
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-cascade/test/block.spec.tsx
  packages/alfa-cascade/test/cascade.spec.tsx
  packages/alfa-cascade/test/precedence.spec.ts
  packages/alfa-cascade/test/rule-tree.spec.ts
  packages/alfa-cascade/test/selector-map.spec.tsx
  packages/alfa-cascade/tsconfig.json
  packages/alfa-dom/src/h.ts
Labels: minor

#1581 Handle `@layer` rules when building `Cascade`.
  .changeset/empty-jars-hang.md
  .changeset/four-peaches-wave.md
  .changeset/stale-numbers-shake.md
  .changeset/stupid-camels-turn.md
  docs/review/api/alfa-dom.api.md
  docs/review/api/alfa-selective.api.md
  packages/alfa-cascade/package.json
  packages/alfa-cascade/src/precedence/layer.ts
  packages/alfa-cascade/src/selector-map.ts
  packages/alfa-cascade/test/block.spec.tsx
  packages/alfa-cascade/test/cascade.spec.tsx
  packages/alfa-cascade/test/common/index.ts
  packages/alfa-cascade/test/layer.spec.ts
  packages/alfa-cascade/test/selector-map.spec.tsx
  packages/alfa-cascade/tsconfig.json
  packages/alfa-dom/src/style/rule/import.ts
  packages/alfa-dom/src/style/rule/layer.ts
  packages/alfa-dom/src/style/rule/media.ts
  packages/alfa-dom/src/style/rule/style.ts
  packages/alfa-dom/src/style/rule/supports.ts
  packages/alfa-selective/src/selective.ts
  yarn.lock
Labels: minor

#1583 Update to WCAG 2.2
  .changeset/hip-plums-dance.md
  docs/review/api/alfa-wcag.api.md
  packages/alfa-wcag/scripts/criteria.js
  packages/alfa-wcag/scripts/techniques.js
  packages/alfa-wcag/src/criterion.ts
  packages/alfa-wcag/src/criterion/data.ts
  packages/alfa-wcag/src/technique/data.ts
Labels: minor
