Repository Siteimprove/alfa, pull requests merged in 2025-03, with the labels that each got.

#1765 Add minimal serialization of rules
  .changeset/three-cherries-fry.md
  docs/review/api/alfa-act.api.md
  packages/alfa-act/src/outcome.ts
  packages/alfa-act/src/rule.ts
Labels: patch

#1766 Make SIA-R115 look into the full tree
  .changeset/friendly-mangos-check.md
  packages/alfa-rules/src/sia-r115/rule.ts
Labels: patch

#1767 Pass serialization options through questions
  .changeset/strong-eagles-fry.md
  docs/review/api/alfa-act.api.md
  packages/alfa-act/src/question.ts
Labels: patch

#1768 Add support for `Text` layout
  .changeset/cool-zoos-agree.md
  .changeset/odd-needles-remain.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/h.ts
  packages/alfa-dom/src/native.ts
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/src/node/element.ts
  packages/alfa-dom/src/node/element/predicate.ts
  packages/alfa-dom/src/node/predicate.ts
  packages/alfa-dom/src/node/predicate/has-box.ts
  packages/alfa-dom/src/node/text.ts
  packages/alfa-dom/src/tsconfig.json
  packages/alfa-dom/test/h.spec.ts
  packages/alfa-dom/test/native.spec.tsx
  packages/alfa-rules/src/sia-r80/rule.ts
  packages/alfa-style/src/node/predicate/is-clipped.ts
  packages/alfa-style/src/node/predicate/is-offscreen.ts
Labels: minor

#1773 Add dedupe-on-install plugin
  .gitignore
  .yarn/.gitignore
  .yarn/plugins/plugin-dedupe-on-install.cjs
  .yarnrc.yml
Labels: internal

#1774 Add defaults for `Text.of` optional parameters
  .changeset/sour-balloons-sing.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/node/text.ts
  packages/alfa-dom/test/node/text.spec.ts
  packages/alfa-dom/test/tsconfig.json
Labels: bug

#1775 SIA-R83: use text layout
  .changeset/heavy-shoes-sneeze.md
  .changeset/large-mirrors-grow.md
  docs/review/api/alfa-rectangle.api.md
  packages/alfa-rectangle/src/rectangle.ts
  packages/alfa-rules/src/sia-r83/rule.ts
  packages/alfa-rules/test/sia-r83/rule.spec.tsx
Labels: minor

#1777 Update user agent sheet for `<details>` to fix visibility of content
  .changeset/tall-wolves-allow.md
  packages/alfa-cascade/src/user-agent.ts
  packages/alfa-cascade/test/cascade.spec.tsx
  packages/alfa-style/test/node/predicate/is-visible.spec.tsx
Labels: Language support

#1782 SIA-R78: Ignore headings in closed details
  .changeset/tame-news-argue.md
  packages/alfa-rules/src/sia-r78/rule.ts
  packages/alfa-rules/test/sia-r78/rule.spec.tsx
Labels: patch

#1781 Add logs to `Native.fromNode`
  .changeset/slow-kings-whisper.md
  packages/alfa-dom/src/native.ts
Labels: minor

#1786 Simplify the `Native` `map` and `mapAsync` functions in `alfa-dom/native`
  .changeset/orange-falcons-smash.md
  packages/alfa-dom/src/native.ts
Labels: bug
