Repository Siteimprove/alfa, pull requests merged in 2025-01, with the labels that each got.

#1742 Accept callbacks in `Result#*orElse` methods
  .changeset/tiny-pianos-travel.md
  docs/review/api/alfa-result.api.md
  packages/alfa-result/src/err.ts
  packages/alfa-result/src/ok.ts
  packages/alfa-result/src/result.ts
  packages/alfa-result/test/result.spec.ts
Labels: minor

#1745 Package skaffolding
  .changeset/eighty-eels-applaud.md
  .changeset/fifty-kids-hug.md
  .changeset/flat-moose-raise.md
  .changeset/sour-trees-sort.md
  config/knip.ts
  config/validate-structure.json
  docs/review/api/alfa-string.api.md
  packages/alfa-rules/src/sia-r14/rule.ts
  packages/alfa-string/package.json
  packages/alfa-string/src/string.ts
  packages/alfa-string/src/tsconfig.json
  packages/alfa-test-deprecated/package.json
  packages/alfa-toolchain/package.json
  packages/alfa-toolchain/src/create-alfa-package.ts
  packages/alfa-toolchain/src/tsconfig.json
  packages/alfa-toolchain/src/validation/validate-package-json.ts
  yarn.lock
Labels: internal

#1747 Update `changeset`
  package.json
  packages/alfa-toolchain/package.json
  yarn.lock
Labels: dependencies

#1748 Include path in Low verbosity Node serialization
  .changeset/fast-students-count.md
  docs/review/api/alfa-dom.api.md
  packages/alfa-dom/src/node.ts
  packages/alfa-dom/test/node.spec.tsx
Labels: minor

#1749 Update TypeScript
  config/knip.ts
  docs/review/api/alfa-xpath.api.md
  package.json
  packages/alfa-aria/scripts/roles.ts
  yarn.lock
Labels: internal
